### ISSUE TITLE
LineId of AssociatedDocumentLineDocument in IncludedSupplyChainTradeLineItem must be settable

### ISSUE THREAD

**Issue by TomcatBB** [stephanstapel/ZUGFeRD-csharp#108]
The LineId is currently auto generated and starts from 1 with increment of 1 for each TradeLineItem.

Some Customers like the Deutsche Bahn, expect in the LineId their own Id given in the Order. So we need the possibility to set the LineId via code.

I will pull a merge request for this today.

**Comment by stephanstapel** [comment]
I'm not sure if I will integrate this. Certainly not now.

**Comment by TomcatBB** [comment]
i am ready with the code now, and will raise the pull request. 
I implemented it the way, that it is also possible to not specify the LineId, and then it is internaly generated and incremented like before. But now you have the ability to set it, because it is needed in some situations. Specially for the Deutsche Bahn who requires XRechnungen starting from 27.11.2020 on, and want to see their own given LineIDs, not following the schema 1,2,3.
For users who dont want to specify the LineID nothing changes with this implementaion, because of the still existing auto generating as a fallback.

**Comment by Alpini1980** [comment]
I also stumpled accross this field today and beside that it is autoincrement I am not sure if integer is the right choice as the datatype. The "udt:IDType" should  be a string value in CII (and UBL too) - it just needs to be set with unique values.

**Comment by TomcatBB** [comment]
Agree to this. Have a look in my pull request. Part of it is also the change from int to string for the LineId. Because like you said per definition the LineId is a string that has to be unique.

**Comment by Alpini1980** [comment]
Thanks for confirmation @TomcatBB. So hopefully Stephan will merge your code :-) I could need this field too as it seems to be the only possibility to identify a line in a large xRechnung.

The invoices we create contain several thousand TradeLine items. For example a merged Key containing the delivery document ID  + a line-number can be used in this field. In Zugferd format there is an AdditionalReferenceDocument/IsuerAssignedID for such numbers but this field not seems to have been mapped into the XRechnung standard and I did not find any other field in XRechnung standard which could be suitable for a delivery document ID.

Regards, Stefan

**Comment by TomcatBB** [comment]
Can we expect a decision here? Because we have to plan our upcoming release that needs this feature. So we have to decide if we can stick with your Version or if we have to use our own fork? We highly interested to use this version here and not have the need to separate here.

**Comment by stephanstapel** [comment]
Still thinking...

I agree that LineId should be string.
I'm not fine with the function signatures (where you added the lineId parameter). I'd like to make the lineId parameter first and eventually add a second function, i.e.

```csharp
public void AddTradeLineCommentItem(string comment) {}
public void AddTradeLineCommentItem(string lineId, string comment) {}
```


```csharp
public TradeLineItem AddTradeLineItem(string name,
                                     string description = null,
                                     QuantityCodes unitCode = QuantityCodes.Unknown,
                                     decimal? unitQuantity = null,
                                     decimal grossUnitPrice = Decimal.MinValue,
                                     decimal netUnitPrice = Decimal.MinValue,
                                     decimal billedQuantity = Decimal.MinValue,
                                     TaxTypes taxType = TaxTypes.Unknown,
                                     TaxCategoryCodes categoryCode = TaxCategoryCodes.Unknown,
                                     decimal taxPercent = Decimal.MinValue,
                                     string comment = null,
                                     GlobalID id = null,
                                     string sellerAssignedID = "", string buyerAssignedID = "",
                                     string deliveryNoteID = "", DateTime? deliveryNoteDate = null,
                                     string buyerOrderID = "", DateTime? buyerOrderDate = null)
                                     string buyerOrderID = "", DateTime? buyerOrderDate = null
                                     ) {}

public TradeLineItem AddTradeLineItem(string lineId, string name,
                                     string description = null,
                                     QuantityCodes unitCode = QuantityCodes.Unknown,
                                     decimal? unitQuantity = null,
                                     decimal grossUnitPrice = Decimal.MinValue,
                                     decimal netUnitPrice = Decimal.MinValue,
                                     decimal billedQuantity = Decimal.MinValue,
                                     TaxTypes taxType = TaxTypes.Unknown,
                                     TaxCategoryCodes categoryCode = TaxCategoryCodes.Unknown,
                                     decimal taxPercent = Decimal.MinValue,
                                     string comment = null,
                                     GlobalID id = null,
                                     string sellerAssignedID = "", string buyerAssignedID = "",
                                     string deliveryNoteID = "", DateTime? deliveryNoteDate = null,
                                     string buyerOrderID = "", DateTime? buyerOrderDate = null)
                                     string buyerOrderID = "", DateTime? buyerOrderDate = null
                                     ) {}
```

For something as important as the lineId, It'd imho not be good to just append it to the list of parameters.

what do you think?

**Comment by TomcatBB** [comment]
yes you are right, i would prefer the second solution you suggested with the option to set it in first place or leave it complety away, and then use the autogeneration stuff as before, like i implemented?

**Comment by stephanstapel** [comment]
yep. Do you have time to adopt this or could you otherwise split the merge request? It'd probably be helpful if you could PR the stringified version first.

**Comment by TomcatBB** [comment]
i will try to change my solution to the new discused version and raise another pull request

**Comment by TomcatBB** [comment]
updated the pull request with the suggested changes

**Comment by stephanstapel** [comment]
done.
Can you please test the new code?

Furthermore, I'd like to make LineId in AssociatedDocument read only. Do you see any problems if doing so?

The code would look like this:

```csharp
/// <summary>
    /// Representation for general information on item level
    /// </summary>
    public class AssociatedDocument
    {
        /// <summary>
        ///  Detailed information in free text form
        /// </summary>
        public List<Note> Notes { get; set; } = new List<Note>();

        /// <summary>
        /// identifier of the invoice line item
        /// </summary>
        public string LineID { get; internal set; }


        /// <summary>
        /// Initializes a new associated document object, optionally passing a certain lineID
        /// </summary>
        /// <param name="lineID"></param>
        internal AssociatedDocument(string lineID)
        {
            this.LineID = lineID;
        }
    }
```

the setter would be internal and the constructor as well.

**Comment by TomcatBB** [comment]
tested the new code, works perfect.
Also i agree that is maybe a good idea to make the LIneId internal in the AssociatedDocument

**Comment by TomcatBB** [comment]
can you do the change for the internal LineID, because currently i'am very busy?
Thx in advance

**Comment by stephanstapel** [comment]
yes of course. I'll do that tonight. Expect the finalized version tomorrow. I'd be in turn be very grateful if you could test manual and automatic line id generation, eventually even mixed.

**Comment by TomcatBB** [comment]
i have to check if i have time to do this in the next days. For my code i can say, that i tested both scenarios.
