### ISSUE TITLE
Profile.Basic Beispiel

### ISSUE THREAD

**Issue by drocx** [stephanstapel/ZUGFeRD-csharp#11]
Hallo,

erstmal vielen Dank für die Umsetzung dieses tollen Projekts.

Könntest du vielleicht noch, wenn es möglich wäre ein Beispiel für das Profile.Basic ergänzen.

**Comment by stephanstapel** [comment]
Hallo,

vielen Dank!
Nach meinem Verständnis bedeutet BASIC im Wesentlichen, dass die Positionsinformationen entfallen dürfen.
Verstehst Du die Spezifikation auch so?

**Comment by drocx** [comment]
Ja genau.
Es gibt keine Positionsnummer oder Einzelpreise. Die werden zusammengefasst. Zusätzliche Informationen werden dann als Freitext (Included.Note) abgebildet ohne einen "Subject Code".
Zahlungsbedingungen werden ebenfalls als Freitext übergeben. Das sieht man auch im XML File des offiziellen Beispiels:[ZUGFeRD_1p0_BASIC_Einfach.pdf](https://github.com/stephanstapel/ZUGFeRD-csharp/files/892856/ZUGFeRD_1p0_BASIC_Einfach.pdf)

Auf den Seiten 3-7 sieht man welche Codes und Textfelder im Basic Format verwendet werden:
[Das ZUGFeRD-Format_1p0_c1p0_Codelisten.pdf](https://github.com/stephanstapel/ZUGFeRD-csharp/files/892885/Das.ZUGFeRD-Format_1p0_c1p0_Codelisten.pdf)

**Comment by stephanstapel** [comment]
ok. D.h. dass Du annimmst, dass an der Bibliothek Anpassungen notwendig sind, richtig? Die Codes werden momentan unabhängig vom Profil immer genutzt.

Kannst Du die Ausgabe des COMFORT-Beispiels umbauen, so dass es konform ist? Toll wäre auch, wenn Du die ZugFerdComfortEinfachGenerator.cs anpassen könntest zu einer ZugFerdBasicEinfachGenerator.cs.
Das würde mir helfen.
Du brauchst es nicht einzuchecken, wenn das zu kompliziert ist, kopiere es gerne einfach in diesen Thread!

**Comment by drocx** [comment]
Da bin ich mir nicht sicher.

Das Beispiel kann ich umbauen. Den Generator wahrscheinlich auch. Melde mich sobald ich damit fertig bin.

**Comment by stephanstapel** [comment]
prima, vielen Dank für die Pull Requests!

**Comment by stephanstapel** [comment]
vielen Dank für die Ergänzungen. Ich habe noch einige kleinere Anpassungen gemacht und die Bibliothek als Version 2.2.0.0 auf nuget veröffentlicht!
