### ISSUE TITLE
Missing TaxCategoryCodes

### ISSUE THREAD

**Issue by ROBdk97** [stephanstapel/ZUGFeRD-csharp#111]
TaxCategoryCodes like D, F, I,  J, K, L and M are missing
https://service.unece.org/trade/untdid/d20a/tred/tred5305.htm
They are also mentioned in the ZUGFeRD Specifications and where added in 2016 to the norm
(All the years and can be found under Data element directory (EDED): https://www.unece.org/tradewelcome/un-centre-for-trade-facilitation-and-e-business-uncefact/outputs/standards/unedifact/directories/2011-present.html)

**Comment by stephanstapel** [comment]
Thanks for your issue.

What is really strange: the Excel list in ZUGFeRD 2.1.1 shows even different values:

![grafik](https://user-images.githubusercontent.com/2912080/97973086-d1c45580-1dc5-11eb-8b71-6d2209727530.png)

I'm of course happy to add further category codes. Could you contribute some documentation for the empty values:
- D
- F
- I
- J
- K (VAT exempt for EEA intra-community supply of goods   and services)
- L (Canary Islands general indirect tax)
- M (Tax for production, services and importation in Ceuta and Melilla)

?

**Comment by ROBdk97** [comment]
- D     Value Added Tax (VAT) margin scheme - travel agents

              Indication that the VAT margin scheme for travel agents
              is applied.

- F     Value Added Tax (VAT) margin scheme - second-hand goods

              Indication that the VAT margin scheme for second-hand
              goods is applied.

- I     Value Added Tax (VAT) margin scheme - works of art Margin scheme � Works of art

              Indication that the VAT margin scheme for works of art
              is applied.

- J     Value Added Tax (VAT) margin scheme - collector�s items and antiques

              Indication that the VAT margin scheme for collector�s
              items and antiques is applied.

-  K     VAT exempt for EEA intra-community supply of goods and services

              A tax category code indicating the item is VAT exempt
              due to an intra-community supply in the European
              Economic Area.

- L     Canary Islands general indirect tax

              Impuesto General Indirecto Canario (IGIC) is an indirect
              tax levied on goods and services supplied in the Canary
              Islands (Spain) by traders and professionals, as well as
              on import of goods.

- M     Tax for production, services and importation in Ceuta and Melilla

              Impuesto sobre la Producci�n, los Servicios y la
              Importaci�n (IPSI) is an indirect municipal tax, levied
              on the production, processing and import of all kinds of
              movable tangible property, the supply of services and
              the transfer of immovable property located in the cities
              of Ceuta and Melilla.

Taken from https://service.unece.org/trade/untdid/d20a/tred/tred5305.htm

**Comment by ROBdk97** [comment]
I also found out that the Country and the Currency Codes you use differ from the ones mentioned in the ZUGFeRD Specifications. The ones used in the project also include the DDR and other Countries and Currencies that do not exist anymore.
