### ISSUE TITLE
XRechnung 2.0 and 1.2 switchable?

### ISSUE THREAD

**Issue by TomcatBB** [stephanstapel/ZUGFeRD-csharp#113]
in the current code, not in the released package, the Version for XRechnung is hard coded to 2.0. Does it make more sense to set the version by the User, because when you release the new Package before the 01.01.2021 the Version 2.0 is not valid. It becomes valid starting 01.01.2021. So maybe it would make more sense to let the caller control which version he wants?

**Comment by stephanstapel** [comment]
It's just a one time switch and the formats are identical anyway. That's why I chose this way.

**Comment by TomcatBB** [comment]
you are right, but the receiver, in the normal way, will use the KOSIT Validator to verify if the Document is valid, and this marks the document to reject, when the receiver still demands a 1.2 Version XRechnung and we send him a Version 2.0. Even if its technically compatible.

**Comment by stephanstapel** [comment]
ok, I see. So rather go for a DateTime.Today check?

**Comment by TomcatBB** [comment]
yes but i would let the user of the api decide which version he wants to use. Because i am not sure if every receiver is able to switch direct on the 01.01.2020 to the new version. We have a pending question to the Deutsche Bahn, where we exactly asking this, but we are still have no answer.

**Comment by stephanstapel** [comment]
Ok, but this will be two breaking changes. One for now and one for the time after January 1st. That's imho not worth it. The other option would be to let the user decide based on the Profile.
I.e. I could implement a Profile named XRechnung1 for legacy invoices and leave XRechnung for the current version.

Makes sense?

**Comment by TomcatBB** [comment]
i would the user decide on the Profile, therefore for better understanding we could have a Profile Called XRechnung1_2 and one called XRechnung2_0 ?

**Comment by Alpini1980** [comment]
> The other option would be to let the user decide based on the Profile.

I think this would be the best solution. I had some correspondence with the KOSIT last week regarding an issue which is solved in "Extension XRechnung 2.0" (which is officially valid from 01.01.2021) and they said: 

"It's possible to use XRechnung 2.0 even now if you make a bilateral agreement with the invoice receiver."

So the XRechnung version is independent from the official start date.

Regards, Stefan

**Comment by stephanstapel** [comment]
What a chaos, thanks for the information!

**Comment by stephanstapel** [comment]
Please see the updated documentation:

https://github.com/stephanstapel/ZUGFeRD-csharp
