### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by aschliewert** [stephanstapel/ZUGFeRD-csharp#114]
Hi.

Is it possible that a new version will be released which also contains the AdditionalReferencedDocuments? 

Thanks in advance

**Comment by stephanstapel** [comment]
Hi,
The new version will contain everything which is in the master branch. As I am not quite sure - does this answer your question?
Cheers,
Stephan

**Comment by aschliewert** [comment]
Rather, I wanted to find out whether you could possibly create a new release with the current changes?

**Comment by stephanstapel** [comment]
Ok, that is a different question. Soon, right after closing #108 and #113.

**Comment by aschliewert** [comment]
OK thank you!
