### ISSUE TITLE
InvoiceReferencedDocument InvoiceDescriptor21Reader wrong XPath?

### ISSUE THREAD

**Issue by Alpini1980** [stephanstapel/ZUGFeRD-csharp#115]
Hello,

in InvoiceDescriptor21Reader (lines 282/283) there is the following code:

```
ID = _nodeAsString(doc.DocumentElement, "//ram:InvoiceReferencedDocument/ram:IssuerAssignedID", nsmgr),
IssueDateTime = _nodeAsDateTime(doc.DocumentElement, "//ram:InvoiceReferencedDocument/ram:FormattedIssueDateTime", nsmgr)
```
I am not sure and did not do any testing but think it's using the wrong XPath. Isn't 

"//ram:ApplicableHeaderTradeSettlement/" is missing in the XPath of both lines? So the code would then be:

```
ID = _nodeAsString(doc.DocumentElement, "//ram:ApplicableHeaderTradeSettlement/ram:InvoiceReferencedDocument/ram:IssuerAssignedID", nsmgr),
IssueDateTime = _nodeAsDateTime(doc.DocumentElement, "//ram:ApplicableHeaderTradeSettlement/ram:InvoiceReferencedDocument/ram:FormattedIssueDateTime", nsmgr)
```
For me it isn't urgent as I don't need the reader at the moment.

Regards, Stefan

**Comment by stephanstapel** [comment]
Hi,

yes and no. // means that XPath will find any occurrence from the current node no matter where. So the code is working, there's no bug.
But it's probably better to be more precise and let it alone be for readability.
