### ISSUE TITLE
MimeTypeWrapper.cs wrong extension for Excel files

### ISSUE THREAD

**Issue by Alpini1980** [stephanstapel/ZUGFeRD-csharp#116]
Hello Stephan,

there's a very small typo in the MimeTypeWrapper.cs in line no. 40:

the file extension is called ".xslx" but should be ".xlsx" :-)

Regards, Stefan

**Comment by stephanstapel** [comment]
omg, what a shame!
I guess that's the price of night time coding :)

**Comment by Alpini1980** [comment]
Thanks Stephan!
