### ISSUE TITLE
DefinedTradeContact not always allowed in _writeOptionalContact()-method for XRechnung-Profiles

### ISSUE THREAD

**Issue by Alpini1980** [stephanstapel/ZUGFeRD-csharp#121]
Hello Stephan,

I'am really sorry having to discuss another small issue:

In the _writeOptionalParty()-Method in "InvoiceDescriptor21Writer.cs" the "DefinedTradeContact" is written for all types of "parties" and XRechnung-profiles. But it isn't allowed for all types of parties. In the "SellerTradeparty" it is allowed but for example in the "ShipToTradeParty" (and some other) it isn't allowed for XRechnung profiles. If the contact==null then a new empty contact is created but I did not find any party where the contact is mandatory. 

So I wonder why this empty contact is beeing created in the _writeOptionalParty()-Method? If this new contact creation isn't needed at this place it may be also the solution to supress it for the not allowed XRechnung parties by passing an empty contact to the _writeOptionalParty()-Method.

So when I remove lines 1067-1070 from _writeOptionalParty()-Method it leads to a fully valid XRechnung.xml when not passing a contact where it isn't needed:
`
else if ( ((profile & Profile.XRechnung) == Profile.XRechnung) || ((profile & Profile.XRechnung1) == Profile.XRechnung1) )
{
    _writeOptionalContact(writer, "ram:DefinedTradeContact", new Contact(), Profile.XRechnung1 | Profile.XRechnung);
}
`

The Kosit-Validator is just outputting a warning when a contact has been found in a party where it isn't allowed so it's absolutely not urgent.

//Edit: I found out in XRechnung documentation that only the SELLER CONTACT is mandatory but not the BUYER CONTACT. That may be the reason for the creation of the empty contacts? In the ZUGFeRD documentation both contacts (BG-6 and BG-9) are not mandatory, maybe a failure in the documentation or it's because these are not mandatory for the ZUGFeRD profiles :-)

Regards, Stefan

**Comment by stephanstapel** [comment]
There was a reason for writing the empty contact because it otherwise didn't validate by the time it was implemented.

I'm a bit short on time currently. Can you do some testing that empty contacts really aren't necessary for the KOSiT validator?
We can then remove this else statement and leave the rest as-is.

**Comment by Alpini1980** [comment]
Hello Stephan,

no problem and as I wrote: This Issue only raises a warning and the invoices are still accepted so no rush needed.

In the meantime I'll do some more testing. At moment I have commented out the lines above and it already worked with some test-invoices without any problems. But I think the code in the InvoiceDescriptor21Writer.cs can still be improved to make it a little bit more foolproof when generating XRechnung invoices and not running into validation problems.

Is there a validation tool for ZUGFeRD invoices available like the KOSIT validation tool for XRechnung invoices?

Regards, Stefan

**Comment by stephanstapel** [comment]
cool thanks.

I used this one so far:
https://www.din-zugferd-validation.org/

however I don't know if it works with > 1.x

This one also seems to be ok:
https://www.zugferd-community.net/de/open_community/validation

**Comment by Alpini1980** [comment]
Hello Stephan,

because it's really annoying to search in the XRechnung and ZUGFeRD manuas for this topic and both manuals are needed at the same time I made this small overview about the mapping of all ZUGFeRD "parties" in XRechnung and if the BG's are allowed, mandatory or optional. If you or anyone else notices failures in my overview then please comment here.

"Code OK" means that the _writeOptionalParty() is allready called correctly for XRechnung profiles or not in my opinion. So only the ShipToTradeParty was wrong written which has been already corrected. If all "to do's" could be solved it would make this small part of the whole structure XRechnung-Validation save I think. But the question is what's your philosophy behind your lib regarding allowed/mandatory/optional fields? Let the lib do the logic or let it do the programmer? I think not everything can be checked/prevented by the lib to make it validation-save. The removal of the "else-if" above would give the programmer the control about when the DefinedTradeContact is written and when not and there's still the validation tool of the KOSIT which is (once it it running) doing a good job. And for the ZUGFeRD there are the above mentioned validation sites too.

![DefinedTradeContact](https://user-images.githubusercontent.com/73544666/100471980-aa6a5b00-30db-11eb-8bc1-8b528efd2282.png)

Of course there are much more entries in the "parties" other than the DefinedTradeContact and the PostalTradeAdress which I have in my small overview.

Regards, Stefan

**Comment by stephanstapel** [comment]
That looks really great, thanks!
Could you upload the Excel sheet or transform it into markdown so we can collaboratively edit it (feel free to create a .md page in the repository!). I'd like to add some columns to mark what needs to implement exactly for what profile. Otherwise I fear to still get lost in the table :)

**Comment by stephanstapel** [comment]
@Alpini1980 : could you provide the Excel sheet?
