### ISSUE TITLE
Reverse Charge working?

### ISSUE THREAD

**Issue by hypers1** [stephanstapel/ZUGFeRD-csharp#122]
Does reverse charge (TAX Catory Code AE) work?
I cannot validate documents with AE:

_[BR-AE-02]-An  Invoice that contains an Invoice line (BG-25) where the Invoiced item  VAT category code (BT-151) is “Reverse charge” shall contain the Seller  VAT Identifier (BT-31), the Seller Tax registration identifier (BT-32)  and/or the Seller tax representative VAT identifier (BT-63) and the  Buyer VAT identifier (BT-48) and/or the Buyer legal

[Test.zip](https://github.com/stephanstapel/ZUGFeRD-csharp/files/5610563/Test.zip)

 registration  identifier (BT-47).

[BR-AE-10]-A VAT Breakdown (BG-23) with VAT Category code (BT-118) "Reverse charge" shall have a VAT exemption reason code (BT-121), meaning "Reverse charge" or the VAT exemption reason text (BT-120) "Reverse charge" (or the equivalent standard text in another language).

[BR-AE-04]-An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is “Reverse charge” shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48) and/or the Buyer legal registration identifier (BT-47)._

I am a little bit confused, because all required fields are filled. What could be the reason for this?

**Comment by hypers1** [comment]
Hier ist nochmal der Inhalt der XML-Datei. Meiner Meinung nach ist die Datei korrekt (auch wenn man der Doku glauben darf):

`<?xml version="1.0" encoding="utf-8"?>
<rsm:CrossIndustryInvoice xmlns:a="urn:un:unece:uncefact:data:standard:QualifiedDataType:100" xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:qdt="urn:un:unece:uncefact:data:standard:QualifiedDataType:100" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100">
  <rsm:ExchangedDocumentContext>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>
  <rsm:ExchangedDocument>
    <ram:ID>18383</ram:ID>
    <ram:TypeCode>380</ram:TypeCode>
    <ram:IssueDateTime>
      <udt:DateTimeString format="102">20201127</udt:DateTimeString>
    </ram:IssueDateTime>
  </rsm:ExchangedDocument>
  <rsm:SupplyChainTradeTransaction>
    <ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>1</ram:LineID>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:SellerAssignedID>1</ram:SellerAssignedID>
        <ram:Name>HSW-Tür Instandsetzung</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:GrossPriceProductTradePrice>
          <ram:ChargeAmount>52.00</ram:ChargeAmount>
        </ram:GrossPriceProductTradePrice>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>52.00</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="HUR">4.00</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:ExemptionReason>Umkehrung der Steuerschuldnerschaft</ram:ExemptionReason>
          <ram:CategoryCode>AE</ram:CategoryCode>
          <ram:RateApplicablePercent>0.00</ram:RateApplicablePercent>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>208.00</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLineItem>
    <ram:ApplicableHeaderTradeAgreement>
      <ram:BuyerReference>123456789</ram:BuyerReference>
      <ram:SellerTradeParty>
        <ram:ID>116078</ram:ID>
        <ram:Name>Mustermann GmbH</ram:Name>
        <ram:DefinedTradeContact>
          <ram:PersonName>Wolfgang Muster</ram:PersonName>
          <ram:TelephoneUniversalCommunication>
            <ram:CompleteNumber>069-12335</ram:CompleteNumber>
          </ram:TelephoneUniversalCommunication>
          <ram:EmailURIUniversalCommunication>
            <ram:URIID>mail@muster.de</ram:URIID>
          </ram:EmailURIUniversalCommunication>
        </ram:DefinedTradeContact>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>60388</ram:PostcodeCode>
          <ram:LineOne>Musterstrasse 4</ram:LineOne>
          <ram:CityName>Frankfurt am Main</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">04523149435</ram:ID>
        </ram:SpecifiedTaxRegistration>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">DE152338654</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:SellerTradeParty>
      <ram:BuyerTradeParty>
        <ram:ID>10099</ram:ID>
        <ram:Name>DB Station&amp;Service AG RB Mitte</ram:Name>
        <ram:DefinedTradeContact>
          <ram:PersonName>Klaus Koffer</ram:PersonName>
        </ram:DefinedTradeContact>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>10115</ram:PostcodeCode>
          <ram:LineOne>Elisabeth-Schwarzhaupt-Platz 1</ram:LineOne>
          <ram:CityName>Berlin</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">DE152138634</ram:ID>
        </ram:SpecifiedTaxRegistration>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">04523249415</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:BuyerTradeParty>
      <ram:BuyerOrderReferencedDocument>
        <ram:IssuerAssignedID />
      </ram:BuyerOrderReferencedDocument>
    </ram:ApplicableHeaderTradeAgreement>
    <ram:ApplicableHeaderTradeDelivery>
      <ram:ActualDeliverySupplyChainEvent>
        <ram:OccurrenceDateTime>
          <udt:DateTimeString format="102">20201123</udt:DateTimeString>
        </ram:OccurrenceDateTime>
      </ram:ActualDeliverySupplyChainEvent>
      <ram:DeliveryNoteReferencedDocument>
        <ram:IssuerAssignedID>22138</ram:IssuerAssignedID>
      </ram:DeliveryNoteReferencedDocument>
    </ram:ApplicableHeaderTradeDelivery>
    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
      <ram:SpecifiedTradeSettlementPaymentMeans>
        <ram:TypeCode>1</ram:TypeCode>
        <ram:Information>Rechnung</ram:Information>
        <ram:PayeePartyCreditorFinancialAccount>
          <ram:IBANID>DE54500800000192632400</ram:IBANID>
          <ram:AccountName>Mustermann GmbH</ram:AccountName>
        </ram:PayeePartyCreditorFinancialAccount>
        <ram:PayeeSpecifiedCreditorFinancialInstitution>
          <ram:BICID>DRESDEFFXXX</ram:BICID>
        </ram:PayeeSpecifiedCreditorFinancialInstitution>
      </ram:SpecifiedTradeSettlementPaymentMeans>
      <ram:ApplicableTradeTax>
        <ram:CalculatedAmount>0.00</ram:CalculatedAmount>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:BasisAmount>233.00</ram:BasisAmount>
        <ram:CategoryCode>AE</ram:CategoryCode>
        <ram:RateApplicablePercent>0.00</ram:RateApplicablePercent>
      </ram:ApplicableTradeTax>
      <ram:SpecifiedTradeAllowanceCharge>
        <ram:ChargeIndicator>
          <udt:Indicator>true</udt:Indicator>
        </ram:ChargeIndicator>
        <ram:BasisAmount>0.00</ram:BasisAmount>
        <ram:ActualAmount>25.00</ram:ActualAmount>
        <ram:Reason>Lieferpauschale</ram:Reason>
        <ram:CategoryTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:CategoryCode>AE</ram:CategoryCode>
          <ram:RateApplicablePercent>0.00</ram:RateApplicablePercent>
        </ram:CategoryTradeTax>
      </ram:SpecifiedTradeAllowanceCharge>
      <ram:SpecifiedTradePaymentTerms>
        <ram:Description>10 Tage 3% Skonto, 30 Tage netto</ram:Description>
        <ram:DueDateDateTime>
          <udt:DateTimeString format="102">20201227</udt:DateTimeString>
        </ram:DueDateDateTime>
      </ram:SpecifiedTradePaymentTerms>
      <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
        <ram:LineTotalAmount>208.00</ram:LineTotalAmount>
        <ram:ChargeTotalAmount>25.00</ram:ChargeTotalAmount>
        <ram:AllowanceTotalAmount>0.00</ram:AllowanceTotalAmount>
        <ram:TaxBasisTotalAmount>233.00</ram:TaxBasisTotalAmount>
        <ram:TaxTotalAmount currencyID="EUR">0.00</ram:TaxTotalAmount>
        <ram:GrandTotalAmount>233.00</ram:GrandTotalAmount>
        <ram:DuePayableAmount>233.00</ram:DuePayableAmount>
      </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
    </ram:ApplicableHeaderTradeSettlement>
  </rsm:SupplyChainTradeTransaction>
</rsm:CrossIndustryInvoice>`

**Comment by stephanstapel** [comment]
My approach usually is to step through the source code of the validation which is in this case (https://docs.peppol.eu/poacc/billing/3.0/rules/BR-AE-02/):

`
(exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'AE'][cac:TaxScheme/normalize-space(upper-case(cbc:ID))='VAT']) and (exists(//cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID) or exists(//cac:TaxRepresentativeParty/cac:PartyTaxScheme[cac:TaxScheme/(normalize-space(upper-case(cbc:ID)) = 'VAT')]/cbc:CompanyID)) and (exists(//cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/(normalize-space(upper-case(cbc:ID)) = 'VAT')]/cbc:CompanyID) or exists(//cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyID))) or not(exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'AE'][cac:TaxScheme/normalize-space(upper-case(cbc:ID))='VAT']))
`

**Comment by hypers1** [comment]
I am not sure, wether it is a bug:
When reverse charge is used, some validators (i. e. https://www.epoconsulting.com/erechnung/xrechnung-validator) don't accept the file when the sales taxid (Umsatzsteuer-ID) is marked with the schemeID "VA".

**This works not:**

```
                                <ram:SpecifiedTaxRegistration>
                                        <ram:ID schemeID="VA">DE201092120</ram:ID>
                                </ram:SpecifiedTaxRegistration>
```

**This works:**


```
                                <ram:SpecifiedTaxRegistration>
                                        <ram:ID schemeID="VAT">DE201092120</ram:ID>
                                </ram:SpecifiedTaxRegistration>
```

**Comment by landrix** [comment]
VA is right

**Comment by hypers1** [comment]
Yes, I think the same, after I studied the documentation. Are some validators working wrong? 
I have some files with this problem, that the Deutsche Bahn doesn't accept, because of the VA/VAT-Problem.

**Comment by stephanstapel** [comment]
there is a similar discussion here:
https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/57

There are some old changes for BR-AE-04 here (referenced in the issue):
https://github.com/ConnectingEurope/eInvoicing-EN16931/commit/68ba586378fb718ebfd743b01912c9788feb33ea
i.e. for (pure) EN16391, the validation is correct.
