### ISSUE TITLE
Problem with AssociatedDocument

### ISSUE THREAD

**Issue by ThomasSchwab123** [stephanstapel/ZUGFeRD-csharp#123]
Hi,
in version 4.0 I can create an instance of AssociatedDocument
AssociatedDocument associatedDocument = new AssociatedDocument();                

with version 5.0 it is not possible. Is there a bug?

best regards
Thomas

**Comment by stephanstapel** [comment]
Hi,

we changed the visibility of the constructor to internal. The reason behind this was that the lines can now be either given a bespoke line id or the library can automatically calculate the next valid one. In order to avoid double line ids, you now need to rely on the library to generated the associated document with either 

`InvoiceDescriptor.AddTradeLineCommentItem()`

 or 

`InvoiceDescriptor.AddTradeLineItem()`

Does this deliver what you need or did we forget a use case when we modified the constructor to internal?

Cheers,
Stephan

**Comment by ThomasSchwab123** [comment]
Hi Stephan,

the problem is, that I must transfer the data with a JSON string. When I want to Deserializize the string and convert it to the object, then I get the following error:
Unable to find a constructor to use for type s2industries.ZUGFeRD.AssociatedDocument. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'AssociatedDocument.LineID', line 1, position 91."}

Here is my code. When I want to make this, then I need the constructor.

        public void TestConvert()
        {
            string json;
           json = "{'ActualDeliveryDate':'','AdditionalReferencedDocuments':[],'AssociatedDocument':{'LineID':'0','Notes':[]}}";
            TradeLineItem TLI = Newtonsoft.Json.JsonConvert.DeserializeObject<TradeLineItem>(json);                

        }

Can you give me the constructor back?

Best regards
Thomas

**Comment by stephanstapel** [comment]
Whoa. We did this to prohibit manual creation which is what you now need. I guess a custom converter would be the way to go:

https://stackoverflow.com/questions/40439290/custom-deserialization-using-json-net

**Comment by ThomasSchwab123** [comment]
Hi Stephan,

unfortunately I don't can change this in .net, because creating the json is not a .net programm code. But I can change the other program, that it is not creating and transfering to .net.

Thanks

Best regards
Thomas

**Comment by stephanstapel** [comment]
Sounds good. So what approach will you follow? Will you implement a custom JsonConverter for deserialization?

**Comment by ThomasSchwab123** [comment]
Hi,
I change the serialisation in the other program, that I don't have the "AssociatedDocument" in my json.
Then the deserialization is working

Old json string
json = "{'ActualDeliveryDate':'','AdditionalReferencedDocuments':[],'AssociatedDocument':{'LineID':'0','Notes':[]}}";

New json string
json = "{'ActualDeliveryDate':'','AdditionalReferencedDocuments':[]}";

Best regards
Thomas
