### ISSUE TITLE
Export to XRechnung uses wrong encoding.

### ISSUE THREAD

**Issue by BarthauerSoftwareGmbH** [stephanstapel/ZUGFeRD-csharp#126]
Hello,

I found another small issue.

After temporarily fixing my other issue by omitting the TradeLineComments for now, we got the complain from our customer that the XRechnung is encoded as "UTF-8 BOM" instead of "UTF-8" and because of that can't be processed by them.

The Specification also states in Part 1, Chapter 5.1 that the XML file needs to be encoded as "UTF-8". (Although atleast for me it wouldnt be clear if they mean "UTF-8" only or the entirety of UTF-8 which would include UTF-8 BOM)

Johannes

**Comment by stephanstapel** [comment]
I haven't come across this so far.
My understanding is the same as yours: UTF-8 is required and the standard does not mention anything on the flavor (googling "xrechnung utf-8 bom" doesn't lead to any valuable information).

As changing this would cause very much change for the users, would it be a viable option to write the XRechnung into to stream and write this into a UTF-8 file then?

**Comment by Alpini1980** [comment]
I think the customer isn't using a good expression for the problem. The generated XML's have a three byte UTF-8 BOM at the beginning of the file:

![Screenshot 2020-12-09 181119](https://user-images.githubusercontent.com/73544666/101662822-42583500-3a4a-11eb-8c26-ba97d930a2ec.png)

It's good decribed here: https://de.wikipedia.org/wiki/Byte_Order_Mark

"...ein BOM am String- oder Dateianfang ist erlaubt, um die Verwendung von UTF-8 als Kodierung zu kennzeichnen."

**Comment by stephanstapel** [comment]
@BarthauerSoftwareGmbH : does the proposed solution work for you? If so, can we close the issue?
