### ISSUE TITLE
ContractReferencedDocument is not properly closed

### ISSUE THREAD

**Issue by ihinz** [stephanstapel/ZUGFeRD-csharp#127]
When  I tried the current NuGet-package (Version 5.0.0) for generating an XRechnung I noticed a SpecifiedProcuringProject-Element
inside a ContractReferencedDocument-Element in my XML-Structure. From what I know this is incorrect.
Looking at the code in "InvoiceDescriptor21Writer.cs" I found this part, which I think is missing a "Writer.WriteEndElement();" before the last closing bracket (lines 472 & 473), resulting in the problem.

![grafik](https://user-images.githubusercontent.com/75789860/101773275-ded31380-3aec-11eb-8f43-72354eae2a5e.png)

**Comment by stephanstapel** [comment]
Hi @ihinz , 
I guess that broke by a merge (would be a typical scenario). I'll fix it tonight and add a test to the test project. As I'm not planning to release a bugfix release in 2020, would it be a viable option to use the github version first?

**Comment by ihinz** [comment]
Thanks for the quick reply. I do not need a release right now. We were still using a not 100% up-todate version from here. That one just had a minor issue that I fixed locally, which your current version didn't have anymore. Things should be fine for now, it just means we can't switch to the NuGet-package to have an easier way of updating for the moment. I just wanted to make sure you were aware of the issue.
