### ISSUE TITLE
Leitweg-ID

### ISSUE THREAD

**Issue by ThomasSchwab123** [stephanstapel/ZUGFeRD-csharp#128]
Hi Stephan,

I have to fill the "Leitweg-ID"
https://de.wikipedia.org/wiki/Leitweg-ID
"Buyer Reference" (Attribut BT-10 from EN 16931-1) 
https://ecosio.com/de/blog/was-ist-eine-leitweg-id/
How can I fill, or how can I find this field?
Is there a documentation where all the fields are explained?

Best regards
Thomas

**Comment by stephanstapel** [comment]
Please use the field ReferenceOrderNo

**Comment by blockberd** [comment]
That is not recognized as the Leitweg-ID by https://xrechnung-bdr.de. Which field are we suppose to use?
