### ISSUE TITLE
Invalid Content DateTimeString

### ISSUE THREAD

**Issue by lingotwingo** [stephanstapel/ZUGFeRD-csharp#129]
Hi, 

while validating the XML file this error comes up:
Invalid content was found starting with element '{"urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100":DateTimeString}'. One of '{"urn:un:unece:uncefact:data:standard:QualifiedDataType:100":DateTimeString}' is expected.

What does this error mean?

Thanks for the help.

**Comment by stephanstapel** [comment]
Hi,

which validator are you using, which version of ZUGFeRD/ XRechnung and could you post the example file?

Cheers!

**Comment by lingotwingo** [comment]
Hello Stephan,


I am mainly using zugferd-community.net. 



> <rsm:CrossIndustryInvoice xmlns:a="urn:un:unece:uncefact:data:standard:QualifiedDataType:100" xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:qdt="urn:un:unece:uncefact:data:standard:QualifiedDataType:10" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100"><rsm:ExchangedDocumentContext><ram:TestIndicator><udt:Indicator>false</udt:Indicator></ram:TestIndicator><ram:GuidelineSpecifiedDocumentContextParameter><ram:ID>urn:cen.eu:en16931:2017#conformant#urn:zugferd.de:2p0:extended</ram:ID></ram:GuidelineSpecifiedDocumentContextParameter></rsm:ExchangedDocumentContext><rsm:ExchangedDocument><ram:ID>202089402845</ram:ID><ram:Name>RECHNUNG</ram:Name><ram:TypeCode>380</ram:TypeCode><ram:IssueDateTime><udt:DateTimeString format="102">20201215</udt:DateTimeString></ram:IssueDateTime></rsm:ExchangedDocument><rsm:SupplyChainTradeTransaction><ram:IncludedSupplyChainTradeLineItem><ram:AssociatedDocumentLineDocument><ram:LineID>1</ram:LineID></ram:AssociatedDocumentLineDocument><ram:SpecifiedTradeProduct><ram:Name>Teleskopkran (mind. 3 h)</ram:Name></ram:SpecifiedTradeProduct><ram:SpecifiedLineTradeAgreement><ram:GrossPriceProductTradePrice><ram:ChargeAmount currencyID="EUR">250.0000</ram:ChargeAmount><ram:BasisQuantity unitCode="HUR">3.0000</ram:BasisQuantity></ram:GrossPriceProductTradePrice><ram:NetPriceProductTradePrice><ram:ChargeAmount currencyID="EUR">250.0000</ram:ChargeAmount><ram:BasisQuantity unitCode="HUR">3.0000</ram:BasisQuantity></ram:NetPriceProductTradePrice></ram:SpecifiedLineTradeAgreement><ram:SpecifiedLineTradeDelivery><ram:BilledQuantity unitCode="HUR">3.0000</ram:BilledQuantity></ram:SpecifiedLineTradeDelivery><ram:SpecifiedLineTradeSettlement><ram:ApplicableTradeTax><ram:TypeCode>VAT</ram:TypeCode><ram:CategoryCode>S</ram:CategoryCode><ram:RateApplicablePercent>16.00</ram:RateApplicablePercent></ram:ApplicableTradeTax><ram:SpecifiedTradeSettlementLineMonetarySummation><ram:LineTotalAmount currencyID="EUR">750.00</ram:LineTotalAmount></ram:SpecifiedTradeSettlementLineMonetarySummation></ram:SpecifiedLineTradeSettlement></ram:IncludedSupplyChainTradeLineItem><ram:IncludedSupplyChainTradeLineItem><ram:AssociatedDocumentLineDocument><ram:LineID>2</ram:LineID></ram:AssociatedDocumentLineDocument><ram:SpecifiedTradeProduct><ram:Name>4xA-Pauschale
4xA-Pauschale incl. einmaliger An-/Abfahrt, einmaligem Auf-/Abbau, Ballasttransport, Genehmigung, 1 x firmeneigene Begleitung u. Maut - excl. Polizei u. VLM (zusätzl. BF3, BF4, Beifahrer, Streckenänderungen o. ä.).

> Geeignete Rundschlingen zum Anschlagen werden bauseits gestellt.</ram:Name></ram:SpecifiedTradeProduct><ram:SpecifiedLineTradeAgreement><ram:GrossPriceProductTradePrice><ram:ChargeAmount currencyID="EUR">0.0000</ram:ChargeAmount><ram:BasisQuantity unitCode="LS">0.0000</ram:BasisQuantity></ram:GrossPriceProductTradePrice><ram:NetPriceProductTradePrice><ram:ChargeAmount currencyID="EUR">1990.0000</ram:ChargeAmount><ram:BasisQuantity unitCode="LS">0.0000</ram:BasisQuantity></ram:NetPriceProductTradePrice></ram:SpecifiedLineTradeAgreement><ram:SpecifiedLineTradeDelivery><ram:BilledQuantity unitCode="LS">1.0000</ram:BilledQuantity></ram:SpecifiedLineTradeDelivery><ram:SpecifiedLineTradeSettlement><ram:ApplicableTradeTax><ram:TypeCode>VAT</ram:TypeCode><ram:CategoryCode>S</ram:CategoryCode><ram:RateApplicablePercent>16.00</ram:RateApplicablePercent></ram:ApplicableTradeTax><ram:SpecifiedTradeSettlementLineMonetarySummation><ram:LineTotalAmount currencyID="EUR">1990.00</ram:LineTotalAmount></ram:SpecifiedTradeSettlementLineMonetarySummation></ram:SpecifiedLineTradeSettlement></ram:IncludedSupplyChainTradeLineItem><ram:ApplicableHeaderTradeAgreement><ram:SellerTradeParty><ram:ID>89</ram:ID><ram:Name>RIEGER &amp; MOSER GmbH &amp; Co. KG</ram:Name><ram:DefinedTradeContact><ram:PersonName>Michael Arb</ram:PersonName><ram:DepartmentName>RIEGER &amp; MOSER</ram:DepartmentName><ram:TelephoneUniversalCommunication><ram:CompleteNumber>0731-88033614</ram:CompleteNumber></ram:TelephoneUniversalCommunication><ram:FaxUniversalCommunication><ram:CompleteNumber>0731-45540</ram:CompleteNumber></ram:FaxUniversalCommunication><ram:EmailURIUniversalCommunication><ram:URIID>M.Arb@rieger-moser.de</ram:URIID></ram:EmailURIUniversalCommunication></ram:DefinedTradeContact><ram:PostalTradeAddress><ram:PostcodeCode>89079</ram:PostcodeCode><ram:LineOne>Hans-Lorenser-Strasse 26</ram:LineOne><ram:CityName>Ulm</ram:CityName><ram:CountryID>DE</ram:CountryID></ram:PostalTradeAddress><ram:SpecifiedTaxRegistration><ram:ID schemeID="VA">DE 147047973</ram:ID></ram:SpecifiedTaxRegistration></ram:SellerTradeParty><ram:BuyerTradeParty><ram:ID>4808</ram:ID><ram:Name>HARDER logistics GmbH &amp; Co. KG </ram:Name><ram:PostalTradeAddress><ram:PostcodeCode>89231</ram:PostcodeCode><ram:LineOne>Max-Eyth-Str. 39</ram:LineOne><ram:CityName>Neu-Ulm</ram:CityName><ram:CountryID>DE</ram:CountryID></ram:PostalTradeAddress><ram:SpecifiedTaxRegistration><ram:ID schemeID="VA">DE813802671</ram:ID></ram:SpecifiedTaxRegistration></ram:BuyerTradeParty><ram:BuyerOrderReferencedDocument><ram:FormattedIssueDateTime><udt:DateTimeString>2020-11-09T00:00:00</udt:DateTimeString></ram:FormattedIssueDateTime><ram:IssuerAssignedID /></ram:BuyerOrderReferencedDocument></ram:ApplicableHeaderTradeAgreement><ram:ApplicableHeaderTradeDelivery><ram:ActualDeliverySupplyChainEvent><ram:OccurrenceDateTime><udt:DateTimeString format="102">20201214</udt:DateTimeString></ram:OccurrenceDateTime></ram:ActualDeliverySupplyChainEvent></ram:ApplicableHeaderTradeDelivery><ram:ApplicableHeaderTradeSettlement><ram:InvoiceeTradeParty><ram:ID>4808</ram:ID><ram:Name>HARDER logistics GmbH &amp; Co. KG </ram:Name><ram:PostalTradeAddress><ram:PostcodeCode>89231</ram:PostcodeCode><ram:LineOne>Max-Eyth-Str. 39</ram:LineOne><ram:CityName>Neu-Ulm</ram:CityName><ram:CountryID>DE</ram:CountryID></ram:PostalTradeAddress></ram:InvoiceeTradeParty><ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode><ram:SpecifiedTradeSettlementPaymentMeans><ram:TypeCode>58</ram:TypeCode><ram:Information /></ram:SpecifiedTradeSettlementPaymentMeans><ram:ApplicableTradeTax><ram:CalculatedAmount currencyID="EUR">439.20</ram:CalculatedAmount><ram:TypeCode>VAT</ram:TypeCode><ram:BasisAmount currencyID="EUR">2745.00</ram:BasisAmount><ram:CategoryCode>S</ram:CategoryCode><ram:RateApplicablePercent>16.00</ram:RateApplicablePercent></ram:ApplicableTradeTax><ram:SpecifiedTradePaymentTerms><ram:Description>rein netto sofort</ram:Description><ram:DueDateDateTime><udt:DateTimeString format="102">20201215</udt:DateTimeString></ram:DueDateDateTime></ram:SpecifiedTradePaymentTerms><ram:SpecifiedTradeSettlementHeaderMonetarySummation><ram:LineTotalAmount currencyID="EUR">2745.00</ram:LineTotalAmount><ram:ChargeTotalAmount currencyID="EUR">0.00</ram:ChargeTotalAmount><ram:AllowanceTotalAmount currencyID="EUR">0.00</ram:AllowanceTotalAmount><ram:TaxBasisTotalAmount currencyID="EUR">2745.00</ram:TaxBasisTotalAmount><ram:TaxTotalAmount currencyID="EUR">439.20</ram:TaxTotalAmount><ram:GrandTotalAmount currencyID="EUR">3184.20</ram:GrandTotalAmount><ram:TotalPrepaidAmount currencyID="EUR">0.00</ram:TotalPrepaidAmount><ram:DuePayableAmount currencyID="EUR">3184.20</ram:DuePayableAmount></ram:SpecifiedTradeSettlementHeaderMonetarySummation></ram:ApplicableHeaderTradeSettlement></rsm:SupplyChainTradeTransaction></rsm:CrossIndustryInvoice>






And the other one I am using is din-zugferd-validation.org where another error is coming up: 

no declaration found for element 'rsm:CrossIndustryInvoice'.

**Comment by stephanstapel** [comment]
Thanks.
I put little effort in maintaining ZUGFeRD 2.0 writer. Is it possible that you step up to version 2.1? The bugs you are mentioning are not appearing there.
