### ISSUE TITLE
SEPA-Lastschrift mit Angabe Mandatsreferenz und GläubigerID

### ISSUE THREAD

**Issue by drocx** [stephanstapel/ZUGFeRD-csharp#13]
Hallo,

erstmal vielen Dank für das Einbauen meiner Code Ergänzungen.

Mit ist gerade noch aufgefallen, dass der Writer noch keine SEPA Lastschrift mit Prenotification kann.
Könntest du das vielleicht noch zeitnah einbauen?
Alternativ würde ich mich daran versuchen.

**Beispiel 37 aus der ZUGFeRD Formatbeschreibung Seite 86/131:**
```xml
<ram:ApplicableSupplyChainTradeSettlement> 
... 
 <ram:PaymentReference>Rechnung Nummer 4711/2014</ram:PaymentReference> 
 <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode> 
   
 <ram:SpecifiedTradeSettlementPaymentMeans> 
  <ram:TypeCode>49</ram:TypeCode> 
  <ram:Information>Betrag wird per SEPA-Lastschrift eingezogen</ram:Information> 
  <ram:ID schemeAgencyID="DE98ZZZ09999999999">REF A-123</ram:ID> 
  <ram:PayerPartyDebtorFinancialAccount> 
   <ram:IBANID>DE21860000000086001055</ram:IBANID> 
   <ram:AccountName>Bundeskasse Halle -Darlehen-</ram:AccountName> 
  </ram:PayerPartyDebtorFinancialAccount> 
  <ram:PayerSpecifiedDebtorFinancialInstitution> 
   <ram:BICID>MARKDEF1860</ram:BICID> 
   <ram:Name>Deutsche Bundesbank -Filiale Leipzig-</ram:Name> 
  </ram:PayerSpecifiedDebtorFinancialInstitution> 
 </ram:SpecifiedTradeSettlementPaymentMeans> 
...
</ram:ApplicableSupplyChainTradeSettlement> 
```

**Comment by stephanstapel** [comment]
Hallo,

mit SEPA habe ich mich in der Tat noch nicht auseinandergesetzt. Machen wir es doch dieses Mal anders herum: ich baue es ein und Du reviewst es. Was meinst Du?

**Comment by drocx** [comment]
Können wir gerne so machen.

Es müssen ja auch nur das oben angegebene XML geschrieben werden, da bei ZUGFeRD-Rechnungen wird davon ausgegangen wird, dass das Fälligkeitsdatum der Rechnung dem Fälligkeitsdatum der Lastschrift entspricht.
Andere Prenotification Arten werden nicht unterstützt.

**Comment by stephanstapel** [comment]
kann es sein, dass das Beispiel in der Doku falsch ist?
Schau mal hier aus der technischen Dokumentation:

![image](https://cloud.githubusercontent.com/assets/2912080/24880609/6044726a-1e3b-11e7-9172-fbd5397391b5.png)

dort steht, dass es den AccountName nur bei PayeePartyCreditorFinancialAccount gibt, nicht bei PayerPartyDebtorFinancialAccount. Was meinst Du?

**Comment by drocx** [comment]
Könnte sein. Sonst gibt es noch ein SEPA Confort Extended Beispiel bei der ZUGFeRD Beschreibung. In dem XML müsste man es ja nochmal nachschauen können. 
Ich persönlich würde die Felder aber nicht nutzen, da ich meist nur Iban und BIC habe. Der Name der Bank ist meist nicht vorhanden. 
Morgen kann ich aber nochmal die Doku genauer lesen. Dann bin ich wieder am Rechner.

**Comment by drocx** [comment]
Ja. Das Beispiel aus der Doku ist falsch und die technische Doku ist richtig.

```xml
<ram:ApplicableSupplyChainTradeSettlement>
	<ram:PaymentReference>2013-471102</ram:PaymentReference>
	<ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
	<ram:SpecifiedTradeSettlementPaymentMeans>
		<ram:TypeCode>49</ram:TypeCode>
		<ram:Information>SEPA-Lastschrift</ram:Information>
		<ram:ID schemeAgencyID="DE98ZZZ09999999999">REF A-123</ram:ID>
		<ram:PayerPartyDebtorFinancialAccount>
			<ram:IBANID>DE21860000000086001055</ram:IBANID>
		</ram:PayerPartyDebtorFinancialAccount>
		<ram:PayerSpecifiedDebtorFinancialInstitution>
			<ram:BICID>MARKDEF1860</ram:BICID>
			<ram:Name>Deutsche Bundesbank -Filiale Leipzig-</ram:Name>
		</ram:PayerSpecifiedDebtorFinancialInstitution>
	</ram:SpecifiedTradeSettlementPaymentMeans>
...
	<ram:SpecifiedTradePaymentTerms>
		<ram:Description>Der Betrag in Höhe von EUR 529,87 wird am 20.03.2014 von Ihrem Konto mit IBAN DE21860000000086001055
und BIC MARKDEF1860, Deutsche Bundesbank -Filiale Leipzig- per SEPA-Lastschrift eingezogen.
Mandatsreferenz: REF A-123, Gläubiger-Identifikationsnummer: DE98ZZZ09999999999</ram:Description>
		<ram:DueDateDateTime><udt:DateTimeString format="102">20140320</udt:DateTimeString></ram:DueDateDateTime>
        </ram:SpecifiedTradePaymentTerms>
...
</ram:ApplicableSupplyChainTradeSettlement>
```
[ZUGFeRD_1p0_COMFORT_SEPA_Prenotification.pdf](https://github.com/stephanstapel/ZUGFeRD-csharp/files/912269/ZUGFeRD_1p0_COMFORT_SEPA_Prenotification.pdf)

**Comment by stephanstapel** [comment]
Schau Dir mal den commit an: https://github.com/stephanstapel/ZUGFeRD-csharp/commit/d400afe760b117034ea6b901aae904f3cd31e47f

das müsste meiner Meinung nach so passen.
In nuget habe ich noch nicht aktualisiert, mache ich, sobald Du Dein ok gegeben hast!

**Comment by drocx** [comment]
Hallo,
der InvoiceDescriptor war glaube ich noch nicht ganz fertig umgesetzt. Ich habe den Code ergänzt und einen Pull Request erstellt #14.

**Comment by drocx** [comment]
Ich habe die Nuget Pakete bei mir letzte Woche aktualisiert. Läuft alles. 👍
