### ISSUE TITLE
Decimal Places in BilledQuantity

### ISSUE THREAD

**Issue by AndreasPiehlmaier** [stephanstapel/ZUGFeRD-csharp#132]
Hi,

In InvoiceDescriptor21Writer.cs the "BilledQuantity" field is limited to 2 decimal places. All other writer classes using 4 decimal places. Is there any kind of limitation in ZugFerd/XRechnung or could be extended to 4 places?

**Comment by stephanstapel** [comment]
You are probably right. According to Factur-X documentation:

![image](https://user-images.githubusercontent.com/2912080/104188922-3d581e00-541a-11eb-9b06-5b75be0fc4cc.png)

consider it done.
