### ISSUE TITLE
failing test TestXRechnung1  validation || and && wrong

### ISSUE THREAD

**Issue by bvschie** [stephanstapel/ZUGFeRD-csharp#133]
InvoiceDescriptor21Writer.cs
Save
-> was ReceivableSpecifiedTradeAccountingAccount

                if (descriptor.Profile == Profile.XRechnung1 || descriptor.Profile == Profile.XRechnung && tradeLineItem.ReceivableSpecifiedTradeAccountingAccounts.Count > 0)

-> think need to change into:

                if ((descriptor.Profile == Profile.XRechnung1 || descriptor.Profile == Profile.XRechnung) && tradeLineItem.ReceivableSpecifiedTradeAccountingAccounts.Count > 0)

**Comment by stephan-nowecor** [comment]
you are right, thanks
