### ISSUE TITLE
Support for roundings in the totals

### ISSUE THREAD

**Issue by Manuel-Lu** [stephanstapel/ZUGFeRD-csharp#134]
Hi, is there a reason that roundings in the totals is not implemented? 

InvoiceDescriptor21Writer.ch, Line 863: // ToDo: RoundingAmount  //Rundungsbetrag

Shall I make a pull request?

**Comment by stephanstapel** [comment]
The reason is just that nobody needed it so far :)
Would be great, looking forward to your pull request!
Do you please remember to add it also for 2.0 reader and writer? As far as I understand it was not present in ZUGFeRD 1, was it?

**Comment by Manuel-Lu** [comment]
Ok, pull request will come.
(It's in the EN 16931 (COMFORT) and EXTENDED-Profiles)
