### ISSUE TITLE
TaxBasisTotalAmount not written in comfort

### ISSUE THREAD

**Issue by chrisschx** [stephanstapel/ZUGFeRD-csharp#137]
code at the moment is:

_writeOptionalAmount(Writer, "ram:TaxBasisTotalAmount", this.Descriptor.TaxBasisAmount, profile: Profile.Extended); 

but TaxBasisTotalAmount is needed in comfort and so on, too.

TaxBasisTotalAmount was written in V5 but in the current (not yet released) version it does not work anymore because of profile: Profile.Extended

**Comment by stephanstapel** [comment]
Just for me:
Part of commit https://github.com/stephanstapel/ZUGFeRD-csharp/commit/1e32834161214d74cbd220b0edf0ca774fbd2056

**Comment by stephanstapel** [comment]
Thanks, can you please test the new version? Should be alright now.
