### ISSUE TITLE
SetBuyerOrderReferenceDocument should have nullable DateTime as parameter

### ISSUE THREAD

**Issue by chrisschx** [stephanstapel/ZUGFeRD-csharp#139]
SetBuyerOrderReferenceDocument should have nullable DateTime as parameter

later, the orderdate will be checked like that: if (this.Descriptor.OrderDate.HasValue) (--> #region BuyerOrderReferencedDocument)

but SetBuyerOrderReferenceDocument has no nullable DateTime

So all i can do at the moment is to initialize with a MinValue

and this way, a min value will be written to the xml document

better would be a nullable datetime as parameter

public void SetBuyerOrderReferenceDocument(string orderNo, DateTime? orderDate)

**Comment by stephanstapel** [comment]
good idea
