### ISSUE TITLE
Different tax calculations 

### ISSUE THREAD

**Issue by patrickkurras** [stephanstapel/ZUGFeRD-csharp#140]
Hi Stephan,

first of all, thanks for the awesome plugin, it works very well. But I have a little issue with the different tax calculations.

We are using the vertical tax calculation as default. However, you use the horizontal tax calculation in the TaxAmount property in the tax class. In the case of many invoice positions with non-round individual prices, the result differs by a few cents. So that ram: TaxTotalAmount and ram: CalculatedAmount do not result in the same amount.

Do you already have a solution for that?

Kind regards,
Patrick

**Comment by stephanstapel** [comment]
Hi,

you are welcome!
The classic problem of billing :)
Is this is a problem for your customers or (only) for the validator?
There is the new feature of RoundingAmount (which is currently only available via github, not yet via nuget), would that be helpful for you?

Cheers,

Stephan

**Comment by patrickkurras** [comment]
Hi Stephan,

I tried it with the "RoundingAmount" but it does not work and it's a problem for both (our customers and the validator).
 I will add a new property in the Tax class, that I'll use to fill the CalculatedAmount. If you want, I can do a PR for it.

Cheers,
Patrick
