### ISSUE TITLE
Example for XRechnung and documentation?

### ISSUE THREAD

**Issue by ThomasSchwab123** [stephanstapel/ZUGFeRD-csharp#141]
Hi,

I want to create a XRechnung.
With Version 1.0 it works. A validator said that the xml file is ok.
But with Version 2.0, I get error messages with a validator.

I have the specification from the following link:
https://www.xoev.de/xrechnung-16828
I think, this is a validator for the XRechnung Version 2.0
https://www.epoconsulting.com/erechnung/xrechnung-validator
Where can I find the required fields?
How do I know, for example, which field in the dll I have to use for the field BG-23 or BT-117? Is there a documentation? Which Profile must I use?
I think, I have to use "ZUGFeRDVersion.Version21" and "Profile.XRechnung"

Perhaps, you can give me an .Net example which creates a XRechung, that can be validated?

Best regards
Thomas

**Comment by stephanstapel** [comment]
Afaik, the epo consulting validator generates strange output sometimes.
Can you share the sample you generated invoice here (or alternatively send it via mail -> firstname.lastname@web.de)?

Concerning breaking down codes like BG-23 and BT-117 I'd like to encourage you to google them. In this case it's about VAT information that needs to be written into the invoice. I guess using AddApplicableTradeTax() would solve this.
More documentation would be desirable but please remember this is an open source project.

You can find working examples in the test project which contains various scenarios for all versions and profiles:
https://github.com/stephanstapel/ZUGFeRD-csharp/tree/master/ZUGFeRD-Test

**Comment by ThomasSchwab123** [comment]
Hi Stephan,

thanks for the tip and for the example.
Now it works.

Best regards
Thomas
