### ISSUE TITLE
Name for HeaderExchangedDocument can't be changed

### ISSUE THREAD

**Issue by chrisschx** [stephanstapel/ZUGFeRD-csharp#143]
at the moment the name is written this way:

Writer.WriteElementString("ram:Name", _translateInvoiceType(this.Descriptor.Type));

so for type 380 it's always "RECHNUNG"

but type 380 can also be a "SCHLUSSRECHNUNG"

so there should be a way to set this name manually

i did it this way at the moment:

            if(this.Descriptor.TypeName != "")
              Writer.WriteElementString("ram:Name", this.Descriptor.TypeName);
            else
              Writer.WriteElementString("ram:Name", _translateInvoiceType(this.Descriptor.Type));

**Comment by stephanstapel** [comment]
Hi,

thanks for the request. I understand the problem. However, creating setters for every field degrates the library to a type-safe xml generator which is not my original goal. The idea was to only allow to set what is absolutely necessary and leave the rest for the library.
Could you circumvent this issue by just replacing the string in the output file for now?

**Comment by chrisschx** [comment]
in my dll i changed the code like described

big companys like bmw need the exact name for each type of invoice

a normal invoice is RECHNUNG / a closing invoice is SCHLUSSRECHNUNG and so on

otherwise they don't accept the zugferd invoice

that's why i needed to change that

maybe a boolean flag would do the trick or an other enum?

if type 380 can be more than just "RECHNUNG" there should be a way to set it

**Comment by tipa** [comment]
I agree with @chrisschx that this field should be more customizable. In a code comment you wrote yourself that this is a free text field:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/9852cae7288a29e3215a4845aff0529a0ab063f7/ZUGFeRD/InvoiceDescriptor21Writer.cs#L89

If I am not completely mistaken, the ZUGFeRD format can also be user internationally so a German-only translation seems odd.

**Comment by Laser5000** [comment]
Hi, 
maybe it helps:
https://projekte.kosit.org/xrechnung/xrechnung/-/issues/44
https://service.unece.org/trade/untdid/d19b/tred/tred1001.htm

Code for "Schlussrechnung / Final construction invoice" should be 877.
