### ISSUE TITLE
TradeLineItem GrossPriceProductTradePrice and BilledQuantity wrong decimal rounding

### ISSUE THREAD

**Issue by TomcatBB** [stephanstapel/ZUGFeRD-csharp#146]
Hello since Version 6.0.0 the NetPriceProductTradePrice is correctly written with 4 digits as the decimal part but the GrossPriceProductTradePrice is still written rounded to 2 decimal digits. 

Also the BilledQuantity has a rounding bug.
So if i input 160.56789 it ouputs 160,0000. If i input 160,5678 the ouput is correct 160,5678.

**Comment by stephanstapel** [comment]
oops. Didn't mean to close this.

I could not reproduce the bug with the current code. In the first case, it outputs

![grafik](https://user-images.githubusercontent.com/2912080/114620100-89319200-9cab-11eb-83fd-3fab3a5d52e9.png)

can you still reproduce it with the current code?

**Comment by stephanstapel** [comment]
Hi @TomcatBB ,

can you please confirm if this bug is still existing?

**Comment by TomcatBB** [comment]
Hi @stephanstapel,

sorry for the late reply.  Yes the Problem with the BilledQuantity is not occuring any longer.
The GrossPriceProductTradePrice is still written with 2 digits but i am not sure if this is a bug, so for me right now its ok.

**Comment by stephanstapel** [comment]
ok cool. Sounds good. Concerning GrossPriceProductTradePrice I'd wait if this is really an issue.
