### ISSUE TITLE
BillingSpecifiedPeriod for SpecifiedLineTradeSettlement missing

### ISSUE THREAD

**Issue by patrickthoma** [stephanstapel/ZUGFeRD-csharp#147]
Hello,

we need to process invoices containing energy consumption bills. In those bills, the `BillingSpecifiedPeriod` is not listed in `ApplicableHeaderTradeSettlement`, but in `SpecifiedLineTradeSettlement`. 

Due to the fact that this library does not contain billing periods on trade line items but only at the invoice level, we can't process this bills as we need the billing period.

Therefore, I'd like to ask if it would be possible to add the billing period on trad line level?

Thank you very much,
best regads

**Comment by stephanstapel** [comment]
Hi,

is that something that you can implement and issue a PR for it?

**Comment by patrickthoma** [comment]
Hello,

thanks for your quick response - I will try it.
