### ISSUE TITLE
Plans for UBL support (XRechnung)

### ISSUE THREAD

**Issue by SupportTeamSMB** [stephanstapel/ZUGFeRD-csharp#148]
Hi, are there any plans on adding support for the UBL syntax of XRechnungen?

**Comment by stephanstapel** [comment]
Hi,
if you like, I can provide the foundation for this and be more than happy to accept your pull requests.
Looking forward to hear from you!

**Comment by stephanstapel** [comment]
Since I didn't hear anything back from you, I'll close this issue here
