### ISSUE TITLE
Missing "AppliedTradeAllowanceCharge"

### ISSUE THREAD

**Issue by festus01-kdp** [stephanstapel/ZUGFeRD-csharp#150]
Is there a timeline for the above feature?
Greetings
Klaus

**Comment by stephanstapel** [comment]
Hi,
what is missing?

**Comment by festus01-kdp** [comment]
the discount to the position line is missing
The comment of the file InvoiceDescriptor says:
"TODO Rabatt ergänzen"

**Comment by stephanstapel** [comment]
I guess this comment is old and should be deleted.
Using TradeLineItem.AddTradeAllowanceCharge() should do the trick.
