### ISSUE TITLE
How do I set the profile?

### ISSUE THREAD

**Issue by chucker** [stephanstapel/ZUGFeRD-csharp#151]
The README gives an example that starts out as:

```csharp
InvoiceDescriptor desc = InvoiceDescriptor.CreateInvoice("471102", new DateTime(2013, 6, 5), CurrencyCodes.EUR, "GE2020211-471102");
desc.Profile = Profile.Comfort;
```

However, [this commit](https://github.com/stephanstapel/ZUGFeRD-csharp/commit/0d1590afdd00572c083a6ec751245dfb96d60a28) made profile a read-only property, so the sample code can't compile as of package version 6.0.0. I also can't find overloads of the `CreateInvoice` method to choose the profile.

(Specifically, it seems I need `Profile.XRechnung`.)

**Comment by stephanstapel** [comment]
good point, this line is indeed old. I updated it. Nevertheless you find more examples further down in the readme.
If you need more sample code, please see the test project!
