### ISSUE TITLE
AppliedTradeAllowanceCharge: BasisAmount should not be present

### ISSUE THREAD

**Issue by Laser5000** [stephanstapel/ZUGFeRD-csharp#152]
Hallo,
ich muss mich auch bedanken! Klasse Projekt. Habe es damit geschafft eine zu 99% valide XRechnung zu erzeugen.
Ein kleines Problem ist allerdings aufgetaucht wenn es Zeilenrabatte gibt.
Geprüft mit
https://www.epoconsulting.com/erechnung-sap/xrechnung-validator   (Warnung)
und
https://www.zugferd-community.net/de/dashboard/validation             (Fehler)

Profil: Xrechnung
Version 2.1
Fehler / Warnung: [CII-SR-123] - BasisAmount should not be present

CodeSchnipsel aus der XML:

`     <ram:SpecifiedLineTradeAgreement>
        <ram:GrossPriceProductTradePrice>
          <ram:ChargeAmount>43.32</ram:ChargeAmount>
          <ram:BasisQuantity unitCode="H87">20.0000</ram:BasisQuantity>
          <ram:AppliedTradeAllowanceCharge>
            <ram:ChargeIndicator>
              <udt:Indicator>false</udt:Indicator>
            </ram:ChargeIndicator>
            <ram:BasisAmount>728.00</ram:BasisAmount>
            <ram:ActualAmount>254.80</ram:ActualAmount>
          </ram:AppliedTradeAllowanceCharge>
        </ram:GrossPriceProductTradePrice>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>36.4000</ram:ChargeAmount>
          <ram:BasisQuantity unitCode="H87">20.0000</ram:BasisQuantity>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>`

Gibt es eine Möglichkeit für mich die Ausgabe von "BasisAmount" zu deaktivieren? Wenn ich den Basisamount bei Generierung auf 0 setze wird er trotzdem ausgegeben und als Fehler ausgewiesen. 

vg
Mathias

**Comment by stephanstapel** [comment]
Vielen Dank.
Dies hier ist der Quellcode der Regel:

```xml<param name="CII-SR-123" value="not(ram:GrossPriceProductTradePrice/ram:AppliedTradeAllowanceCharge/ram:BasisAmount)"/>```

d.h. wird die Ausgabe-Datei erfolgreich validiert, wenn die Zeile einfach weg ist?

**Comment by Laser5000** [comment]
Ja wenn ich die Zeile BasisAmount weg lasse dann habe ich komplett valide. 
Reason habe ich nicht angegeben und deswegen vermutlich auch ohne Ausgabe. Wird mir auch nicht als Fehler ausgegeben.

Hätte das hier gefunden:

https://portal3.gefeg.com/projectdata/invoice/deliverables/installed/publishingproject/zugferd%202.0.1%20-%20facturx%201.03/en%2016931%20%E2%80%93%20facturx%201.03%20%E2%80%93%20zugferd%202.0.1%20-%20comfort.scm/html/de/021.htm?https://portal3.gefeg.com/projectdata/invoice/deliverables/installed/publishingproject/zugferd%202.0.1%20-%20facturx%201.03/en%2016931%20%E2%80%93%20facturx%201.03%20%E2%80%93%20zugferd%202.0.1%20-%20comfort.scm/html/de/0249.htm

Demnach sollte es nur ActualAmount und ChargeIndicator geben.

**Comment by Laser5000** [comment]
Ja mit Reason erhalte ich auch das von beiden Validierer als Fehler:


val-sch.1.1 | CII-SR-123 | warning | [CII-SR-123] - BasisAmount should not be present
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:IncludedSupplyChainTradeLineItem[1]/ram:SpecifiedLineTradeAgreement[1]
val-sch.1.2 | CII-SR-128 | warning | [CII-SR-128] - Reason should not be present
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:IncludedSupplyChainTradeLineItem[1]/ram:SpecifiedLineTradeAgreement[1]



Das ZUGFeRD-xml ist nicht valide.
Profile: urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0
[CII-SR-123] - BasisAmount should not be present
[CII-SR-128] - Reason should not be present
