### ISSUE TITLE
Adding support for .NET Framework 4.8

### ISSUE THREAD

**Issue by patrickthoma** [stephanstapel/ZUGFeRD-csharp#154]
Hello,

our application targets .NET Framework 4.8. When we install the ZUGFeRD-csharp nuget packages to our C# project, we get build warnings and as a result, the build fails on our buildservers. The following warning occurs:

`#[warning]: Warning MSB3268: The primary reference "MyDll.dll" could not be resolved because it has an indirect dependency on the framework assembly "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.8". To resolve this problem, either remove the reference "MyDll.dll" or retarget your application to a framework version which contains "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".`

I checked the referenced ZUGFeRD-csharp DLLs, and they are .NET Standard 2.0. Also, the nuget package only contains a .NET Standard 2.0 DLL, whereas the zugferd solution file available on github also supports .NET Framework 4.6.1. 

I am aware that .NET Framework supports .NET Standard 2.0 and therefore this procedure should work in theory. However, in reality we obtain build errors. Therefore, I would like to ask if it would be possible to include .NET Framework 4.6.1 DLLs (or even better for us, .NET Framework 4.8. DLLs) in the nuget packages?

**Comment by stephanstapel** [comment]
Hi,

there was a similar discussion here:

https://github.com/stephanstapel/ZUGFeRD-csharp/discussions/145

Will do so with the next version (already prepared), so consider it done (closing the issue here)!

**Comment by patrickthoma** [comment]
Thanks for the fast answer - seems like others had this requirement too.

Might be that I am mistaken, but unfortunatly I cannot find the .NET 4.6.1 DLL in the nuget package:

![image](https://user-images.githubusercontent.com/38472350/117427444-56cf2980-af25-11eb-83f8-bc4cf5699ad4.png)

**Comment by patrickthoma** [comment]
Perfect, thanks!

**Comment by stephanstapel** [comment]
> Might be that I am mistaken, but unfortunatly I cannot find the .NET 4.6.1 DLL in the nuget package:

yes, that is right for 6.0.0. Will change with upcoming versions.
