### ISSUE TITLE
BuyerTradeParty LineTwo (BT-51) and BuyerTradeParty LineThree (BT-163) are not existing

### ISSUE THREAD

**Issue by aschliewert** [stephanstapel/ZUGFeRD-csharp#155]
Guten Tag:-)

In dem Objekt BuyerTradeParty können üblicherweise die Adresszusätze gesetzt werden. 
Hierfür gibt es normalerweise die Eigenschaften LineTwo (BT-51) und LineThree (BT-163). 
Über das ZUGFeRD-csharp Projekt ist dies leider nicht möglich, daher meine Frage:
Ist angedacht, dass das in naher Zukunft implementiert wird?
Es gibt einige Firmen, welche die XRechnung ohne diese Felder nicht akzeptieren.

Freundliche Grüße

**Comment by stephanstapel** [comment]
Entschuldige, ich habe dieses Issue komplett übersehen. BT-51 ist ja implementiert, z.B. hier:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/a9759cb6f4631d3d335d295780c17c1d46ab8f23/ZUGFeRD/InvoiceDescriptor21Writer.cs#L1146

allerdings fußt die Belegung der Zeilen auf dem fachlichen Modell, dass der Party in der Bibliothek zugrunde liegt.

**Comment by aschliewert** [comment]
Danke für die Antwort. Ja LineOne und LineTwo lassen sich eingeschränkt setzen, das habe ich nachträglich auch noch gesehen. LineThree lässt sich nicht setzen. Diese 3 Felder sind ja zusätzliche Adressfelder, welche üblicherweise so belegt werden, wie es die fachliche Logik darstellt, aber das ist kein Muss und sie sollten in gewissen Fällen auch abweichen können bzw. könnte eine Belegung der Felder mit anderen Zusatzdaten erwünscht sein. Sollte man diese dann nicht frei belegbar machen? -und dann auch zusätzlich noch LineThree anbieten?
Vielen Dank im Vorfeld

**Comment by stephanstapel** [comment]
Hallo,
prima. Das Ziel der Bibliothek ist es, nicht 1:1 ein XML-Mapping zu C# zu implementieren, sondern das Modell semantisch zu füllen, wo es keine Semantik gibt. Das ist leider an manchen Stellen aufgeweicht, ZUGFeRD hat sich einfach gleichzeitig in zu viele Richtungen entwickelt. Dennoch halte ich dieses Ziel nach wie vor aufrecht. Mittelfristig kann man sich eher fragen, ob dieses semantische Modell nicht sogar kundenspezifisch gemappt werden kann, es gab z.B. hier https://github.com/stephanstapel/ZUGFeRD-csharp/issues/158 eine entsprechende Anfrage.

**Comment by aschliewert** [comment]
Okay das ist schade, dann muss ich diese Änderungen selbst pflegen, trotzdem danke

**Comment by tipa** [comment]
Ich unterstütze den Wusch von @aschliewert, `LineOne` and `LineTwo` selbst setzen zu können (bzw. generell näher am offiziellen Factur-X Schema zu bleiben). Beim Implementieren in mein Projekt verwirrt die unterschiedliche Benennung der Properties zw. dieser Library und dem Factur-X-Schema, sodass ich immer wieder in den Source-Code schauen muss, welche Property zu welchem XML-Node mappt. Zusätzliche Logik wie die hier macht es noch schwieriger:  https://github.com/stephanstapel/ZUGFeRD-csharp/blob/86f6a6afad329709e90610b75d082ff757098eb5/ZUGFeRD/InvoiceDescriptor22Writer.cs#L1350

**Comment by Dirksche** [comment]
Wir haben in unserer Software bei den Kundendaten außer Namen und PLZ+Ort **drei** weitere mögliche Adresszeilen, wovon eine in der Regel Straße+Hausnummer enthält.
Wir haben Logik welche entscheidet, welche Info in welcher Reihenfolge bei klassischen Rechnungen "gedruckt" wird. Daher würden wir auch gerne in der E-Rechnung explizit angeben können, welche Info in `LineOne` (BT-50), `LineTwo` (BT-51) und `LineThree` (BT-163) geschrieben wird.

Ich finde die momentane Logik, dass bei vorhandenem `ContactName` dieser in `LineOne` geschrieben wird, nicht so toll. Ich denke die ZUGFeRD-csharp Library soll es doch dem Anwender überlassen, was wo reingeschrieben wird. Wenn der Anwender den `ContactName` in die Adresszeilen geschrieben haben möchte, dann soll der Anwender den `ContactName` für `LineOne`, `LineTwo` oder `LineThree` (entsprechend wo er den reingeschrieben haben möchte) übergeben.
Wir müssten `ContactName` "missbrauchen", um all unsere Adresszeilen setzen zu können. Und der im letzten Kommentar erwähnte Code kompliziert die Logik unnötig.

Ich hoffe das klingt jetzt nicht schimpfend oder so, ich bin manchmal halt einfach sehr direkt ;-)

**Comment by stephanstapel** [comment]
Hallo @Dirksche ,
erst einmal freue ich mich, dass Ihr die Komponente so gewinnbringend für Euch einsetzen könnt.
Ich kann den Punkt inhaltlich, das ist allerdings nichts, was ich aktuell ändern möchte.

**Comment by Dirksche** [comment]
Kein Problem. Ich habe unseren Code geändert, so, dass wir die Adresszeilen entsprechend "drehen".
