### ISSUE TITLE
Problem with AddTradeLineCommentItem XRechnung

### ISSUE THREAD

**Issue by dexUserMike** [stephanstapel/ZUGFeRD-csharp#158]
The AddTradeLineCommentItem('SomeText') creates the following line:
 <ram:BilledQuantity unitCode="Unknown">0.0000</ram:BilledQuantity>
 
 The UnitCode "Unknown" ist rejected with the following Error:
 [BR-CL-23]-Unit code MUST be coded according to the UN/ECE Recommendation 20 with Rec 21 extension
 
 When I usw a validation Tool like https://ecosio.com/de/peppol-und-xml-dokumente-online-validieren/
 no error occurs, but the BUND ist rejecting a XMLFile including a TradeLineCommentItem
 
 I am Using XRechnung 2.0.0
 Any Ideas?

**Comment by stephanstapel** [comment]
Hi @dexUserMike,

can you share a larger part of that document?
Despite the documentation saying BilledQuantity is required:

![grafik](https://user-images.githubusercontent.com/2912080/130221799-20bb3843-26c5-42df-92a5-ad284c08d2fe.png)

could you go and validate the document without BilledQuantity for that particular line?

**Comment by dexUserMike** [comment]
<ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>1</ram:LineID>
        <ram:IncludedNote>
          <ram:Content>- hoheitliche Gebühren -</ram:Content>
        </ram:IncludedNote>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:Name>TEXT</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:GrossPriceProductTradePrice>
          <ram:ChargeAmount>0.0000</ram:ChargeAmount>
        </ram:GrossPriceProductTradePrice>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>0.0000</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="Unknown">0.0000</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:ExemptionReason>Dienstleistungen außerhalb des Steueranwendungsbereichs</ram:ExemptionReason>
          <ram:CategoryCode>O</ram:CategoryCode>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>0.00</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLiteItem>

Those lines produces the error. Without that lines everything is fine. 
Maybe we need a different unitCode, because UNKNOWN is no longer accepted.
This change was made by the German BUND about 4weeks ago, until then everything was fine.
My problem is, I can't reach any of the Developers at the BUND. (I quess its a facility of the German Bundesbahn)

**Comment by stephanstapel** [comment]
Thanks! The error makes total sense of course. The question is which unit code to use, there are plenty of those available:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/QuantityCodes.cs

I guess there must be a recommendation, however, there are no comment lines in any of the sample documents, neither XRechnung nor ZUGFeRD 2.x.

It'd be great if you could get this information from BUND and I'll fix this.

**Comment by dexUserMike** [comment]
<ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>1</ram:LineID>
        <ram:IncludedNote>
          <ram:Content>- hoheitliche Gebühren -</ram:Content>
        </ram:IncludedNote>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:Name>TEXT</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:GrossPriceProductTradePrice>
          <ram:ChargeAmount>0.0000</ram:ChargeAmount>
        </ram:GrossPriceProductTradePrice>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>0.0000</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="Unknown">0.0000</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:ExemptionReason>Dienstleistungen außerhalb des Steueranwendungsbereichs</ram:ExemptionReason>
          <ram:CategoryCode>O</ram:CategoryCode>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>0.00</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLiteItem>

Those lines produces the error. Without that lines everything is fine. 
Maybe we need a different unitCode, because UNKNOWN is no longer accepted.
This change was made by the German BUND about 3 weeks ago, until then everything was fine.
My problem is, I can't reach any of the Developers at the BUND. (I quess its a facility of the German Bundesbahn)

**Comment by dexUserMike** [comment]
Its hard to get someone there, I don't even have a mailadress or phonenumber
I would simply use C62 as a UnitCode per default because it stands for "one, unit and piece"
I try to reach someone for an answer, but It can take a while.

**Comment by stephanstapel** [comment]
alright, that'd be good. I just pushed the change. Can you build from source and try again?

**Comment by stephanstapel** [comment]
Hi @dexUserMike,

is your issue solved with the latest code change in the repository?

**Comment by dexUserMike** [comment]
I had no feedback yet, maybe by the end of the week. we use xrechnung only once at the beginning of a month

**Comment by stephanstapel** [comment]
alright, looking forward!

**Comment by dexUserMike** [comment]
I had no feedback yet, maybe by the end of the week. we use xrechnung only once at the beginning of a month

**Comment by dexUserMike** [comment]
C62 as UnitCode fpr cemmentline works, xrechnung confirmed. Thanks a lot.
