### ISSUE TITLE
ZUGFeRD Community

### ISSUE THREAD

**Issue by Vad1mo** [stephanstapel/ZUGFeRD-csharp#16]
FYI:

We just forked the project to the @ZUGFeRD Community. We are building up a cross Open Source community that will promote ZUGFeRD projects. 

We will communicate more details in the next weeks.

**Comment by stephanstapel** [comment]
Ist ein Fork der richtige Mechanismus? Das entkoppelt doch die Weiterarbeit in meinem Repository von dem geforkten?!

**Comment by Vad1mo** [comment]
Die Idee ist keineswegs einen Fork zu machen um die Entwicklung unter @ZUGFeRD weiter zu führen.  Ausser du möchtest das unbedingt. Siehe es eher als ein Link von @ZUGFeRD zu dem Projekt hier. 

Weiteres können wir offline besprechen. Vieles ist noch in den Anfängen und nicht in den Stein gemeisselt.

**Comment by stephanstapel** [comment]
Alles gut, ich freue mich über das gemeinsame Inhaltsverzeichnis der verschiedenen Projekte.
