### ISSUE TITLE
Payment Means in ZUGFeRD >=2.0.1

### ISSUE THREAD

**Issue by rmoosdorf** [stephanstapel/ZUGFeRD-csharp#162]
Ein konkreter (Fehler-)Fall mit Profil=XRechnung und Version=210: 
- Ich rufe `descriptor.SetPaymentMeans(PaymentMeansTypeCodes.SEPADirectDebit, "TEST", "CreditorId", "MandateNumber")` auf.

### Aktuelles Verhalten:
- Unabhängig von der verwendeten Version, werden "CreditorId" und "MandateNumber" immer als
```
    <ram:SpecifiedTradeSettlementPaymentMeans>
        <ram:TypeCode>59</ram:TypeCode>
        <ram:ID schemeAgencyID="CreditorId">MandateNumber</ram:ID>
    </ram:SpecifiedTradeSettlementPaymentMeans>
```
ausgegeben. Das ist aber nur korrekt für ZUGFeRD 1.0.

### Erwartetes Verhalten:
Angabe von BG-19 (Gruppe DIRECT DEBIT; siehe XRechnung Spec), was in ZUGFeRD zu folgenden Einträgen führen sollte: 
1. BT-89: 
```
<ram:SpecifiedTradePaymentTerms>
    <ram:DirectDebitMandateID>MandateNumber</ram:DirectDebitMandateID>
</ram:SpecifiedTradePaymentTerms>
```
2. BT-90: 
```
<ram:ApplicableHeaderTradeSettlement>
    <ram:CreditorReferenceID>CreditorId</ram:CreditorReferenceID>
</ram:ApplicableHeaderTradeSettlement>
```
3. BT-91: 
```
<ram:SpecifiedTradeSettlementPaymentMeans>
    <ram:PayerPartyDebtorFinancialAccount>
        <ram:IBANID>xxx</ram:IBANID>
    </ram:PayerPartyDebtorFinancialAccount>
</ram:SpecifiedTradeSettlementPaymentMeans>
```

Punkt 3. kann ich per AddDebitorFinancialAccount erreichen. Punkte 1. und 2. fehlen meines erachtens. Ebenso fehlt die Unterstützung für BG-18 (Gruppe PAYMENT CARD INFORMATION).

Ich hoffe das ist verständlich, ich musste mir das ziemlich zusammensuchen. :D

**Comment by rmoosdorf** [comment]
Hier noch die Specs, auf die ich mich beziehe:
[XRechnung-v1-2-0.pdf](https://github.com/stephanstapel/ZUGFeRD-csharp/files/7521954/XRechnung-v1-2-0.pdf)
[ZUGFeRD-2.1.1 - Spezifikation_TA.pdf](https://github.com/stephanstapel/ZUGFeRD-csharp/files/7521956/ZUGFeRD-2.1.1.-.Spezifikation_TA.pdf)

**Comment by stephanstapel** [comment]
Guten Morgen,
hast Du die Möglichkeit die Code-Anpassung + Tests selbst vorzunehmen und per Pull Request einzureichen? Ich gebe gerne Hinweise, welche Code-Stellen dies betrifft und schlage in diesem Fall ein kleinschrittiges Vorgehen vor (z.B. Start mit ZUGFeRD 2.0).

**Comment by rmoosdorf** [comment]
Guten Morgen,
ja, mache ich gerne.

**Comment by rmoosdorf** [comment]
Ich bräuchte noch einen Branch für meine Änderungen.

**Comment by stephanstapel** [comment]
Du musst eigentlich nur das Repository forken, rechts oben auf der Projekt-Seite
