### ISSUE TITLE
Tax in TradeAllowanceCharge

### ISSUE THREAD

**Issue by kfuxiusks21** [stephanstapel/ZUGFeRD-csharp#164]
Hi Stephan,

this is a snippet from the ZUGFeRD XML-File : 
![image](https://user-images.githubusercontent.com/43236559/142886101-855c14ed-5e63-4fe9-85f5-037ff93cc2a9.png)

and this is another snippet from my debugging session:
![image](https://user-images.githubusercontent.com/43236559/142886597-9c1efcc5-38fe-452f-a4ab-2cc1d45fc09d.png)

I'm using the version 6.2.0 of this library.

it looks like the invoice-reader does not include the tax fields from the SpecifiedTradeAllowanceCharge-Node.

i hope the information just fit your needs.

**Comment by stephan-nowecor** [comment]
could you provide the complete example? If you don't want to post it here, feel free to send it to my firstname.my lastname@web.de

**Comment by stephanstapel** [comment]
could you provide the complete example? If you don't want to post it here, feel free to send it to my firstname.my lastname@web.de

**Comment by kfuxiusks21** [comment]
Hey Stephan,

its one of the "official" ZUGFeRD-Example"-Documents
[Invoice.pdf](https://github.com/stephanstapel/ZUGFeRD-csharp/files/7586219/Invoice.pdf)

**Comment by stephanstapel** [comment]
Can you please run the tests and debug these lines:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/52c25d7dc90562c6f377bd79734e0e041b75fbb8/ZUGFeRD-Test/ZUGFeRD21Tests.cs#L122

is that what was missing? If not, can you add to the tests?

**Comment by kfuxiusks21** [comment]
In **TradeAllowanceCharges** everything works very well now and results are as expected. 👍 

During my Debugging-Session I recognized that the same problem is existent within the :
InvoiceDescriptor.ServiceCharges List<ServiceCharge>, the Tax Properties are not exported from the XML-File.
