### ISSUE TITLE
TradeLineItem attribute "ram:ExemptionReason" is useless with Profile.XRechnung

### ISSUE THREAD

**Issue by elotto** [stephanstapel/ZUGFeRD-csharp#165]
Tax ExemptionReason is required only on invoice level. Semantic model of XRechnung does not require this attribute on the invoice lines.   Our custemers have invoices with many line items included tax code "O". Through current implementation, every trade line includes following entry: 

_<ram:ExemptionReason>Dienstleistungen außerhalb des Steueranwendungsbereichs</ram:ExemptionReason>_

It grows file size and is for XRechnung-Profile useless. It may be  useful to omit generation of this attribute by InvoiceDescriptor21Writer or to give more control to invoice descriptor API for generation of tax entries on the line item level.

**Comment by stephanstapel** [comment]
Looking forward for your recommendation!

**Comment by stephanstapel** [comment]
@TomcatBB : you implemented the ExemptionReason functionality IIRC. Is it possible that you take a look at this?

**Comment by stephanstapel** [comment]
Please test.

**Comment by elotto** [comment]
Thank you for the fix. It works for me, because i don't use Profile.Extended.
