### ISSUE TITLE
Insurance Tax

### ISSUE THREAD

**Issue by TruSoggy** [stephanstapel/ZUGFeRD-csharp#167]
Is there a way to apply insurance tax?
Since i only see VAT in the library.

**Comment by stephanstapel** [comment]
I am not aware of such definitions. Please see the VAT tabs here:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/documentation/zuferd211en/Documentation/EN16931%20code%20lists%20values%20used%20from%202020-02-14.xlsx

**Comment by TruSoggy** [comment]
In the official ZUGFeRD Documentation Specifications.pdf it says in line 647 - 653

> Permitted Types of Tax 647
> - Up to profile EN 16931 (COMFORT), ZUGFeRD 2.1.1 only supports the tax type “VAT” 648 (“Umsatzsteuer”) with the code “VAT”. 649
> - The EXTENDED profile must be used in order to apply other kinds of tax, such as 650 insurance tax or mineral oil tax. The applicable code for the type of tax in question must 651 then be selected from code list UNTDID 5153.

**Comment by stephanstapel** [comment]
Alright, thanks. Do you know which exact codes can be applied here?

**Comment by TruSoggy** [comment]
All I found was this:
https://service.unece.org/trade/untdid/d95b/uncl/uncl5153.htm

**Comment by stephanstapel** [comment]
Good. Would you mind adding them here including the documentation?
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/TaxTypes.cs

I'm happy to implement the business rule that all other types than VAT are only valied for EXTENDED profile.

**Comment by TruSoggy** [comment]
Will do

**Comment by TruSoggy** [comment]
#168 Here you go.

**Comment by stephanstapel** [comment]
thanks, merged. I'll probably need some days for the remaining work on validation.

**Comment by stephanstapel** [comment]
btw. Is this valid for all versions of XREchnung and ZUGFeRD?

**Comment by TruSoggy** [comment]
Unfortunately that i don't know about. I only read the Documentation on ZUGFeRD 2.1

**Comment by stephanstapel** [comment]
Would you mind checking this:
https://github.com/stephanstapel/ZUGFeRD-csharp/commit/ad1e728311b0f7f33730feb06b279315d494550f

especially the new test cases?
