### ISSUE TITLE
Invoice kind of not readable

### ISSUE THREAD

**Issue by dsseb** [stephanstapel/ZUGFeRD-csharp#172]
The attached invoice seems to be readable and is processed by InvoiceDescriptor.Load(), but none of the contents is loaded into the properties. 

cbc:CustomizationID: urn:cen.eu:en16931:2018#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0 

Our internal DMS is able to render the invoice. It looks like this one here is using different XML namespaces?
I would appreciate your assistance.

I have removed the additional attachment from the attached sample.
[TEST XRechnung.txt](https://github.com/stephanstapel/ZUGFeRD-csharp/files/7813677/TEST.XRechnung.txt)

**Comment by stephanstapel** [comment]
Hi,
the library currently only supports CII format (see https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/demodata/xRechnung/xRechnung%20CII.xml). UBL format (see https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/demodata/xRechnung/xRechnung%20UBL.xml) is not yet supported.

If you need support for this format, I'm happy to implement this together.

**Comment by stephanstapel** [comment]
Looks like this issue isn't relevant any more.
