### ISSUE TITLE
XRechnung and TradeLineCommentItem

### ISSUE THREAD

**Issue by sebfischer83** [stephanstapel/ZUGFeRD-csharp#177]
Hi,

I add a TradeLineCommentItem and this produce the following entry in the XRechnung.
 ```
 <ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>4</ram:LineID>
        <ram:IncludedNote>
          <ram:Content>Rechnung enthält 0,50 EUR (Umsatz)Steuer auf Altteile gem. Abschn. 10.5 Abs. 3 UStAE</ram:Content>
        </ram:IncludedNote>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:Name>TEXT</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:GrossPriceProductTradePrice>
          <ram:ChargeAmount>0.0000</ram:ChargeAmount>
        </ram:GrossPriceProductTradePrice>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>0.0000</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="C62">0.0000</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:CategoryCode>O</ram:CategoryCode>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>0.00</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLineItem>
```

The validator gives me the following error.
`[BR-O-02]-An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Not subject to VAT" shall not contain the Seller VAT identifier (BT-31), the Seller tax representative VAT identifier (BT-63) or the Buyer VAT identifier (BT-48).`

I need to change the Tax to
```
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:CategoryCode>Z</ram:CategoryCode>
<ram:RateApplicablePercent>0.00</ram:RateApplicablePercent>
        </ram:ApplicableTradeTax>

```
Then it would work, but this is not editable in the library.

**Comment by stephanstapel** [comment]
Can you explain the change that you wanted to have in the xml file?
As far as I understand BR-0-02, the VAT identifiers of buyers and sellers shall not be set. Imho this doesn't make any sense since there are multiple other line items with VAT 'enabled'. This ticket say it in similar manner: https://projekte.kosit.org/xrechnung/xrechnung/-/issues/67

**Comment by sebfischer83** [comment]
I try it with the new Validator and I cant make a Text position working. I will discuss it with Kosit.

**Comment by stephanstapel** [comment]
Thanks @sebfischer83 , a discussion with Kosit would really help. I tried to contact one of the designer's of XRechnung via xing yesterday. Not sure if he will reply at all :)
