### ISSUE TITLE
Add Support for different XRechnung Versions

### ISSUE THREAD

**Issue by playunits** [stephanstapel/ZUGFeRD-csharp#179]
As of Right now there are multiple valid XRechnung 2 Versions ( 2.0, 2.1, 2.2, As seen in Profile.cs Lines 111-113)
> case "urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2": return Profile.XRechnung1;
> case "urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0": return Profile.XRechnung;
> case "urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.1": return Profile.XRechnung;
> case "urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.2": return Profile.XRechnung;

All of these evaluate to the XRechnung Profile. A further distinction could be very useful.

Also the Library currently only supports output via the XRechnung Profile to Version 2.1.
It would be great if an Option or a Profile would be added to Export to XRechnung Version 2.0 and 2.2.

**Comment by stephanstapel** [comment]
Hi,
the code you quote allows to parse all versions of XRechnung which is how it is supposed to work.
Generating profiles other than the current valid one is also not desired. Why should one want to generate old versions of XRechnung which are not valid any more?
