### ISSUE TITLE
public instead of internal?

### ISSUE THREAD

**Issue by cGiesen** [stephanstapel/ZUGFeRD-csharp#181]
Moin Staphan,

I like to ad invoice position include position number to my ZUGFeRD XML
For that, I have to create a new object of AssociatedDocument;
But I got an error: "AssociatedDocument" enthält keinen Konstruktor, der 1 Argumente annimmt."	
An Empty Constructor is also not allowed.
AssociatedDocument associatedDocument = new AssociatedDocument("1.1");

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/15cf955909605657229c7f71e01ecbff4cb272d1/ZUGFeRD/AssociatedDocument.cs#L47

cu Carsten

**Comment by stephanstapel** [comment]
Hi Carsten,

are you looking for this:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/15cf955909605657229c7f71e01ecbff4cb272d1/ZUGFeRD/InvoiceDescriptor.cs#L746

?

Cheers,

Stephan

**Comment by cGiesen** [comment]
Yes. But for some reason (I don't know), it didn't work for me.
![image](https://user-images.githubusercontent.com/2094549/170569462-0acf5759-b055-4993-b8ad-49fec5d1389f.png)

**Comment by cGiesen** [comment]
Moin Stephan,

What I like to do: 
I like to set invoice position row number.
This is located in **tradeLineItem.AssociatedDocument.LineID**

My first Idea, I set this value directly. Didn't work
Then I use: **desc.AddTradeLineCommentItem(lineID);**
But the **AssociatedDocument** object in **tradeLineItem** is stil NULL

Have a look in **zugferd_2p1_EXTENDED_Warenrechnung.pdf** there is this object filled.

Perhaps we have a look the direct way?

CU Carsten

**Comment by stephan-nowecor** [comment]
It works like this:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/ecd53fa75d7c9e888804afd4160766512a35ce11/ZUGFeRD-Test/BasicTests.cs#L62

**Comment by stephanstapel** [comment]
it should work like this:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/222ca2043f53635f2841b8f5a05f3705f1562b72/ZUGFeRD-Test/BasicTests.cs#L62
