### ISSUE TITLE
Return ZUGFeRD version

### ISSUE THREAD

**Issue by cGiesen** [stephanstapel/ZUGFeRD-csharp#182]
Moin Stephan,

we have different readers to read the XML file.
I like to get the ZUGFeRD we read the XML file with.
Perhaps **desc.Version**

just vor statistics ;)

CU
Carsten

**Comment by stephanstapel** [comment]
implemented in https://github.com/stephanstapel/ZUGFeRD-csharp/commit/c8bd31b598c1dfc1fbc697325ab89fe1c248e420
