### ISSUE TITLE
Notes of type "PayeePartyCreditorFinancialAccount" require corresponding "PayeeSpecifiedCreditorFinancialInstitution" nodes

### ISSUE THREAD

**Issue by compu-mw** [stephanstapel/ZUGFeRD-csharp#183]
Hi,

we ran into an issue using ZUGFeRD-csharp to parse XRechnung xml files.
Apparently, nodes of type 
_ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementPaymentMeans/ram:PayeePartyCreditorFinancialAccount_ 
will only be parsed if a corresponding number of nodes of type _ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementPaymentMeans/ram:PayeeSpecifiedCreditorFinancialInstitution_
are present.
The relevant code can be found at https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/InvoiceDescriptor21Reader.cs#L209.
There do not seem to exist any business rules enforcing this (at least for XRechnung) - is this intended behavior? If so, could you please explain the reasoning behind it so we can incorporate it into our parsing scheme?

Thanks and regards
Martin

**Comment by stephanstapel** [comment]
That is right. During implementation I asked myself the same. I didn't find an answer to: how would you fill those bank accounts without valid account information?

**Comment by compu-mw** [comment]
Hi,

Thanks for the quick response! 
I see what you mean; however, nodes of type _ram:PayeePartyCreditorFinancialAccount_ can hold an element of type _ram:IBANID_, containing the account's IBAN (at least for XRechnung). For transactions within the SEPA zone, this eliminates the need for further account data.
We only ran into that issue while parsing sample files, so far, but I'd assume it would be a popular use case.

Regards
Martin

**Comment by stephanstapel** [comment]
Can you provide an example (feel free to xx-out the accounts of cours)?
