### ISSUE TITLE
Help with TradeLineItem / basis_quantity != 1

### ISSUE THREAD

**Issue by SlavkoBosancic** [stephanstapel/ZUGFeRD-csharp#19]
Hello all,
I am trying to generate a COMFORT level zugferd xml, using your library.
I have a time-based line-item whose basis_quantity is defined as more than 1. Here is the example:
_________________________
![image](https://user-images.githubusercontent.com/5020737/45289392-591b2480-b4ed-11e8-8738-c92135af8eb4.png)
_________________________

If I understand the documentation correctly, the corresponding line-item XML node (IncludedSupplyChainTradeLineItem) should be defined as following:

![image](https://user-images.githubusercontent.com/5020737/45289546-ba42f800-b4ed-11e8-94f0-0a125a465d5f.png)

Should the unit code used in BasisQuantity be the same as the one in BilledQuantity? Or, can I use a period multiplier like it is in the PDF invoice (x0.25) which effectively has a different unit_code (not hours).

Your library multiplies the unit price and the billed quantity, but in the case where the basis_quantity is not 1, like the above, the multiplication result would be false (6 x 240,00 = 1440,00 instead of 60,00)
`_total = tradeLineItem.NetUnitPrice * tradeLineItem.BilledQuantity;`

Reading the specification, it is completely unclear for me if my XML representation is correct or not. So, I ask you if you have any knowledge to share regarding this?

**Comment by stephanstapel** [comment]
Sorry for the delay. I tried to contact one of my ZUGFeRD peers and ask for advice - unfortunately without any progress yet.
The xml representation looks ok to me but I asked myself whether the recipient will be able to use it accordingly. As you mentioned, my library doesn't use alternative basis quantities and I guess the same will be true on the recipient side. However, it might make sense to extend the library to support alternative basis quantities.

**Comment by stephanstapel** [comment]
Got answer now. Could you provide the full example?
My email address is {firstname}.{lastname}@web.de

**Comment by SlavkoBosancic** [comment]
Great, I will generate a PDF as soon as I am at my computer and send it.
Thanks.

**Comment by SlavkoBosancic** [comment]
Sent.

**Comment by stephanstapel** [comment]
I'm just closing the issue.
