### ISSUE TITLE
There is 0..* for InvoiceReferencedDocument not only 0..1

### ISSUE THREAD

**Issue by mbreig** [stephanstapel/ZUGFeRD-csharp#190]
In XRechnung specification the group BG-3 is defined as 0..*. BG-3 describes the invoices on which the current invoice depends on.
In the current implementation of ZUGFeRD-csharp (v9.0.0) it is only possible to define maximum one invoice.

**Comment by stephanstapel** [comment]
I'm currently working on completely different topics but ready to help. Can you point me to the field you are referring to? And is there a limit to the cardinality (depending on the invoice type).

**Comment by stephanstapel** [comment]
Alright. But how would it look with multiple reference documents?
Like this:

```xml
<ram:InvoiceReferencedDocument>
  <ram:IssuerAssignedID>RECHNUNG000</ram:IssuerAssignedID>
  <ram:FormattedIssueDateTime>
    <qdt:DateTimeString format="102">20190902</qdt:DateTimeString>
  </ram:FormattedIssueDateTime>
</ram:InvoiceReferencedDocument>
<ram:InvoiceReferencedDocument>
  <ram:IssuerAssignedID>RECHNUNG000</ram:IssuerAssignedID>
  <ram:FormattedIssueDateTime>
    <qdt:DateTimeString format="102">20190902</qdt:DateTimeString>
  </ram:FormattedIssueDateTime>
</ram:InvoiceReferencedDocument>
```

?

**Comment by mbreig** [comment]
I have checked a sample XRechnung-file with a list of two refrenced invoices (your sample above) in the kosit validator and it did not accept this file (with only one referenced invoice everything is fine).
A short look in the ZUGFeRD-reference shows that there is only one "InvoiceReferencedDocument"-node allowed. XRechnung v2.2 tells "0..*". And this is not a misprint because the description of this node says: "Eine Gruppe von Informationselementen, die Informationen über eine oder mehrere vorausgegangene Rechnung(en) enthalten"
I hate it. 
Because of the different "interpretation" of the e-invoice specification it make no sence at this time to modify your API. 
Sorry for creating this issue. 
Regards Marcus

**Comment by stephanstapel** [comment]
Thanks a lot for your investigation!
Unfortunately this is not the first time that there is 'something' between the docs and the implementation.

How about going for a list, stating in the docs that currently only 0..1 is supported by the validators and adding a occurrency check to the validator which is executed automatically before saving a file?

**Comment by mbreig** [comment]
I think this idea sounds good.
