### ISSUE TITLE
Missing distinction: BasisQuantity.UnitCode vs. BilledQuantity.UnitCode

### ISSUE THREAD

**Issue by ahagert** [stephanstapel/ZUGFeRD-csharp#191]
Great work! But I have one thing that does not match with a real world X-Rechnung I got from customer for testing purposes:

It is possible to have tradelineitems with different unit codes in "SpecifiedLineTradeAgreement" and "SpecifiedLineTradeDelivery". This happens for instance on positions having the following shape: 

Amount: X kW
Price: Y €/kW/Year
BillingSpecifiedPeriod: 20220101 - 20220131

So in my eyes it seems to be necessary to read both unit quantities to different properties. Actually both are written to "TradeLineItem.UnitCode" (InvoiceDescriptor21Reader.cs -> lines 300/ 340).

Example: 

```
<ram:SpecifiedLineTradeAgreement>
	<ram:NetPriceProductTradePrice>
		<ram:ChargeAmount>...</ram:ChargeAmount>
		<ram:BasisQuantity unitCode="DAY">365</ram:BasisQuantity>
	</ram:NetPriceProductTradePrice>
</ram:SpecifiedLineTradeAgreement>
<ram:SpecifiedLineTradeDelivery>
	<ram:BilledQuantity unitCode="KWT">...</ram:BilledQuantity>
</ram:SpecifiedLineTradeDelivery>
```

**Comment by stephanstapel** [comment]
Hello,
thanks a lot. I understand the problem here. The idea of the library is that it is no xml mapper but simplifies handling of zugferd/xrechnung invoices as much as possible. Imho, because of all special xrechnung features inside the library now, it has almost become a nightmare to generate a simple invoice.

**Comment by ahagert** [comment]
Hello,
your library is 99% of what I need for a commercial project (besides it has to be COM-visible ;-)). I've seen, it's under apache 2.0 license. I have no experience with that. So can I ask you some questions? It seems to be allowed to do a fork and modifiy it for our purposes. Of course your comments an licencing will be preserved in the project and I'll state changes made.

1. Is it allowed to rename the modified project and binaries (i.e. s2industries.ZUGFeRD.dll -> mycompany.ZUGFeRD.dll)?
2. Have I to publish my modifications (on github, under the same licence)?
3. What additional information I have to deploy? There is no "NOTICE" file I could deploy. So is it enough to place a information in our public documentation or has it to be on a defined place?

Best regards!

**Comment by stephanstapel** [comment]
Hi @ahagert ,
Please read the license in section 4, Redistribution. It seems like you are free to rename and modify as you wish.
However, I find it to be quite unfair to rename the file and to keep improvements for yourself. Remember, years of work by myself are buried in the library.

**Comment by ahagert** [comment]
I agree, of course. I just see problems if we create a version (i.e. 10.0.0.0) which is different from a possible next version of yours. So what about "s2industries.mycompany.ZUGFeRD.dll" or vice versa? And of course I also will ask my head for a donation.

Best regards!
