### ISSUE TITLE
QuantityCodes nicht vollständig

### ISSUE THREAD

**Issue by KVS-CBL** [stephanstapel/ZUGFeRD-csharp#2]
Hallo zusammen,
erstmal Glückwunsch zu diesem tollen Projekt!

Ist es Absicht das als QuantityCode nur Unknown, C62, KGM, MTK angeboten werden?
Die Liste sollte um folgende Werte ergänzt werden: DAY, HAR, HUR, KTM, KWH, LS, LTR, MIN, MMK, MMT, MTQ, MTR, NAR, NPR, P1, SET, TNE, WEE
Diese Einheiten sind zumindest in der offiziellen ZUGFeRD Codeliste enthalten.

**Comment by stephanstapel** [comment]
Die Implementierung stützt sich im wesentlichen noch auf die Version 0.9. Hier waren meines Wissens die genauen Wertemengen noch nicht enthalten. Vielen Dank aber für den Hinweis und den Patch!
