### ISSUE TITLE
BankAccount ram:BICID

### ISSUE THREAD

**Issue by Argollinger** [stephanstapel/ZUGFeRD-csharp#206]
Bei Prüfung einer erstellten Factur-X 2.1 Datei erhalte ich beim Prüfportal von Gefeg immer die Meldung "Das Element 'ram:PayerSpecifiedDebtorFinancialInstitution' soll in diesem Kontext nicht verwendet werden. [Zeile 0452]"
Ursprung ist die Ausgabe des Tag BIC obwohl dieser leer ist.
Besteht die Möglichkeit im InvoiceDescriptor21Writer sowohl für Debitor und Creditor eine if Bedingung einzubauen, so das der Tag nur ausgegeben wird, wenn auch eine BIC angegeben wurde.
if (!String.IsNullOrEmpty(account.BIC))
{
Writer.WriteStartElement("ram:PayeeSpecifiedCreditorFinancialInstitution");
Writer.WriteElementString("ram:BICID", account.BIC);
Writer.WriteEndElement(); // !PayeeSpecifiedCreditorFinancialInstitution
}

If Bedingung war im 20 Writer beinhaltet und ist jetzt nicht mehr da.
Oder hat dies einen bestimmten Hintergrund?
Laut Spezifikation ist dies nicht erforderlich, aber wenn Tag ausgeben wird muß auch ein Wert drin stehen.

**Comment by stephanstapel** [comment]
Hallo,
Du kannst gerne einen Pull Request stellen mit dem Verweis auf BT-86. Wenn ich das richtig nachvollziehen konnte (Blame-Funktion auf der Datei), ist beim Wechsel von alten Konten-Strukturen auf die neuen Strukturen nicht mitübertragen worden, dass diese Information optional ist.
Bitte erstelle in der entsprechenden Datei einen Testfall (z.B. Erstellen einer Rechnung ohne BIC, Parsen des Ergebnis-Strings, ob dort "BICID" vorhanden ist). Danke!

**Comment by Argollinger** [comment]
Hallo,
habe einen Pull Request mit den Änderungen erstellt. #207
