### ISSUE TITLE
Party ID miss the SchemeID

### ISSUE THREAD

**Issue by danvy** [stephanstapel/ZUGFeRD-csharp#208]
Hello,
Factru-X documents get rejected because SpecifiedLegalOrganization ID does not have a schemeId attribute 0002.
I investigate in the source code and noticed that it would require to change Party.ID from string to GlobalID. This would introduce breaking changes.
Is there any advice if I push such pull request ?

**Comment by stephanstapel** [comment]
Hi,
SpecifiedLegalOrganization is currently not written as a part of a party. If you want, I'd be happy to review your pull request.
ISO 6523 is implemented in GlobalID

Please make sure to implement both reader and writer and provide tests to allow reading of Factur-X files including and not including this information.

Imho, this should go into _writeOptionalParty(). If you add it to InvoiceDescriptor21Writer and InvoiceDescriptor21Reader, I can backport it to version 2.0.

**Comment by danvy** [comment]
PR #209 submitted
