### ISSUE TITLE
Wrong length of datetime element

### ISSUE THREAD

**Issue by DasNeo** [stephanstapel/ZUGFeRD-csharp#21]
Hey,
I'm trying to read a ZUGFERD xml but I'm getting the error ["Wrong length of datetime element"](https://github.com/stephanstapel/ZUGFeRD-csharp/blob/4d6747c7812d77c661ce414109bdc6c3d5f6d8de/ZUGFeRD/InvoiceDescriptorReader.cs#L484).

![image](https://user-images.githubusercontent.com/13910771/46934160-020def80-d057-11e8-958e-8f3f97d77b7d.png)

What am I doing wrong here?

Thanks,
DasNeo.

**Comment by DasNeo** [comment]
Hey,

I sent you an email.

Kind Regards,
DasNeo

**Comment by stephanstapel** [comment]
Data was really wrong, the DateTimeString field was empty so the exception was right :)
