### ISSUE TITLE
DefinedTradeContact missing in Zugferd 2.1, EN16931/Comfort

### ISSUE THREAD

**Issue by WernerK61** [stephanstapel/ZUGFeRD-csharp#210]
Hi,

documentation for Zugferd 2.1 says that DefinedTradeContact is used in EN16931/Comfort.

If output profile XRechnung is used, then DefinedTradeContact is correctly written,
but if EN16931/Comfort is used, then DefinedTradeContact is omitted.

I guess that the reason is that in InvoiceDescriptor21Writer.cs  Line 1185  Profile.Comfort is missing:
_writeOptionalContact(writer, "ram:DefinedTradeContact", contact, Profile.Extended | Profile.XRechnung1 | Profile.XRechnung);

Is this a bug, or is this DefinedTradeContact in EN16931 intentionally missing for some reason ?

Regards
Werner

**Comment by stephanstapel** [comment]
I see your point. Things are a bit more complicated unfortunately. Please search for DefinedTradeContact in the TA document.

DefinedTradeContact is written in Comfort profile only for the parties:
* SellerTradeParty
* BuyerTradeParty

but not:
* ShipToTradeParty
* UltimateShipToTradeParty
* ShipFromTradeParty
* InvoicerTradeParty (not yet implemented)
* PayeeTradeParty (not yet implemented)
* SellerTaxRepresentativeTradeParty (not yet implemented)
* ProductEndUserTradeParty (not yet implemented)

i.e. trade party is not trade party anymore. I honestly have no idea how to implement this as _writeOptionalParty() is used for all sorts of parties.

**Comment by KSafadi** [comment]
Same issue for me. When Profile basic is used, then DefinedTradeContact is omitted. When using XRECHNUNG, everything works.

**Comment by stephanstapel** [comment]
@KSafadi: yes, that should be alright. It is defined like this in the specification.
btw: which type of party are you writing to the invoice file? There are multiple scenarios, when DefinedTradeContact is written and when not

**Comment by KSafadi** [comment]
@stephanstapel alright! I am writing to the SellerTradeParty.

**Comment by stephanstapel** [comment]
In case of SellerTradeParty, it should be written only in these profiles:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/85c9c3e5-a42d-447b-aa3b-4f333294008a)

**Comment by stephanstapel** [comment]
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/8c57c2e2b2c1453fcbbb31de24ad9a10c118ff91/ZUGFeRD/InvoiceDescriptor22Writer.cs#L1369

**Comment by KSafadi** [comment]
@stephanstapel ah okay that makes sense. Thank you.

**Comment by marvinvalent** [comment]
@stephanstapel I don't understand. Wouldn't that call of _writeOptionalContact need Profile.Comfort added to the Profile-parameter for it to be written in the profile for EN 16931?

**Comment by stephanstapel** [comment]
@marvinvalent : you are right, thanks
