### ISSUE TITLE
Set Peppol EndpointID

### ISSUE THREAD

**Issue by drocx** [stephanstapel/ZUGFeRD-csharp#216]
Hello, 
in Luxembourg, sending via Peppol is now mandatory.
Therefore, we planned to generate a Zugferd invoice in the xrechnung variant and upload it manually to a portal there.
However, the EndpointID must be stored after the buyer postal address in the xrechnung.

<ram:URIUniversalCommunication>
  <ram:URIID schemeID="9938">LU123456789</ram:URIID>
</ram:URIUniversalCommunication>

https://www.cc.lu/de/themendossiers/e-invoicing/faq

Is there already a way to define this EndpointID in the code? Unfortunately I didn't find anything there.

Regards,
Daniel

**Comment by stephanstapel** [comment]
included in version 12.0
