### ISSUE TITLE
Eine Assembly mit starkem Namen ist erforderlich. (Ausnahme von HRESULT: 0x80131044)

### ISSUE THREAD

**Issue by drocx** [stephanstapel/ZUGFeRD-csharp#22]
Hallo,

ich habe das ZUGFeRD Nuget Paket von Version 2.6 auf Version 2.7 in meinem Projekt aktualisiert.
Seid dem bekomme ich folgende Fehlermeldung:

> Die Datei oder Assembly "s2industries.ZUGFeRD, Version=2.7.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Eine Assembly mit starkem Namen ist erforderlich. (Ausnahme von HRESULT: 0x80131044)

Die DLL hat seid Version 2.7 auch keinen Strong Name mehr.

![zugferd](https://user-images.githubusercontent.com/2034544/48251500-2795db00-e402-11e8-8542-2d5d550d3aa5.png)

Ist dies so gewollt?

**Comment by stephanstapel** [comment]
Der Verzicht auf einen Strong Name war keine Absicht. Ich habe die Umstellung auf .net Standard lediglich über einen Pull Request übernommen. Nun gibt es die Version 2.7.1. Funktioniert dies besser?

**Comment by drocx** [comment]
Mit der neue Version funktioniert es wieder.
Danke 👍
