### ISSUE TITLE
SpecifiedTradePaymentTerms should be [0..n], but is [0..1]

### ISSUE THREAD

**Issue by sude22** [stephanstapel/ZUGFeRD-csharp#223]
Hello,
and first of all thank you for the great work on this project.

When importing an invoice, I noticed that there is a property "PaymentTerms". It is filled with the content from "SpecifiedTradePaymentTerms".
However, in my invoice there are two"SpecifiedTradePaymentTerms" sections.

Shouldn't the "PaymentTerms" property then be a list?
![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/3779162/353f84b8-6dd4-44ee-808c-93f521244ea9)

Example:
`<ram:SpecifiedTradePaymentTerms>`
`    <ram:Description>Zahlbar bis 07.01.2024 ohne Abzug</ram:Description>`
`    <ram:DueDateDateTime>`
`        <udt:DateTimeString format="102">20240107</udt:DateTimeString>`
`    </ram:DueDateDateTime>`
`</ram:SpecifiedTradePaymentTerms>`
`<ram:SpecifiedTradePaymentTerms>`
`    <ram:Description>Zahlbar bis 15.12.2023  3,00% Skt= 1039,84</ram:Description>`
`    <ram:DueDateDateTime>`
`        <udt:DateTimeString format="102">20231215</udt:DateTimeString>`
`    </ram:DueDateDateTime>`
`    <ram:ApplicableTradePaymentDiscountTerms>`
`        <ram:BasisAmount currencyID="EUR">1072.00</ram:BasisAmount>`
`        <ram:CalculationPercent>3.00</ram:CalculationPercent>`
`    </ram:ApplicableTradePaymentDiscountTerms>`
`</ram:SpecifiedTradePaymentTerms>`

BTW: It would be excellent if the fields in "ApplicableTradePaymentDiscountTerms" could also be imported, as then automatic processing of the discount values would be possible.

**Comment by stephanstapel** [comment]
Thanks for your initiative!
I'd be more than happy if you could issue a pull request. Please remember to implement both reader and write and add test cases

**Comment by jochenkirstaetter** [comment]
Hi @stephanstapel 

Kindly assign this one to me.
I'm going to implement the [0..n] cardinality. I might need this for my current assignment where multiple payment terms are required.

Cheers, JoKi

**Comment by stephanstapel** [comment]
@jochenkirstaetter: thanks! Please remember backwards compatibility and please add test cases.

**Comment by jochenkirstaetter** [comment]
@stephanstapel 

Interestingly, the `InvoiceProvider` in the test project already provides [multiple payment terms](https://github.com/jochenkirstaetter/ZUGFeRD-csharp/blob/78fcafeda1eaee82fc119491bc1615020e50f31c/ZUGFeRD-Test/InvoiceProvider.cs#L105), although as a single one due to the existing cardinality.

`desc.SetTradePaymentTerms("Zahlbar innerhalb 30 Tagen netto bis 04.04.2018, 3% Skonto innerhalb 10 Tagen bis 15.03.2018");`

I'm going to use this example as base for my implementation.

**Comment by stephanstapel** [comment]
> @stephanstapel
> 
> Interestingly, the `InvoiceProvider` in the test project already provides [multiple payment terms](https://github.com/jochenkirstaetter/ZUGFeRD-csharp/blob/78fcafeda1eaee82fc119491bc1615020e50f31c/ZUGFeRD-Test/InvoiceProvider.cs#L105), although as a single one due to the existing cardinality.
> 
> `desc.SetTradePaymentTerms("Zahlbar innerhalb 30 Tagen netto bis 04.04.2018, 3% Skonto innerhalb 10 Tagen bis 15.03.2018");`
> 
> I'm going to use this example as base for my implementation.

I guess I stole the example from ZUGFeRD 1.0 sample data :)

**Comment by jochenkirstaetter** [comment]
Hm, interesting.

The specification of Version XRechnung 2.2.0 | Fassung vom 27.01.2022 specifies the _Payment Terms_ as a single, optional element.

![image](https://github.com/user-attachments/assets/72a3e29c-b958-4858-bb19-10980a869fec)

Sounds a bit like a challenge to apply the right profile handling to it.

Game on... 

@sude22 - could you please provide me a link or source of the specs in your original post? Thanks a bunch.

PS: Conversion to a List has been done already, I'm currently in the validation phase. Hence, stumbling over those specification details of each version and profile.

**Comment by stephanstapel** [comment]
Just found this in ZUGFeRD 2.2 specification:

![grafik](https://github.com/user-attachments/assets/46e0d5e2-9a24-41a7-a130-f13e6daa152b)

cardinality is a bit weird. This would meet your screenshot about XRechnung/ EN16931/ Comfort.

**Comment by jochenkirstaetter** [comment]
Thanks @stephanstapel , 
that would mean, that multi cardinality seems to be bound to Extended only. 

OK, this is mainly bothering the writing process, as the reading is always a loop. I guess, I'll add conditional writing based on the Profile. That should resolve the issue.

Cheers, JoKi
