### ISSUE TITLE
InvoiceDescriptor.Load cannot load version xrechnung_3.0

### ISSUE THREAD

**Issue by Chips100** [stephanstapel/ZUGFeRD-csharp#224]
Reading any XRechnung by calling `InvoiceDescriptor.Load` with version string `urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0` leads to an UnsupportedException with message *No ZUGFeRD invoice reader was able to parse this stream!.*

The commit history shows a commit to add support vor XRechnung 3.0.1, but as far as I can see, it does not apply to loading files. Is there a plan when such a support will be added?

**Comment by stephanstapel** [comment]
Hi @Chips100 
happy to receive a pull request.
It should be here:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/36a447b712a9250157426699c388715b822928dd/ZUGFeRD/InvoiceDescriptor21Reader.cs#L404C17-L404C17

**Comment by Chips100** [comment]
Thanks for the quick response!
I was unsure if the `InvoiceDescriptor21Reader` is fully compatible, but for our (small) scenarios it works well in local tests. I will open a PR.

**Comment by stephanstapel** [comment]
Thanks! The remaining dealing with version is here:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/Profile.cs
and should be correct. Happy if you would like to review it.

**Comment by Chips100** [comment]
I already peaked into that commit and while I am not *that* familiar with the library, it does look good to me! 👍
