### ISSUE TITLE
ZUGFeRD 2.0 und Profil EN16931 (XRechnung)

### ISSUE THREAD

**Issue by drocx** [stephanstapel/ZUGFeRD-csharp#23]
Hallo,

planst du eventuell schon das ZUGFeRD Format 2.0 zu unterstützen?
~~Neu ist unter anderem ein neues Profil EN16931.~~
Das Comfort Profil wurde zum Profil EN16931 umbenannt und erweitert.

Dieses ist identisch mit dem XRechnung Standard. Somit hätte man mit einer Schnittstelle zwei Standards unterstützt.
XRechnung wird ab 2020 für diverse öffentlichen Verwaltungen als Pflicht vorgeschrieben.
Bei XRechnung wird nur das XML versendet ohne PDF Datei.

[Was ist der Unterschied zwischen ZUGFeRD 2.0 und der XRechnung und worin genau liegt hier der Vorteil von ZUGFeRD 2.0?](https://www.ferd-net.de/zugferd/zugferd-faq/was-ist-der-unterschied-zwischen-zugferd-2.0-und-der-xrechnung-und-worin-genau-liegt-hier-der-vorteil-von-zugferd-2.0.html)
[Was ist der Unterschied zwischen „ZUGFeRD Version 1“ und „ZUGFeRD Version 2"?](https://www.ferd-net.de/zugferd/zugferd-faq/was-ist-der-unterschied-zwischen-zugferd-version-1-und-zugferd-version-2.html)

**Comment by stephan-nowecor** [comment]
Hallo,
ja, das habe ich vor, allerdings habe ich aktuell leider andere Prioritäten, so dass sich dies verzögert. Die Anwendung ist darauf vorbereitet, es bedarf nach meinem aktuellen Verständnis von ZUGFeRD 2.0 eigentlich nur eines neuen Writers und Readers, der die neue Version schreibt bzw. liest.

Das Metamodell/ Domänenmodell ist ja im wesentlichen unverändert, so dass ich dies zunächst weiterverwenden würde. Das hätte dann auch den Vorteil, dass man ZUGFeRD 1.0 lesen kann und ZUGFeRD 2.0 daraus schreiben kann und umgekehrt.

Für Unterstützung bin ich dankbar, ich kann auch gerne die Basisarbeit übernehmen. Bitte dann um eine kurze Info!

**Comment by stephanstapel** [comment]
Hallo,
ja, das habe ich vor, allerdings habe ich aktuell leider andere Prioritäten, so dass sich dies verzögert. Die Anwendung ist darauf vorbereitet, es bedarf nach meinem aktuellen Verständnis von ZUGFeRD 2.0 eigentlich nur eines neuen Writers und Readers, der die neue Version schreibt bzw. liest.

Das Metamodell/ Domänenmodell ist ja im wesentlichen unverändert, so dass ich dies zunächst weiterverwenden würde. Das hätte dann auch den Vorteil, dass man ZUGFeRD 1.0 lesen kann und ZUGFeRD 2.0 daraus schreiben kann und umgekehrt.

Für Unterstützung bin ich dankbar, ich kann auch gerne die Basisarbeit übernehmen. Bitte dann um eine kurze Info!

**Comment by Noratem** [comment]
Hallo, 
ich muss mich auch grade beruflich etwas damit beschäftigen und wollte nur einen Hinweis da lassen, dass meiner meinung nach das Modell doch an enigen Stellen geändert wurde, sogar inkompatibel zu V1. Zumindest interpretieren ich das so, z.B. bei "AdditionReferencedDocument". Das sieht in der V2 ganz anders aus als bisher in V1. 
Wollte das nur als Tipp hier bereits mal reinschreiben.

**Comment by stephanstapel** [comment]
danke für die Info, ich schaue mir das an. Ich hoffe jedoch immer noch, dass ich das Modell in der Bibliothek zusammenhalten kann für beide Versionen. Vielleicht muss ich das über eine entsprechende Erweiterung, Dokumentation, Fehlermeldungen bei Inkompatibilität regeln. Mal schauen!
