### ISSUE TITLE
Misplaced tag InvoiceCurrencyCode ?

### ISSUE THREAD

**Issue by Lau1234** [stephanstapel/ZUGFeRD-csharp#230]
Hi, 

I am using Zugferd version 1.0 with extended profile and try to validate the invoice with the zugferd-community.net validator. I get the following error : `schema validation fails:org.xml.sax.SAXParseException; lineNumber: 108; columnNumber: 32; cvc-complex-type.2.4.a: Invalid content was found starting with element '{"urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":InvoiceCurrencyCode}'. 
One of '{"urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":PayeeTradeParty, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":SpecifiedTradeSettlementPaymentMeans, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":ApplicableTradeTax, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":BillingSpecifiedPeriod, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":SpecifiedTradeAllowanceCharge, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":SpecifiedLogisticsServiceCharge, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":SpecifiedTradePaymentTerms, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":SpecifiedTradeAccountingAccount, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":SpecifiedTradeSettlementMonetarySummation, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12":ReceivableSpecifiedTradeAccountingAccount}' is expected.` 
Wich refers to this part in the xml file : 
```
 <ram:ApplicableSupplyChainTradeSettlement>	
      <ram:InvoiceeTradeParty>
        <ram:Name>xxxxxxxx</ram:Name>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>xxxxx</ram:PostcodeCode>
          <ram:LineOne>xxxxxxxx</ram:LineOne>
          <ram:LineTwo>xxxxxxxxx</ram:LineTwo>
          <ram:CityName>xxxxxxxx</ram:CityName>
          <ram:CountryID>Unknown</ram:CountryID>
        </ram:PostalTradeAddress>
      </ram:InvoiceeTradeParty>      
	  <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>        <-------- here
      <ram:SpecifiedTradeSettlementPaymentMeans />
      [....]
     </ram:ApplicableSupplyChainTradeSettlement> 
```

In the documentation of 1.0 Extended version, it seems that the InvoiceCurrencyCode is defined before InvoiceeTradeParty & PayeeTradeParty tags no ?

**Comment by stephanstapel** [comment]
Yes, you are right. I rarely came across someone still using SAX though :)
I have fixed it:
https://github.com/stephanstapel/ZUGFeRD-csharp/commit/d81522f6a885a5760ae702774c48f9dfe94460c2

**Comment by Lau1234** [comment]
thank you for the reply and the quick fix!
