### ISSUE TITLE
Adding new entries to QuantityCodes enum 

### ISSUE THREAD

**Issue by skeller1** [stephanstapel/ZUGFeRD-csharp#231]
We're are missing some quantity codes. Is it useful to generate a complete enum from https://www.zugferdpro.com/unitcodes-fuer-die-menge-in-zugferd-xrechnung-xinvoice/

I would like to prepare a pull request.

[rec20_Rev15e-2020.xls](https://github.com/stephanstapel/ZUGFeRD-csharp/files/14124969/rec20_Rev15e-2020.xls)

Regards,
skeller1

**Comment by stephanstapel** [comment]
feel free to add what you need, I will take a look at it. I definitely don't want the entire rec20 list in the library as this would yield the library useless since it would be impossible to understand what to use under what circumstance.

**Comment by skeller1** [comment]
https://github.com/stephanstapel/ZUGFeRD-csharp/pull/232
