### ISSUE TITLE
Missing schemaID "EM" for ElectronicAddress

### ISSUE THREAD

**Issue by vissers-dev** [stephanstapel/ZUGFeRD-csharp#234]
Hi Stephan, thank you very much for this great project. 

I tried the latest Version and tried to validate the xml with Ecosio. I got a warning, that I must set the Sellers and Buyers Electronic Address. According to the new requirements it must be filled. An Email is okay. But then we must set the Schema ID to "EM"

That would be great if this works :)

Thank you

**Comment by stephanstapel** [comment]
Hi @vissers-dev ,
as far as I understand the standard, these are the possible values for a scheme id:
https://docs.peppol.eu/poacc/billing/3.0/codelist/eas/
This list is fully implemented. If you have a different source, please share it.
Cheers,
Stephan

**Comment by vissers-dev** [comment]
Hi,

EAS is full implemented. But this only the usecase for Peppol (?). 

https://blog.seeburger.com/de/xrechnung-version-3-0-1-gueltig-ab-01-februar-2024/

"Im Use Case Peppol ist hier die Peppol-ID des Empfängers (C4) anzugeben,
im Use Case E-Mail-Versand die E-Mail-Adresse des Käufers/Rechnungsempfängers der E-Mail."

or here:

https://www.e-rechnung-bund.de/standard-xrechnung-3-0-1/

"Beispiel: Als Lieferant geben Sie dem Kunden Ihre E‑Mail z. B. <cbc:EndpointID schemeID=“EM“>seller@email.de</cbc:EndpointID> an. Damit haben Sie das Pflichtfeld BT‑34 angegeben. Zusätzlich müssen Sie noch eine elektronische Adresse Ihres Kunden angeben: <cbc:EndpointID schemeID=“EM“>buyer@info.de</cbc:EndpointID>. Damit haben Sie das Pflichtfeld BT‑49 korrekt befüllt.

Nach Absprache mit Ihrem Lieferanten können Sie auch eine Leitweg‑ID oder eine andere gültige elektronische Adresse der EAS‑Code‑Liste angeben bzw. diese einfordern. "

So, it look likes it is EAS or "EM".... 

But I am really not sure......

**Comment by stephan-nowecor** [comment]
I found it:
https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931

respectively:
https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931?preview=/467108974/691830878/Electronic%20Address%20Scheme%20Code%20list%20-%20version%2012%20-%20published%20Sept2023.xlsx

can you add these:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/37704978/eb595552-d736-4efc-9b3f-f59389e80e91)

along with the description:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/37704978/3c2463af-2cbc-4c6c-ae9c-38bd59650df1)

and issue a PR?

**Comment by stephanstapel** [comment]
I found it:
https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931

respectively:
https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931?preview=/467108974/691830878/Electronic%20Address%20Scheme%20Code%20list%20-%20version%2012%20-%20published%20Sept2023.xlsx

can you add these:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/a97b791d-1477-46f9-a6b3-cabd9f25482e)


along with the description:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/cdb740ec-3b59-4a68-bebd-929752a470bf)

and issue a PR?

**Comment by vissers-dev** [comment]
Thanks to Stephan who found the necessary infos :)
