### ISSUE TITLE
New Warnings with xrechnung 3.0.1

### ISSUE THREAD

**Issue by drocx** [stephanstapel/ZUGFeRD-csharp#237]
Since version 3.0.1 is in effect, new warnings appear when validating our xrechnungen.
![Screenshot 2024-02-15 090943](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2034544/c8d36507-5390-4e1e-a498-de8e864eda65)

The first warning states that a business process must be defined. This can be resolved as follows:
`desc.BusinessProcess = "urn:fdc:peppol.eu:2017:poacc:billing:01:1.0";`

The other two warnings appear because we have not defined an ID for the seller and the buyer party.
An empty tag is then written.
Empty tags should apparently no longer be written with the new version.
I have already fixed it for the ID in this PR #236 .

PS: The 12.5.0 Version is missing on the Github Release page. It's only avaiable via nuget.

**Comment by stephan-nowecor** [comment]
Thanks. I understand that there is nothing to be done, I just should add the desc.BusinessProcess hint to the readme page, right?
If so, can you close this issue?

**Comment by drocx** [comment]
The code would probably have to ensure that no more empty tags are written or that there is an option that empty tags are removed before the XML is created.

The warnings from version 2.x have now become mandatory fields in version 3.x. These warnings will probably also become mandatory in the next major release.
[](https://blog.seeburger.com/de/xrechnung-version-3-0-1-gueltig-ab-01-februar-2024/)
The library should support writing these fields to fix all possible warnings.

In the near future, Peppol will certainly also be a bigger topic in Germany:
[](https://www.haufe.de/steuern/gesetzgebung-politik/elektronische-rechnung-wird-pflicht-e-rechnung-im-ueberblick_168_605558.html)

**Comment by stephanstapel** [comment]
I have refactored quite a bit. Can you check if the new version validates properly?

**Comment by drocx** [comment]
Yes. The version validates without errors with the KosIT Validator. The invoices generated with it were accepted at the Luxembourg Peppol portal successfully.

**Comment by drocx** [comment]
I’ll take a look at the version at the beginning of the week.

**Comment by drocx** [comment]
I just created 2 invoices again as XML with the refactored version, which I already successfully validated last week. The files are identical and can therefore also be validated.

**Comment by drocx** [comment]
[Specification XRechnung 3.0.1](https://xeinkauf.de/app/uploads/2023/09/301-XRechnung-2023-09-22.pdf)
I have just found the text passage again where it was pointed out that the warnings can be upgraded to errors. It's on page 84.

<img width="488" alt="image" src="https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2034544/98c7a7fd-a9d3-407c-b88f-2015ea264ed5">

You can close this issue and create a new nuget package.
