### ISSUE TITLE
Add profile for e-reporting

### ISSUE THREAD

**Issue by Athilla** [stephanstapel/ZUGFeRD-csharp#239]
Into factur-x we have two main stream.
e-invoicing (usualy with profile extended by exemple)
e-reporting ( for all invoice with external - not french company )

**Comment by stephanstapel** [comment]
Hi Athilla,
thanks for your pull requests. I would like to add some information about EReporting to the readme. Since this topic is really new to me, is there a good source with a description what E-Reporting is about that I can use for the readme?

**Comment by Athilla** [comment]
Hello Stephan,
To give you a quick summary of what I've understood:
- The French tax authorities require two flows: EInvoicing and EReporting.

Basically, the difference is that EInvoicing is used when there is VAT to
recover between companies, and EReporting is for third parties and
companies outside France, when there is VAT at 0 for example.

from :
https://www.impots.gouv.fr/e-reporting-la-transmission-de-donnees-de-transaction-ladministration

*Who is subject to e-reporting of transaction data?*
All VAT-registered businesses established in France are affected by the
e-reporting of transaction data when they carry out transactions with
private customers (business to consumer, BtoC) or with foreign operators
(businesses or private individuals). Certain foreign companies not
established in France may be subject to the e-reporting obligation,
provided that the transaction they are carrying out is with a person not
subject to VAT (most often a private individual, but it may also be an
association or a public entity) or a taxable person not established in
France, and that the transaction is located in France under the rules of
the General Tax Code.

*Which transactions are covered by e-reporting?*
The transactions that will have to give rise to the transmission of data
(e-reporting) concern businesses subject to VAT in France and trading with
private individuals and, more generally, non-taxable persons (business to
consumer or BtoC), with businesses not established in France (i.e. taxable
persons who do not have an establishment, domicile or habitual residence in
France).

Companies not established in France, or their tax representatives where
applicable, must also transmit transaction data for transactions located in
France that they carry out with non-taxable persons (individuals in
particular) or other taxable persons not established in France.

However, transactions exempt from VAT under the provisions of articles 261
to 261 E of the General Tax Code, which are exempt from invoicing, do not
fall within the scope of e-reporting. This applies in particular to certain
banking and insurance transactions, medical and health services,
educational services and transactions carried out by non-profit-making
organisations whose management is disinterested.


Translated with www.DeepL.com/Translator (free version)

**Comment by stephanstapel** [comment]
Just a last question: who is the recipient for ereporting documents? Is it the tax authorities?
