### ISSUE TITLE
Linebreakes in Notes

### ISSUE THREAD

**Issue by bashuss** [stephanstapel/ZUGFeRD-csharp#24]
Wenn ich bei einem TradeLineItem zusätzlich zu einem Namen eine mehrzeilige Description angebe, so ist der darin enthaltene Zeilenumbruch u.U. für das Verständnis notwendig.
Derzeit wird der übergebene Text jedoch einfach direkt so ins XML gerendert, oder?
D.h. dass ein Zeilenumbruch für einen XML-Parser einfach zu einem Whitespace wird, oder ist hier ein anderer Standard definiert?

Müsste man potentiell mehrzeilige Texte nicht in ein <![CDATA[...]> einpacken?
Sollte das nicht von der Bibliothek übernommen werden?

Gruß,
Bernd

**Comment by stephanstapel** [comment]
sorry für die späte Antwort, die Notification war im Spam-Ordner gelandet.

Ja, ich würde das so verstehen, dass regelkonform Zeilenumbrüch umgewandelt werden wie hier beschrieben:
https://www.w3.org/TR/xml/#AVNormalize
