### ISSUE TITLE
DefinedTradeContact xml tag issue

### ISSUE THREAD

**Issue by landrix** [stephanstapel/ZUGFeRD-csharp#241]
i think

`OrgUnit = _nodeAsString(doc.DocumentElement, "//ram:BuyerTradeParty/DefinedTradeContact/ram:DepartmentName", nsmgr),`

should be

`OrgUnit = _nodeAsString(doc.DocumentElement, "//ram:BuyerTradeParty/ram:DefinedTradeContact/ram:DepartmentName", nsmgr),`

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/16ec6fd078bb6311a49f97fa9d88e94cabad78e3/ZUGFeRD/InvoiceDescriptor21Reader.cs#L136

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/16ec6fd078bb6311a49f97fa9d88e94cabad78e3/ZUGFeRD/InvoiceDescriptor1Reader.cs#L108

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/16ec6fd078bb6311a49f97fa9d88e94cabad78e3/ZUGFeRD/InvoiceDescriptor20Reader.cs#L111

**Comment by stephanstapel** [comment]
yes, that looks right. Could you create a PR?

**Comment by landrix** [comment]
sry, i dont't use this library directly. I'm just porting it into another language, that's when I noticed this. Please correct it yourself when you get the chance.

**Comment by stephanstapel** [comment]
fixed by:
https://github.com/stephanstapel/ZUGFeRD-csharp/pull/242
thanks!
