### ISSUE TITLE
XRechnung 3.01 - Issue with Specifying Charge Percentage

### ISSUE THREAD

**Issue by nicojeske** [stephanstapel/ZUGFeRD-csharp#246]
Hi,

I am currently migrating to XRechnung 3.0.1 to comply with the latest standards. We previously specified transport costs at the document level using `InvoiceDescriptor.AddTradeAllowanceCharge`.

**Issue Encountered:**

In the current implementation, the `BasisAmount` is automatically generated for every `TradeAllowanceCharge`. However, with the introduction of XRechnung 3.0.1, the business rule PEPPOL-EN16931-R042 mandates that alongside specifying a `BasisAmount` (BT-100), we must also specify the charge percentage (BT-101). Specifying the charge percentage does not seem to be currently possible at all. As the `BasisAmount` is always set we can also not just set the `ActualAmount` without the `BasisAmount` being written . The issue also extends to document-level allowances and invoice line allowances/charges.

**Current XML Snippet:**
```xml
<ram:SpecifiedTradeAllowanceCharge>
  <ram:ChargeIndicator>
    <udt:Indicator>true</udt:Indicator>
  </ram:ChargeIndicator>
  <ram:BasisAmount>56.76</ram:BasisAmount>
  <!-- Other fields -->
</ram:SpecifiedTradeAllowanceCharge>
```

**Target XML Structure (To Meet XRechnung 3.0.1 Requirements):**
```xml
<ram:SpecifiedTradeAllowanceCharge>
    <ram:ChargeIndicator>
        <udt:Indicator>true</udt:Indicator>
    </ram:ChargeIndicator>
    <ram:ActualAmount>25.00</ram:ActualAmount>
    <ram:Reason>Lieferpauschale</ram:Reason>
    <ram:CategoryTradeTax>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:CategoryCode>S</ram:CategoryCode>
        <ram:RateApplicablePercent>19.00</ram:RateApplicablePercent>
    </ram:CategoryTradeTax>
</ram:SpecifiedTradeAllowanceCharge>
```
Also refer to `01.21a-INVOICE_uncefact.xml` from the [XRechnung test suite](https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/business-cases/standard/01.21a-INVOICE_uncefact.xml)

**Comment by stephanstapel** [comment]
Hi @nicojeske ,
thanks for the analysis. I understand that this percentage should be calculated automatically based on BasisAmount and ActualAmount value. Do you share this understanding?

**Comment by nicojeske** [comment]
The XRechnung specification does not explicitly say that, but calculating the percentage automatically as a default sounds reasonable to me, as long as it is still possible to manually set the value if needed.

Additionally, I think that `BasisAmount` should be made optional, as that allows modeling flat charges like transportation costs or fixed discounts.

To summarize:
- if `BasisAmount` is set, the system should either calculate the percentage autonomously or allow the user to specify it.
- If `BasisAmount` is NOT set, the system should omit both `BasisAmount` and `CalculationPercent` (name according to the documentation of ZUGFeRD v2.2) from the XML, relying only on the `ActualAmount`

**Comment by stephanstapel** [comment]
Can you test the code from this branch:
https://github.com/stephanstapel/ZUGFeRD-csharp/tree/topic-tradeallowancecharge

Changes are breaking, thus it would be good to verify the changes properly before releasing a new major version.

**Comment by stephanstapel** [comment]
merged into master
