### ISSUE TITLE
PEPPOL Link is dead

### ISSUE THREAD

**Issue by sk2andy** [stephanstapel/ZUGFeRD-csharp#247]
The link in the readme.md is dead:
https://docs.peppol.eu/edelivery/policies/PEPPOL-EDN-Policy-for-use-of-identifiers-4.1.0-2020-03-11.pdf

it returns a 404 and I am not able to find it anywhere (I am new to the whole topic)

**Comment by stephanstapel** [comment]
thanks.
https://docs.peppol.eu/edelivery/policies/PEPPOL-EDN-Policy-for-use-of-identifiers-4.2.0-2023-06-19.pdf
changed :)
