### ISSUE TITLE
ZUGFeRD v1 Reader Issue?

### ISSUE THREAD

**Issue by landrix** [stephanstapel/ZUGFeRD-csharp#249]
Why is ContractReferencedDocument read twice?

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/483a222a39645047803af385c150779ae5b6cfaf/ZUGFeRD/InvoiceDescriptor1Reader.cs#L366

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/483a222a39645047803af385c150779ae5b6cfaf/ZUGFeRD/InvoiceDescriptor1Reader.cs#L387

**Comment by stephanstapel** [comment]
That's a bug, thanks for finding it!
