### ISSUE TITLE
udt:DateTimeString with format="610" throws UnsupportedException at _nodeAsDateTime()

### ISSUE THREAD

**Issue by springy76** [stephanstapel/ZUGFeRD-csharp#25]
I don't know how to interpret whether the invoice xml is ZUGFeRD 1.0 or 2.0

**Comment by swsch** [comment]
I'm not sure what the comment has to do with the issue header, but the root element tells you the version:

```
<rsm:CrossIndustryDocument ...>
```
is the root element of v1, while v2 uses
```
<rsm:CrossIndustryInvoice ... >
```

**Comment by springy76** [comment]
With the comment I wanted to tell that I'm aware that your component may not be ready for 2.0 but I can't tell if the problem is 2.0 related or not.

**Comment by stephanstapel** [comment]
I published an updated version of the nuget package here:
https://www.nuget.org/packages/ZUGFeRD-csharp/

feedback welcome!

**Comment by springy76** [comment]
I'll give it a try tomorrow. Looking at the commits I expect no exceptions anymore. But I'm unsure if DateTime is a good representation at all.

IMHO 102 means a 24h period, 610 a 28..31 day period, 616 a 7 (5) days period and the 19 digit ISO 8601 format a very concrete 1s/1m/1h period. But I might be wrong since I only took a quick look on this ZUGFerD thing because for now I only need the invoice date and total amount.
