### ISSUE TITLE
X-Rechnung 3.1 UBL for Deutsche Bahn - gross unit price decimals

### ISSUE THREAD

**Issue by stephanstapel** [stephanstapel/ZUGFeRD-csharp#255]
broken down from #254, submitted by @goedo

InvoiceDescriptor22Writer.cs, 268
```csharp

                        //_writeOptionalAmount(Writer, "ram:ChargeAmount", tradeLineItem.GrossUnitPrice, 4); 
                        _writeOptionalAmount(Writer, "ram:ChargeAmount", tradeLineItem.GrossUnitPrice, 2); //roger
```

**Comment by stephanstapel** [comment]
rounding rules from EN16931
https://github.com/stephanstapel/ZUGFeRD-csharp/issues/131

**Comment by goedo** [comment]
I enhanced this. (#258 same change)
Even when 
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/20025525/0b060196-254a-47e6-bd25-83457f2f8cff)
this refers to the internal calulcation, IMHO, but the put value should be round. So:

                        //_writeOptionalAmount(Writer, "ram:ChargeAmount", tradeLineItem.GrossUnitPrice, 4); //roger
                        _writeOptionalAmount(Writer, "ram:ChargeAmount", tradeLineItem.GrossUnitPrice, 2); //roger

and I changed _writeOptionalAmount:

                //roger
                if (numDecimals == 2)
                {
                    value = System.Math.Round(value.Value, 2, MidpointRounding.AwayFromZero); 
                }
                //!roger
                writer.WriteValue(_formatDecimal(value.Value, numDecimals));
