### ISSUE TITLE
X-Rechnung 3.1 UBL for Deutsche Bahn - line item gross unit price

### ISSUE THREAD

**Issue by stephanstapel** [stephanstapel/ZUGFeRD-csharp#256]
broken down from #254, submitted by @goedo

InvoiceDescriptor22Writer.cs, 263
```csharp
                   // BT-148                 
                   if (tradeLineItem.GrossUnitPrice.HasValue || (tradeLineItem.GetTradeAllowanceCharges().Count > 0)
                        && !tradeLineItem.NetUnitPrice.HasValue // roger
```

**Comment by stephanstapel** [comment]
@goeko: can you please describe why this needs to be checked?

**Comment by goedo** [comment]
Close the issue please.
I think it was because messing with data during tests. I'll keep the line as comment to remember the situation.
