### ISSUE TITLE
X-Rechnung 3.1 UBL for Deutsche Bahn - tax rounding

### ISSUE THREAD

**Issue by stephanstapel** [stephanstapel/ZUGFeRD-csharp#262]
broken down from #254, submitted by @goedo

Tax.cs
```csharp
  return System.Math.Round(0.01m * this.Percent * this.BasisAmount, 2, MidpointRounding.AwayFromZero);
```

**Comment by stephanstapel** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.midpointrounding?view=net-8.0

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/0fdf7a75-b640-4ab4-93bc-f4adfc533842)

https://de.wikipedia.org/wiki/Rundung

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/b9daa891-db4b-47f2-8ed8-f10cc8fca8e8)

**Comment by stephanstapel** [comment]
rounding rules from EN16931
https://github.com/stephanstapel/ZUGFeRD-csharp/issues/131

**Comment by goedo** [comment]
I'm still not sure if keeping

**return 0.01m * this.Percent * this.BasisAmount;**

could be better (in other places, I do the rounding).

Still not know how to fix

![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/20025525/6a8b86f0-890b-45c6-aa12-ca1606142f90)

Could be related...

**Comment by stephanstapel** [comment]
This is the only piece of code where things are calculated. Fixed this.
