### ISSUE TITLE
XML cardinality not correctly mapped

### ISSUE THREAD

**Issue by tipa** [stephanstapel/ZUGFeRD-csharp#264]
My goal is to create a Factur-X (1.0.06) xml that passes validation without error or warnings (at the moment I use https://erechnungsvalidator.service-bw.de/)

I had several cases where the cardinality of the schema is not correctly mapped in this library. For example, the `Buyer city` should be optional, however this library always writes it (as an empty node `<ram:CityName />`), even if left empty (`null`)

![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2863198/eec593f5-e8f2-4fc9-847a-06584fa42e50)

This causes a warning in the validator mentioned above:
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2863198/a572a3ad-399b-419c-bac2-d3fd2db473c0)

I found more of these cases yesterday, if you consider fixing it, I can list them here as I come across them

**Comment by stephanstapel** [comment]
I'd be more than happy if you could list all the cases that you found, especially if you add screenshots like above. If possible, it would be great to get tickets per case so we can easier reference the fix.

**Comment by stephanstapel** [comment]
From XRechnung 3.01 (https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/documentation/xRechnung/XRechnung%203.0.1/XRechnung-v3.0.1.pdf):

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/9c104a6c-7954-42fb-9f54-33812be4a53a)

BT-51 is buyer address line 2 whereas buyer city BT-52.

**Comment by tipa** [comment]
In the Factur-X / ZUGFeRD 2.2 specification, both are optional:
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2863198/d2405ebb-bfae-4132-8efa-84ba59c96477)

It might not be optional for XRechnung (but correct me if I'm wrong, I am still trying to wrap my head around all those definitions)

**Comment by goedo** [comment]
Hi all,
ZufFerd, Xrechnung and PEPPOL are still fighting for prevalence, it seems.
BT-52 is an option value, IMHO - but:
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/20025525/66086749-50ab-4ab8-9bc8-5d4dcdbb1a22)
Of course, avoiding the empty xml entries (in the few code lines which actually do output) could be done; but this could lead to situations in which exactly this (the empty entry) would be required (I don't know about even one, but I'm not that expert).
I did not find a overall rule for this topic...
So possibly performing some tests (modifying writer.WriteElementString to not output if value is empty) could be an overall fix trial...

**Comment by stephanstapel** [comment]
Thanks, @goedo.

Turning this:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/15926386-af6c-45f6-97c0-00fc84b641ff)

into this:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/93d6123f-3fe8-4ee2-a62d-9dd991880f78)

would be easy. Maybe this is the only thing we can do here so far to escape the battle of standards. Any thoughts?

**Comment by goedo** [comment]
Hi @stephanstapel 
This is - of course - the solution for THIS item and would be easy.
What I'm not sure of is, if we could change the writer behaviour like the optionalwriter behaviour - so principally not outputting anything empty.
Here, as I said, I lack the overall knowlege if some empty ram's may be mandatory. It sound useful trying changing the central behaviour and perform some validations (as a trial and error approach). For my part , I'll do these test... effort is minimal...

**Comment by tipa** [comment]
> Turning this:
> 
> ![grafik](https://private-user-images.githubusercontent.com/2912080/328766862-15926386-af6c-45f6-97c0-00fc84b641ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM3MzYsIm5iZiI6MTcxNjM2MzQzNiwicGF0aCI6Ii8yOTEyMDgwLzMyODc2Njg2Mi0xNTkyNjM4Ni1hZjZjLTQ1ZjYtOTdjMC0wMGZjODRiNjQxZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDczNzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUzZWY5MjFkYjU5ZGM1YjEzZjUzYmViNzU4NWUzY2Y2MWYyMGNlZDdhZjZjMTBjMjUxMGMzODNlYWViZjg0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6WP8iauUVv1kD6VjqrT8A-ggVGuJDGEvSmtvono-K7Y)
> 
> into this:
> 
> ![grafik](https://private-user-images.githubusercontent.com/2912080/328766948-93d6123f-3fe8-4ee2-a62d-9dd991880f78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM3MzYsIm5iZiI6MTcxNjM2MzQzNiwicGF0aCI6Ii8yOTEyMDgwLzMyODc2Njk0OC05M2Q2MTIzZi0zZmU4LTRlZTItYTYyZC05ZGQ5OTE4ODBmNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDczNzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFlNGE0MjJjN2M1YTg1ZWVmNDZmZTkxMzQzODRhNTY3MmI2YzNiYjQ4ZDk2MTY5ZmQ5MzVlMzkyOTFjNGE4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-7RzShA17yxi1bqHnNsyNT2FI9z84UDWnXvzPNSyfQs)

I would appreciate such a change.



> I'd be more than happy if you could list all the cases that you found, especially if you add screenshots like above. If possible, it would be great to get tickets per case so we can easier reference the fix.

I've also seen this problem with these other address fields:
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2863198/5955f0c2-ff49-4831-81fa-a13c05029cf5)

`PostcodeCode`, `LineOne` & `LineTwo` seem to be optional, but they're always written with this library (even when the properties are empty/null).
On the other hand, `LineThree` has a cardinality of `1..1`, but is not always written by this library. However, I believe this might be a typo/mistake in the specification, because it doesn't make much sense to have  `LineOne` and `LineTwo` optional, while `LineThree` isn't. Also, further down in the specification, the cardinality is specified as `0..1`:
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2863198/fc717d54-b63d-45f4-828f-036e854bf213)


@stephanstapel  I can create separate issues for all of those if you prefer, but I believe they are basically all about the same thing
