### ISSUE TITLE
X-Rechnung 3.0.1 UBL warnings

### ISSUE THREAD

**Issue by goedo** [stephanstapel/ZUGFeRD-csharp#268]
The current code in InvoiceDescriptor22Writer.cs.causes warnings on KOSIT-validator:
- Item net price MUST equal (Gross price - Allowance amount) when gross price is provided.
This may be explained here:
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/20025525/dc2e86a1-a7f4-4f2a-acfa-cf68a8b0c43c)
Solution for my (19!) real life test cases (I'm not so familiar with the Profile.-tactic):

                    // BT-148
                    if (tradeLineItem.GrossUnitPrice.HasValue && (tradeLineItem.GetTradeAllowanceCharges().Count > 0) //roger
                    //if (tradeLineItem.GrossUnitPrice.HasValue || (tradeLineItem.GetTradeAllowanceCharges().Count > 0)

A couple of lines below:

                            #region ChargePercentage
                            if (tradeAllowanceCharge.ChargePercentage.HasValue)
                            {
                                //Writer.WriteStartElement("ram:CalculationPercent", profile: Profile.Extended | Profile.XRechnung); //roger
                                Writer.WriteStartElement("ram:CalculationPercent", profile: Profile.Extended); //roger not allowed EN16931 (CII) (val-sch.1)
                                Writer.WriteValue(_formatDecimal(tradeAllowanceCharge.ChargePercentage.Value, 2));
                                Writer.WriteEndElement();
                            }
                            #endregion
(this region exists two times!)
avoids
![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/20025525/78d52188-4e5b-47f9-9a33-5db73b2d34cc)

I tried to uses your Profile. - tactic here,.. :-)

**Comment by stephanstapel** [comment]
So many things changed in the meantime in the component. I'll close this one. Please open it again if the problems persist.
