### ISSUE TITLE
Unterschied v2 und v21+ erkennen

### ISSUE THREAD

**Issue by landrix** [stephanstapel/ZUGFeRD-csharp#271]
Wie kann ich denn mit dem Profil

"urn:cen.eu:EN16931:2017", // Profil EN 16931 (COMFORT)

hier 

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/540f8b733177c7ab11c2b28aa6cb03d4ef2e9d66/ZUGFeRD/InvoiceDescriptor.cs#L411

beim Laden einer ZUGFeRD 2.0 und 2.1 bzw 2.2 die Version 2.0 erkennen?

Wenn ich mit einer v2.0 in die Load Funktion gehe, wird erst auf v2.2 geprüft und die erkennt das Profil ja ebenfalls.

**Comment by stephanstapel** [comment]
Ja, guter Punkt. Das ram:ID-Element schien mir das beste Unterscheidungsmerkmal zu sein. Wie erkennst Du denn, dass es sich bei der Datei, die Du laden willst, um eine 2.0-Datei handelt? Bzw. kommt es beim Laden mit dem 2.2-Reader zu einer Fehlermeldung?

**Comment by landrix** [comment]
Ich hab keinen Anhaltspunkt ob 2.0 oder 2.2, außer ich weiß es definitiv vom Übermittler. Ob ein Fehler kommt, kann ich Dir noch nicht sagen, ich portiere deine Bibliothek gerade https://github.com/LandrixSoftware/ZUGFeRD-for-Delphi und bin noch am Umsetzen der Tests und finden der letzten Macken. Jedenfalls komme ich an jeder Ecke durch und hinterfrage alles.
Vielleicht kannst du den Issue hier noch etwas offen lassen, bis ich das geklärt habe oder jemand eine Idee hat.
