### ISSUE TITLE
Doppelte Ausgabe von ChargePercentage

### ISSUE THREAD

**Issue by landrix** [stephanstapel/ZUGFeRD-csharp#272]
bei InvoiceDescriptor22Writer wird

ChargePercentage

doppelt ausgegeben, ist das korrekt?

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/540f8b733177c7ab11c2b28aa6cb03d4ef2e9d66/ZUGFeRD/InvoiceDescriptor22Writer.cs#L279

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/540f8b733177c7ab11c2b28aa6cb03d4ef2e9d66/ZUGFeRD/InvoiceDescriptor22Writer.cs#L303

**Comment by stephanstapel** [comment]
nein, das ist ein Merge-Fehler. Vielen Dank!
