### ISSUE TITLE
TradeAllowenceCharge not read from xml file

### ISSUE THREAD

**Issue by ursaciuc-adrian** [stephanstapel/ZUGFeRD-csharp#276]
Hello!

I am trying to read a CII xml file using the InvoiceDescriptor.

I am encountering some issues while I try to get the discount applied to the line item. The XML file has the respective field, but everything is empty when I try to get it out from TradeLineItems

<ram:SpecifiedLineTradeAgreement>
    <ram:GrossPriceProductTradePrice>
        <ram:ChargeAmount currencyID="RON">492.65</ram:ChargeAmount>

        <ram:AppliedTradeAllowanceCharge>
            <ram:ChargeIndicator>
                <udt:Indicator>true</udt:Indicator>
            </ram:ChargeIndicator>
            <ram:CalculationPercent>5.0</ram:CalculationPercent>
        </ram:AppliedTradeAllowanceCharge>
    </ram:GrossPriceProductTradePrice>
</ram:SpecifiedLineTradeAgreement>

![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/21957490/13baf855-e4b8-466e-8f52-f9bba2abc367)

Looks like there is no support for percent. Is is possible to add that or is there any workaround for this?

**Comment by stephanstapel** [comment]
Thanks for sending this bug.
Can you share your image file please? If you want to keep it confidential, it'd be great if you would send it to me using firstname.lastname@web.de

**Comment by stephanstapel** [comment]
Is there anything I can do, @ursaciuc-adrian ?
