### ISSUE TITLE
Question about the XInvoice

### ISSUE THREAD

**Issue by IngoManthey** [stephanstapel/ZUGFeRD-csharp#277]
When I test the demo data from the xInvoice directory for plausibility, I always get the following error message:
Recognized document type:
unknown

What is wrong there??

**Comment by stephanstapel** [comment]
this test runs successfully, at least against the current master branch:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/18b19ef01cb5848e80afc1058a5584f0cf8ffc1d/ZUGFeRD-Test/ZUGFeRD22Tests.cs#L40

**Comment by IngoManthey** [comment]
@stephanstapel 
Unfortunately, I expressed myself incorrectly. I validated the files xrechnung with trade line settlement data.xml and xrechnung with trade line settlement empty.xml on the page https://xrechnung.rib.de/. There I was shown the error:
Recognized document type:
unknown
.

**Comment by stephanstapel** [comment]
these are official demo files:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/18b19ef01cb5848e80afc1058a5584f0cf8ffc1d/demodata/xRechnung/xrechnung%20with%20trade%20line%20settlement%20data.xml#L4

I guess I can't do much about this.
Maybe this validator can only handle current formats, you might try:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/documentation/xRechnung/XRechnung%203.0.1/xrechnung-3.0.1-testsuite-2023-09-22.zip
