### ISSUE TITLE
Missing ISO Codes

### ISSUE THREAD

**Issue by PunishedSnakePr** [stephanstapel/ZUGFeRD-csharp#278]
How to use ISO codes (e.g. QuantityCodes) that are currently missing? As an example there is no GRM (gram) in version 12.8. Will there be a way to provide a simple string in such cases (e.g. for AddTradeLineItem)?

**Comment by stephanstapel** [comment]
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/18b19ef01cb5848e80afc1058a5584f0cf8ffc1d/ZUGFeRD/QuantityCodes.cs#L348

**Comment by PunishedSnakePr** [comment]
I've seen that and I don't mean GRM specifically but what can I do if a code is generally missing in an Enum? I mean the EN16931 code list is humongous and not all codes are covered by enums. So, is there a way to bypass enums by simply providing codes as strings?

**Comment by PunishedSnakePr** [comment]
Ok, thanks for the rapid answers. So, I most likely going to open a pull request with stuff I am missing.
