### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by IngoManthey** [stephanstapel/ZUGFeRD-csharp#279]
I have created my X-invoice and unfortunately I get a warning and cannot do anything with it.

When I validate my invoice with https://xrechnung.rib.de/ I get the following warning:
PEPPOL-EN16931-R001 warning Business process MUST be provided.
Path: /rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext[1]

Can someone help me here and write what is missing?

**Comment by stephanstapel** [comment]
This one is a good source:
https://blog.seeburger.com/de/xrechnung-version-3-0-1-gueltig-ab-01-februar-2024/

![image](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/ff3c1d2f-ad4e-48e3-95c6-505f706599eb)
