### ISSUE TITLE
What is the ram:Information tag about?

### ISSUE THREAD

**Issue by tipa** [stephanstapel/ZUGFeRD-csharp#280]
When using `SetPaymentMeans()`, the resulting XML contains an empty `ram:Information` tag

```
      <ram:SpecifiedTradeSettlementPaymentMeans>
        <ram:TypeCode>30</ram:TypeCode>
        <ram:Information />
        <ram:PayeePartyCreditorFinancialAccount>
          <ram:IBANID>...</ram:IBANID>
        </ram:PayeePartyCreditorFinancialAccount>
      </ram:SpecifiedTradeSettlementPaymentMeans>
```

What is this tag about? I didn't see it mentioned in the ZUGFeRD specification.
In the code, the property has the same comment as `TypeCode`:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/920d263043aa3a2c4f1acb6176009404b09a6c62/ZUGFeRD/PaymentMeans.cs#L28-L36

**Comment by stephanstapel** [comment]
You can find it e.g. here:

![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/2912080/c6773cfd-f60c-4f11-aaee-c5b84319032d)

but indeed, no empty entry should be written. I will take care of that.
