### ISSUE TITLE
GEFEG.FX Check mit Zugpferd 2.0 invoiced Error

### ISSUE THREAD

**Issue by CreepyThing** [stephanstapel/ZUGFeRD-csharp#288]
**[GER]**
Hallo, evtl. haben Sie einen Hinweis für mich,
bin hier leider etwas überfragt...
Validiert habe ich überigens gegen den Standard: **EN16931_UBL_Invoice;17.05.2021;Check**

ich hab eine ZUGFeRD Test Rechnung und validiere mit Hilfe von https://portal3.gefeg.com/.

Hier bekomme ich dann dann folgende **Rückmeldung:**
_No declaration found for element 'rsm:CrossIndustryDocument' [Zeile 0002]_

**Orginal Zeile:**
_0002 <rsm:CrossIndustryDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rsm="urn:ferd:CrossIndustryDocument:invoice:1p0" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:15">_

[ZUGFeRD-invoice.zip](https://github.com/user-attachments/files/16029744/ZUGFeRD-invoice.zip)

vielen Dank im Vorraus.

**[ENG]**
Hi,
maybe you've got a hint for me, cause i'm not sure what to do...
I Validate my ZUGFeRD Test Invoice with this website https://portal3.gefeg.com/,
with the Standard **EN16931_UBL_Invoice;17.05.2021;Check**

My **Response** is;
_No declaration found for element 'rsm:CrossIndustryDocument' [Zeile 0002]_

**Orginal Zeile:**
_0002 <rsm:CrossIndustryDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rsm="urn:ferd:CrossIndustryDocument:invoice:1p0" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:15">_

[ZUGFeRD-invoice.zip](https://github.com/user-attachments/files/16029744/ZUGFeRD-invoice.zip)

thanks in advance

**Comment by stephanstapel** [comment]
I get the same response even with the files from the official documentation package

**Comment by CreepyThing** [comment]
thanks a lot, 
seems like the validator won't work properly,
i will contakt the GEFEG guys

**Comment by stephanstapel** [comment]
Did you find out why the validation fails? Is there something to fix in the library?
