### ISSUE TITLE
minor bug in demodata/ZUGFeRD_1p0_COMFORT_Einfach_Original.xml

### ISSUE THREAD

**Issue by spacetrack** [stephanstapel/ZUGFeRD-csharp#29]
line 51 ...

`<ram:ID>urn:ferd:CrossIndustryDocument:invoice:1p0:E</ram:ID>`

... should be "...:1p0:comfort":

`<ram:ID>urn:ferd:CrossIndustryDocument:invoice:1p0:comfort</ram:ID>`

**Comment by stephanstapel** [comment]
these documents originate from the official ZUGFeRD documentation package. Looks I never updated them after their corrections. Will do asap.
In the meantime, feel free to download the demo PDFs here:
https://www.ferd-net.de/downloads/zugferd-1.0/index.html
