### ISSUE TITLE
Is this correct with TradingBusinessName?

### ISSUE THREAD

**Issue by xafero** [stephanstapel/ZUGFeRD-csharp#290]
Hi, thanks for your library, but I got an invoice with a name, it gets read, but not written out again. So my input and my output X-Rechnung are not the same :-(

invoice.Buyer.SpecifiedLegalOrganization.TradingBusinessName = "Does not get written?";

I'm trying to save the invoice with X-Rechnung 3.0.1 (so Profile.XRechnung) and I guess the culprit is here:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/InvoiceDescriptor22Writer.cs#L1237

Is that behaviour really correct? Because in the case of Buyer, it is limited to Comfort and Extended, but in case of Seller and Payee not. Seems weird to me, but of course, the invoice I got could be wrong in this specific instance, so I'm asking.

**Comment by stephanstapel** [comment]
can you please test if the new version works as desired?

**Comment by xafero** [comment]
Yes, thanks
