### ISSUE TITLE
How to fill line: order line number & account assignment information

### ISSUE THREAD

**Issue by MarvinKlein1508** [stephanstapel/ZUGFeRD-csharp#291]
How can i fill these fields? (BT-132 & BT-133)
![grafik](https://github.com/stephanstapel/ZUGFeRD-csharp/assets/32510006/6e896731-5768-435d-b84d-fa15f09ed747)

**Comment by stephanstapel** [comment]
I've added some documentation to guide you

**Comment by stephanstapel** [comment]
If you have a real invoice you can share as a screenshot (of course with sensible information blurred), I'd be more than happy to share this along with sample code on the documentation page.
