### ISSUE TITLE
Support for ZUGFeRD 2.1

### ISSUE THREAD

**Issue by euphilein** [stephanstapel/ZUGFeRD-csharp#31]
Hello,

ZUGFeRD 2.1 is out since 24.03.2020.
Actually it is not supported by ZUGFeRD-csharp and InvoiceDescriptor.Load(zugferdFile); returns an empty descriptor with Type = Unknown.
Do you have any plans to support this ZUGFeRD Version?

**Comment by stephan-nowecor** [comment]
Hi euphilein,

Sorry to not provide support for something that has been published 3 days ago :)
Of course I intend to support this version, too. On the other side, if you like, a pull request is welcome, too.
If you have a sample invoice you could provide I'd been looking forward to this, too.

**Comment by stephanstapel** [comment]
Hi euphilein,

Sorry to not provide support for something that has been published 3 days ago :)
Of course I intend to support this version, too. On the other side, if you like, a pull request is welcome, too.
If you have a sample invoice you could provide I'd been looking forward to this, too.

**Comment by euphilein** [comment]
Sorry if my comment sounds like negative critism.
I understand of course that the version is brand new and don't expect an immidiate solution.
My intention was just to track the support for 2.1 in some way, don't know if the issue is the right way...

Well, right now it seems that I won't have enough time in next few weeks to provide a pull request, but we'll see.

I cannot share the example invoices i have because of privacy reasons, but as far as i know ZUGFeRD always provides examples in their info packages. At least there are some in the 2.1 version when you download it.

**Comment by cGiesen** [comment]
Dear Stephan,

I play arround and try to learn how to update the code for 2.1
But I can't manage that.

Is there any timeline for 2.1?

Very best regards
Carsten

**Comment by stephanstapel** [comment]
Hi,

I have got very early support in my working copy, at least for detecting 1.x and 2.x in order to assign the correct readers.
However, I am still looking for a sponsor for implementing 2.x support.

Cheers,

Stephan

**Comment by cGiesen** [comment]
Hi,

I start understanding how this XML stuff works. Thats new for me. I got the first 2.1 results.

I can assist. But I can't sponsor. Sorry

My first Idea:
In InvoiceDescriptorReader I check for the version an than set the Nodenames an the Namesspace.
My first view show, there are only new names.

1.0 is not importend from my point of view

My nativ language is german. Perhaps we communicate in german. It's easyer for me ;)

cu
Carsten

**Comment by cGiesen** [comment]
Hi,

merde, there are some changes in the structure forposition data :(
Yust to change some header is not enaugh

CU

**Comment by stephanstapel** [comment]
switching to German.
Ich habe gerade die Struktur für die Unterstützung von ZUGFeRD 2.x gepushed:
https://github.com/stephanstapel/ZUGFeRD-csharp/commit/359be00620b125e2191f86d11c3634e87407a18f

Die beiden zentralen Klassen sind:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/InvoiceDescriptor2Reader.cs
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/InvoiceDescriptor2Writer.cs

Schaue es Dir gerne an. In den meisten Teilen sollte es ein Ändern der Tagnamen tun. Wenn es Strukturänderungen gibt, kannst Du Dich gerne melden, das können wir uns gerne zusammen ansehen (Vorschlag: lass uns dafür jeweils eigene Issues aufmachen, damit wir den Überblick nicht verlieren).

Würde mich freuen, wenn es in dem Modus klappen würde und freue mich auf pull requests!

**Comment by cGiesen** [comment]
Oups dann war ich wohl zu schnell ;)
Lesend bin ich fast fertig, mal sehen, wie ich das in Deine Technik überführt bekomme.

Wenn ich das richtig verstehe, Soll Reader1 die 'alte' Technik sein und reader2 soll 2.1 abbilden.
Mein Weg war anders, bis ich gemerkt habe, dass die Positionen eine eigene Struktur haben.

Ich werde also diesem Weg folgen.

**Comment by stephanstapel** [comment]
Ja, genau so ist es gedacht! Einige Teile hatte ich schon umgesetzt, musst mal schauen, wie Du das übereinanderbekommst.

**Comment by stephanstapel** [comment]
ZUGFeRD 2.x support now on it's way. Feel free to test and feedback! Will cose this issue here now.
