### ISSUE TITLE
UBL: UnitCode aus BilledQuantity auslesen

### ISSUE THREAD

**Issue by stephanstapel** [stephanstapel/ZUGFeRD-csharp#317]
https://github.com/stephanstapel/ZUGFeRD-csharp/commit/844c402679560c745d32d9230fb6f5cd92ec3780

**Comment by landrix** [comment]
UBL Reader arbeitet korrekt, das hab ich schon geprüft

**Comment by stephanstapel** [comment]
looks good:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/963989bf1c0e882ccaa3a56e15c5229486a4f2e8/ZUGFeRD/InvoiceDescriptor22UblReader.cs#L440
