### ISSUE TITLE
Publish nuget package for .NET Core/Standard

### ISSUE THREAD

**Issue by effyteva** [stephanstapel/ZUGFeRD-csharp#32]
When referencing this project from a .NET Core 3.1 project, the following warning is shown:

warning NU1701: Package 'ZUGFeRD-csharp 2.10.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

It seems that the project (or the NuGet build) is somehow still configured as .NET framework instead of .NET Standard/Core.

Any chance this could be sorted out?

Thanks!

**Comment by stephanstapel** [comment]
I am not really used to nuget's requirements concerning compatibility. The assembly is compiled as .net standard 2.0. In version 2.11, I followed the nuget structuring guidelines (nothing else was changed).

Can you please check version 2.11 that I just published?

**Comment by effyteva** [comment]
Yes, that fixed those warnings.
Thank you for taking care of this issue so quickly!
