### ISSUE TITLE
BT-41 to BT-43 missing when using SetSellerContact

### ISSUE THREAD

**Issue by Tsumiki-Chan** [stephanstapel/ZUGFeRD-csharp#320]
Hi,

we're currently using the methods "SetSellerContact" and "SetBuyerContact". However upon viewing the XML BT41 to BT-43 and BT-56 to BT-58 are missing.

Code
```csharp
InvoiceDescriptor invoice = InvoiceDescriptor.CreateInvoice(m_invoice.Nummer, m_invoice.Rechnungsdatum, CurrencyCodes.EUR);
invoice.Type = InvoiceType.Invoice;
invoice.SetSeller(CompanySettings["Name"], CompanySettings["Address_PLZ"], CompanySettings["Address_City"], CompanySettings["Address_Street"], CountryCodes.DE);
invoice.SetSellerContact(name: CompanySettings["SellerContact"],
	orgunit: CompanySettings["ContactName"],
	emailAddress: CompanySettings["ContactMail"],
	phoneno: CompanySettings["Phone"],
	faxno: CompanySettings["Fax"]
);
invoice.SetBuyer(m_invoice.Kostenträger.Name, m_invoice.Kostenträger.Adresse.PLZ,m_invoice.Kostenträger.Adresse.Ort, m_invoice.Kostenträger.Adresse.Strasse, countryCode, legalOrganization: new LegalOrganization(GlobalIDSchemeIdentifiers.CompanyNumber));
if (!string.IsNullOrWhiteSpace(m_invoice.Kostenträger.Kontakt))
{
	invoice.SetBuyerContact(m_invoice.Kostenträger.Kontakt);
}
/**
 * ... Buch of other stuff
**/

byte[] zugferdXml = Array.Empty<byte>();
using (var invoiceMemoryStream = new MemoryStream())
{
	invoice.Save(invoiceMemoryStream, ZUGFeRDVersion.Version22, s2industries.ZUGFeRD.Profile.Comfort);
	zugferdXml = invoiceMemoryStream.ToArray();
}
```

However, the XML is missing those informations alltogether

```xml
<ram:SellerTradeParty>
        <ram:Name>[Redacted for Privacy]</ram:Name>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>[Redacted for Privacy]</ram:PostcodeCode>
          <ram:LineOne>[Redacted for Privacy]</ram:LineOne>
          <ram:CityName>[Redacted for Privacy]</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:URIUniversalCommunication>
          <ram:URIID schemeID="EM">[Redacted for Privacy]</ram:URIID>
        </ram:URIUniversalCommunication>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">[Redacted for Privacy]</ram:ID>
        </ram:SpecifiedTaxRegistration>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">[Redacted for Privacy]</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:SellerTradeParty>
      <ram:BuyerTradeParty>
        <ram:Name>[Redacted for Privacy]</ram:Name>
        <ram:SpecifiedLegalOrganization>
          <ram:ID />
        </ram:SpecifiedLegalOrganization>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>[Redacted for Privacy]</ram:PostcodeCode>
          <ram:LineOne>[Redacted for Privacy]</ram:LineOne>
          <ram:CityName>[Redacted for Privacy]</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
      </ram:BuyerTradeParty>
```

Am i missing something here?

**Comment by stephanstapel** [comment]
I added a test case:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/8926fafff3a5fe2a69f87c290fc5329860a204a6/ZUGFeRD-Test/ZUGFeRD22Tests.cs#L1984

which works just fine. 
Imho the code is identical to yours. Can you verify?

**Comment by christian-fischer-trinidat** [comment]
I have found the same problem. I think in the file InvoiceDescriptor22Writer.cs line 1217 the wrong profile is set.
This is (Profile)100, I think it must be (Profile)102 (For Profile Comfort and Extended)

**Comment by stephanstapel** [comment]
@christian-fischer-trinidat : can you share a perma link to the correct line of
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/InvoiceDescriptor22CIIWriter.cs
?

**Comment by christian-fischer-trinidat** [comment]
@stephanstapel : Sorry, I can't do that. It seems to be correct in your file. I found it in the decompiled package of version 13.0.0

![image](https://github.com/user-attachments/assets/d2119e46-4e94-4804-b482-203fe18b3e05)

**Comment by Tsumiki-Chan** [comment]
> I added a test case:
> 
> https://github.com/stephanstapel/ZUGFeRD-csharp/blob/8926fafff3a5fe2a69f87c290fc5329860a204a6/ZUGFeRD-Test/ZUGFeRD22Tests.cs#L1984
> 
> which works just fine. Imho the code is identical to yours. Can you verify?

There doesn't seem to be a relevant difference between our codes except for the Profile (Your codes saves as Extended while mine saves as Comfort).

Just for testing i also tried to save the Invoice with Extended Profile and it worked (aka BT-41 to BT-43 and BT-56 to BG-58 were written. So it seems to be a problem with the comfort configuration

**Comment by stephanstapel** [comment]
> Just for testing i also tried to save the Invoice with Extended Profile and it worked (aka BT-41 to BT-43 and BT-56 to BG-58 were written. So it seems to be a problem with the comfort configuration

I guess it is rather about the version. Do you use the nuget package? Could you try with the current version instead?

**Comment by Tsumiki-Chan** [comment]
> I guess it is rather about the version. Do you use the nuget package? Could you try with the current version instead?

We're currently on the NuGet-Package version 13.0.0 so it should be the latest version

**Comment by stephanstapel** [comment]
I guess we can close the issue as it seems to be fixed in the current version

**Comment by christian-fischer-trinidat** [comment]
@stephanstapel: When is the next release planned?

**Comment by stephanstapel** [comment]
There are quite some breaking changes that I'd like to list in the release notes for the next major version. That is everything that prevents me from releasing :)
