### ISSUE TITLE
X-Rechnung CII: missing qdt namespace

### ISSUE THREAD

**Issue by MelanieVeigl** [stephanstapel/ZUGFeRD-csharp#322]
Hello,
thank you for the great work on this project, I already use it to read zugferd and plan to use it for x-Rechnung cii and ubl.

I attached an example for X-Rechnung CII 2.0 without the qdt namespace. On InvoiceDescriptor.Load I get a XPathException "namesapce 'qdt' is not defined."

I think it should not be an error, if the namespace is not used in xml. 
What is your proposal to handle this error? 

[INVOICE_cii_200.txt](https://github.com/user-attachments/files/16611515/INVOICE_cii_200.txt)

**Comment by stephanstapel** [comment]
good point. Currently, only qdt is supported for reading invoices. 
It would be pretty easy to write this code more abstract:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/7e6f58051890d0d310635c1bcb4503a60a4fa96f/ZUGFeRD/InvoiceDescriptor22CIIReader.cs#L377

i.e. create a function which reads the datetime sub node from a given node regardless if it's qdt or udt. What do you think?

**Comment by MelanieVeigl** [comment]
sounds good. I will create a pull request with the suggested changes.

**Comment by stephanstapel** [comment]
Thanks, go ahead. I might move this into a separate dedicated class like 'UniversalDataTypeParser' later on though.

**Comment by MelanieVeigl** [comment]
Great :), your changes work as expected. Thanks for the quick adjustment. I added tests with #327
