### ISSUE TITLE
TestIndicator should be false if not specified

### ISSUE THREAD

**Issue by MelanieVeigl** [stephanstapel/ZUGFeRD-csharp#323]
The TestIndicator "rsm:CrossIndustryDocument/rsm:SpecifiedExchangedDocumentContext/ram:TestIndicator/udt:Indicator" should be false if it is not specified.

In this context I also can fix the TestIndicator Flag for UBL.

**Comment by stephanstapel** [comment]
Isn't that the case:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/7e6f58051890d0d310635c1bcb4503a60a4fa96f/ZUGFeRD/InvoiceDescriptor.cs#L188

?

**Comment by MelanieVeigl** [comment]
thank you for your quick reply. In the readers, however, the default value in the _nodeAsBool() method for the parameter "defaultValue" is "true". 

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/7e6f58051890d0d310635c1bcb4503a60a4fa96f/ZUGFeRD/InvoiceDescriptor22CIIReader.cs#L54

**Comment by stephanstapel** [comment]
Phew, thanks!
If you have the time, I'm happy for a PR with the default parameter filled with 'false'. Can you do this for all reader versions? Shouldn't be big.
