### ISSUE TITLE
AddAdditionalReferencedDocument only works with ZUGFeRDFormats.CII

### ISSUE THREAD

**Issue by Balin71** [stephanstapel/ZUGFeRD-csharp#329]
Hi,

You can add a document to the InvoiceDescriptor. Saving also works without errors in both formats (UBL, CII). But the document is only inserted into the XML in ZUGFeRDFormats.CII. Is this supposed to be the case or is this a bug? 
I need the document in the UBL version.

desc.Save(stream, ZUGFeRDVersion.Version22, Profile.XRechnung,ZUGFeRDFormats.UBL); > not working
desc.Save(stream, ZUGFeRDVersion.Version22, Profile.XRechnung,ZUGFeRDFormats.CII); > works

Info: The additional document is a PDF file

Best regards,
Steffen

**Comment by stephanstapel** [comment]
UBL is a community driven format. If you need a certain feature, I'm happy to guide you through coding and looking for your PR.
