### ISSUE TITLE
Support for ZUGFeRD 2

### ISSUE THREAD

**Issue by dalton86** [stephanstapel/ZUGFeRD-csharp#33]
Hi,
In Your solution, there are test files from ZUGFeRD 2.0 but Your solution seems to not support it. 
In the description, I see that You have information that the readers are working with standards 1 and 2.
Question do You plan to implement readers for these standards or this is a bug?

**Comment by stephanstapel** [comment]
First step was only to be able to distinguish between version 1 and 2 in order so assign the correct reader.

I am currently implementing the ZUGFeRD 2 reader but am stuck somehow in the process. If you can help, it'd be more than happy to share the current state of code.
