### ISSUE TITLE
AdditionalReferencedDocument - AttachmentBinaryObject

### ISSUE THREAD

**Issue by DasElias** [stephanstapel/ZUGFeRD-csharp#333]
Hi,

two questions regarding the AdditionalReferencedDocument tag.

- When I attach an XML file (`mimeCode` gets mapped to application/xml), I get a Mustang validation error which says essentially that application/xml is not a valid mimeCode. I have tried the XRechnung and the Extended Profile and the issue exists in both. For the extended profile, the standard clearly does not include application/xml as valid MIME type. Is there any workaround how an XML file can be attached; and why is the mapping to application/xml even there, if this seems not to be valid?
- Is there any reason why one can't attach a `AttachmentBinaryObject` when calling `TradeLineItem.AddAdditionalReferencedDocument` even though this seems to be supported by the ZUGFeRD specification?

Kind regards,
Elias

**Comment by stephanstapel** [comment]
* XML is allowed because of the comment in: https://projekte.kosit.org/xrechnung/xrechnung/-/issues/59
Happy to remove it though
* For whatever reason, binary data cannot be attached to AdditionalReferencedDocuments on item level. According to the FacturX 1/ ZUGFeRD 2.2 specification:

![grafik](https://github.com/user-attachments/assets/d27b374d-8150-4f3a-ad08-abab9974f0d0)

**Comment by DasElias** [comment]
Thanks a lot for the quick response. I am not sure about the difference between SpecifiedLineTradeSettlement > AdditionalReferencedDocument vs. SpecifiedLineTradeAgreement > AdditionalReferencedDocument, but it seems that with the latter it is indeed possible to attach binary data on item level. Initially, I was referring to SpecifiedLineTradeAgreement > AdditionalReferencedDocument, hence my confusion since binary data can be attached via this property.

![image](https://github.com/user-attachments/assets/3d0f6936-877d-4573-9674-c5915a0fb6c4)

**Comment by stephanstapel** [comment]
Interesting. I have no idea why ZUGFeRD 2.2 looks so different.
The latest version I can find on gefeg.com (https://portal3.gefeg.com/invoice/tthome/index/617afdc4-623f-44e0-a05b-5b878840e508?page=1&useSelectedItemPosition=true):

ApplicableHeaderTradeAgreement:

![grafik](https://github.com/user-attachments/assets/802952b1-a8d4-4229-ad9c-d53910148a9e)

TradeLineItem:

![grafik](https://github.com/user-attachments/assets/b42efe5a-46e6-4054-b320-61f841e86df9)

which would be in line with the current implementation

**Comment by DasElias** [comment]
If we are both talking about [this link](https://portal3.gefeg.com/projectdata/invoice/deliverables/installed/publishingproject/zugferd%202.0.1%20-%20facturx%201.03/en%2016931%20%E2%80%93%20facturx%201.03%20%E2%80%93%20zugferd%202.0.1%20-%20extended.scm/html/de/021.htm?https://portal3.gefeg.com/projectdata/invoice/deliverables/installed/publishingproject/zugferd%202.0.1%20-%20facturx%201.03/en%2016931%20%E2%80%93%20facturx%201.03%20%E2%80%93%20zugferd%202.0.1%20-%20extended.scm/html/de/0258.htm), then, yes and no. 

It should be noted that the node `AdditionalReferencedDocument` appears not only twice, but three times. The first two occurrences are the ones that you have already mentioned, which reflect the current implementation. However, there is the third occurence in `SpecifiedLineTradeSettlement` which seems to allow to reflect binary attachments on document line level.

![image](https://github.com/user-attachments/assets/2c15f0c7-95d5-4bae-9235-2f8f2fb160ac)

If I were to submit a pull request to map the third node as well, would you have any idea how the library API implementation could be named to avoid confusion with the method that already exists?

**Comment by stephanstapel** [comment]
Can you please check my commit https://github.com/stephanstapel/ZUGFeRD-csharp/commit/1e032bb2866b9b8bdb7850c60170ab7a64a34738? I guess this should write the correct values.

I have no idea how to implement the third occurrence of AdditionalReferencedDocuments and would leave this for later.

Also I have added the overloaded function as suggested. Please let me know if it works for your use case!
