### ISSUE TITLE
Missing ApplicableHeaderTradeDelivery/ShipToTradeParty in Zugferd EN16931

### ISSUE THREAD

**Issue by WernerK61** [stephanstapel/ZUGFeRD-csharp#334]
Hi,

documentation for Zugferd 2.1 says that ApplicableHeaderTradeDelivery/ShipToTradeParty is used in EN16931/Comfort.

If output profile XRechnung is used, then ApplicableHeaderTradeDelivery/ShipToTradeParty is correctly written,
but if EN16931/Comfort is used, then ApplicableHeaderTradeDelivery/ShipToTradeParty is omitted.

(BTW: In  SupplyChainTradeTransaction/IncludedSupplyChainTradeLineItem/SpecifiedLineTradeDelivery/ShipToTradeParty
in Zugferd it should only be written with extended profile)

Is this a bug, or am I missing something,
or is this a similar problem as with DefinedTradeContact, reported in Issue #210 ?

Regards
Werner

**Comment by stephanstapel** [comment]
Yes, this is the expected behaviour. As of ZUGFeRD 2.2, ShipToTradeParty is only written in Extended profile:

![grafik](https://github.com/user-attachments/assets/591f32d1-2f4b-4002-b46a-6dcfde5fe98a)

**Comment by WernerK61** [comment]
Sorry, but: No, it's generally(!) not only for Extended 
As stated above ShipToTradeParty is used in more than one place; according to Zugferd 2.2 docs:

Only on line(!) level at SupplyChainTradeTransaction/IncludedSupplyChainTradeLineItem/SpecifiedLineTradeDelivery/ShipToTradeParty it has to be written only in EXTENDED profile.

But on "global" level at ApplicableHeaderTradeDelivery/ShipToTradeParty it has to be written also in EN16931/Comfort and even BASIC profiles:
![grafik](https://github.com/user-attachments/assets/e94d7ab2-d93f-4f19-a46d-b318dfa3318d)

**Comment by stephanstapel** [comment]
ok, got it. Thanks.
