### ISSUE TITLE
TradelineItem BuyerORderReferencedDocument vom falschen Typ

### ISSUE THREAD

**Issue by landrix** [stephanstapel/ZUGFeRD-csharp#339]
Hallo,

ich denke hier ist etwas generell falsch

tradeLineItem.BuyerOrderReferencedDocument verweist auf das Objekt BuyerOrderReferencedDocument : BaseReferencedDocument
mit den Eigenschaften

public string ID { get; set; }
public DateTime? IssueDateTime { get; set; }

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/fe015c962297412a89700bd4cf3bc5a7141da984/ZUGFeRD/InvoiceDescriptor22CIIWriter.cs#L208

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/fe015c962297412a89700bd4cf3bc5a7141da984/ZUGFeRD/InvoiceDescriptor22CIIReader.cs#L479

Nach Spezifikation hat das aber gar nichts damit zu tun

![image](https://github.com/user-attachments/assets/16b5a4e4-bd12-4198-9164-46aaf476f29d)

Da gibt es nur eine LineID

Soll ich das mal abändern? Soll ein eigener Typ eingeführt werden und wie soll er heißen?

**Comment by landrix** [comment]
Ein Anwender mein Lib benötigt wohl die LineID. Na ich schau mir das mal an.

**Comment by stephanstapel** [comment]
Spannend. Magst Du mal fragen, in welchem Kontext er das anwendet?

**Comment by stephanstapel** [comment]
btw, in ZUGFeRD sieht das noch etwas anders aus:

![image](https://github.com/user-attachments/assets/0c50015e-d36d-478f-b462-8be4b4d6b99e)
![image](https://github.com/user-attachments/assets/3a227c8c-a929-4dd1-8905-9e6a95275304)

**Comment by landrix** [comment]
(Hättest Du mal bitte den Originallink auf die gesamte Spezifikation? Deine View gefällt mir besser, die kenne ich aber nicht)

**Comment by johannespfeiffer** [comment]
@landrix, schau mal hier: https://www.awv-net.de/upload/ferd/zugferd22de.zip im Ordner `DE/Dokumnetation/2. FACTUR-X 1.0.06 Technischer-Anhang.pdf`

**Comment by landrix** [comment]
> Der Grund für die LineId ist folgender:
>  
> Wir erfassen die Zugferd-Daten und leiten diese weiter für eine automatisierte Rechnungskontrolle mit den Daten aus der Bestellung.
> Je mehr Information dafür zur Verfügung steht, desto besser.
> Wenn also auch die Nummer der Bestellposition vorhanden ist, dann kann gezielter auf die Bestelldaten zugegriffen werden.

**Comment by stephanstapel** [comment]
done.
https://github.com/stephanstapel/ZUGFeRD-csharp/commit/20b60be879ed9c4d0cff78b68f26d63ef233d839
