### ISSUE TITLE
Implement 2.1 

### ISSUE THREAD

**Issue by cGiesen** [stephanstapel/ZUGFeRD-csharp#34]
This is the starting tu discuss the needed changes for 2.1

Dieses ist der Start um die nötigen Anpassungen für 2.1 zu diskutieren.

**Comment by cGiesen** [comment]
Ich finde die Lösung unglücklich wie erkannt wird, welche Version das Zugferd hat.
Ich probiere es gerade mit den offiziellen Profil Bezeichnungen :
       public static Version FromString(this Version _p, string s)
        {
            switch (s)
            {
                case "urn:ferd:invoice:1.0:basic": return Version.v10;
                case "urn:ferd:invoice:1.0:comfort": return Version.v10;
                case "urn:ferd:invoice:1.0:extended": return Version.v10;
                case "urn:ferd:invoice:rc:basic": return Version.v20;
                case "urn:ferd:CrossIndustryDocument:invoice:1p0:basic": return Version.v20;
                case "urn:ferd:invoice:rc:comfort": return Version.v20;
                case "urn:ferd:CrossIndustryDocument:invoice:1p0:comfort": return Version.v20;
                case "urn:ferd:CrossIndustryDocument:invoice:1p0:E": return Version.v20;
                case "urn:ferd:invoice:rc:extended": return Version.v20;
                case "urn:ferd:CrossIndustryDocument:invoice:1p0:extended": return Version.v20;
                //new since 2.1
                //ToDo: other profiles missing
                case "urn:cen.eu:en16931:2017": return Version.v21;
            }

            return Version.Unknown;
        } // !FromString()

**Comment by stephanstapel** [comment]
das kann ich gerne kurz so umbauen. Kommt sofort.

**Comment by cGiesen** [comment]
Das war zu schnell ;)
Jetzt fehlt die 2.0 Unterstützung ;)

Ich habe das angepasst, tue mich aber schwer, dass zu Pushen?!
Offensichtlich fehlen mir die Rechte.

**Comment by stephanstapel** [comment]
Üblicherweise arbeitet man ja auf Forks und von dort aus kannst Du Pull Requests zurück in den master stellen.
