### ISSUE TITLE
Update example "Step-by-step guide for creating invoices"

### ISSUE THREAD

**Issue by testtomat** [stephanstapel/ZUGFeRD-csharp#345]
Please change the example:

from 
desc.AddNote("Es bestehen Rabatt- und Bonusvereinbarungen.", "AAK");

to
desc.AddNote("Es bestehen Rabatt- und Bonusvereinbarungen.", SubjectCodes.AAK);

**Comment by stephanstapel** [comment]
Thanks!

https://github.com/stephanstapel/ZUGFeRD-csharp/commit/70abfd1bb1056df5210b137c5a49afe97f78b982
