### ISSUE TITLE
Wrong Mapping of PartyName and RegistrationName in 22UblReader

### ISSUE THREAD

**Issue by RenStinn** [stephanstapel/ZUGFeRD-csharp#347]
Currently the `cac:PartyName/cbc:Name` is mapped as the party name and `cac:PartyLegalEntity/cbc:RegistrationName` is mapped as TradingBusinessName.

Looking at the [specification ](https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-AccountingSupplierParty/cac-Party/cac-PartyLegalEntity/cbc-RegistrationName/) the `cbc:RegistrationName` should be the actual name of the party.

Equivalent the `cbc:Name` should be the TradingBusinessName ([source](https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-AccountingSupplierParty/cac-Party/cac-PartyName/cbc-Name/)).

This also corelates with EN16931, because `cbc:Name` has the business terms BT-28 which is defined as TradingBusinessName.
Same of `cbc:RegistratioName`, BT-27.

**Comment by stephanstapel** [comment]
Thanks for raising this!
I'd like to keep it like it is as it is consistent with the CII mapping.
I have added a comment in the class documentation. If you'd like to have a better description in the documentation, let me know!

**Comment by MelanieVeigl** [comment]
Hi Stephan, 
could you clarify the importance of maintaining consistency with CII in this case?. Since EN16931 specifies that cbc:RegistrationName should be the actual name of the party and cbc:Name should represent the TradingBusinessName, I believe aligning with this standard would help avoid potential data misinterpretations.

I would appreciate it if you could reopen the ticket to explore possible solutions. If the current implementation remains unchanged, I’ll need to adjust the mapping in my own code.
Thanks.

**Comment by stephanstapel** [comment]
Hi @MelanieVeigl ,
The C# properties are mapped 1:1 to the xml structure. I.e. Party.Name is mapped to ram:Name and Party.Name.
ram:TradingBusinessName is mapped to Party.SpecifiedLegalOrganization.TradingBusinessName accordingly.
Imho, this is straightforward for all users and mapping:

Party.Name to ram:TradingBusinessName
and Party.SpecifiedLegalOrganization.TradingBusinessName to ram:Name

would be confusing.
If I got the request wrong, please describe the actual idea. On the other hand, if it requires additional documentation, please also let me know, I'm happy to do that.

**Comment by RenStinn** [comment]
Maybe this makes it a bit clearer.
This is from the CII Specification:
![grafik](https://github.com/user-attachments/assets/fe6cd740-bef7-447e-a4bd-a5679bdcd252)
The Party Class is consistent with those namings which is fine.
But for the UBL Specification the properties are switched (in my opinion a bad design, but we need to work with it).
The UBL-Property `cac:PartyLegalEntity/cbc:RegistrationName` corresponds to the property `Party.Name` (BT-27)
The UBL-Property `cbc:Name` corresponds to the property `Party.SpecifiedLegalOrganization.TradingBusinessName` (BT-28)
So technically the library is assigning the values the wrong way round (only for UBL, CII is fine)

**Comment by stephanstapel** [comment]
I understand this. However, filling SpecifiedLegalOrganization is optional in the C# library. So I suspect that most people will not use it but expect, that filling Party object (including Name property) will be sufficient.

**Comment by RenStinn** [comment]
That is why I would suggest the following which will respect that SpecifiedLegalOrganization is optional.

UBL-Reader:
`cac:PartyLegalEntity/cbc:RegistrationName` -> Party.Name
`cac:PartyName/cbc:Name` -> Party.SpecifiedLegalOrganization.TradingBusinessName

UBL-Writer:
Party.Name -> `cac:PartyLegalEntity/cbc:RegistrationName`
Party.SpecifiedLegalOrganization.TradingBusinessName -> `cac:PartyName/cbc:Name`

CII-Reader:
`ram:Name` -> Party.Name
`ram:SpecifiedLegalOrganization/ram:TradingBusinessName` -> Party.SpecifiedLegalOrganization.TradingBusinessName

CII-Writer:
Party.Name -> `ram:Name`
Party.SpecifiedLegalOrganization.TradingBusinessName -> `ram:SpecifiedLegalOrganization/ram:TradingBusinessName`

That way if the user of the lib fills only the Party.Name the UBL and CII format can be create without violating the UBL specification.
And a propper UBL or CII file can be read correctly.
