### ISSUE TITLE
Bug in last version

### ISSUE THREAD

**Issue by cGiesen** [stephanstapel/ZUGFeRD-csharp#35]
1. 2.0 support is missing now. The tag to search vor are now in Reader2 but in fact is reader2 support for 2.1

2. when I test a  2.1 XML I got the error 
"Auf eine geschlossene Datei kann nicht zugegriffen werden."
"stream.Position = 0;" is not allow for closed streams ;)

Checking for version1 close the stream

Edit:
I transmit a file stream, not a FullPath

**Comment by stephanstapel** [comment]
Der Streaming-Bug ist gefixt:

https://github.com/stephanstapel/ZUGFeRD-csharp/commit/aaa2687387a2cee6485a483be11d55e8f85aff38

btw: kannst Du für unterschiedliche Fehler bitte unterschiedliche Issues aufmachen?

**Comment by stephanstapel** [comment]
Bzgl. des Supports von 2.0 und 2.1: willst Du das wirklich trennen? Dann würde ich auch separate Reader und Writer bereitstellen.

**Comment by cGiesen** [comment]
Streaming-Bug: Schade, jetzt war ich so stolz das ich das geschafft habe ;)

Support 2.0 und 2.1
Aktuell unterstützt Dein 1.0 auch die Version 2.0 (oder nur?)
1.0 kann ich mangels Beispiel nicht testen.
Sauberer wäre echte Trennung 10 20 und 21 dann kann man gezielter arbeiten. Ich traue Behörden eh nicht so recht über den Weg ;)
Wenn ich richtig informiert bin, ist 21 auch kompatible zu X-Rechnung, was auch wieder für extra Code spricht.

Achso, 20 und 21 ist arg unterschiedlich. Ich habe das bei mir mal versucht mit Pattern, die ich je nach Version gesetzt habe. Das ist nicht wirklich lesbar.

PS: Kannst Du mir helfen, PullRequests zu machen? Ich denke, das ist vielleicht leichter?

**Comment by stephanstapel** [comment]
ok, ich erzeuge getrennte reader und writer, code checke ich dafür gleich ein.

Bzgl. des Pull Requests ist der einfachste Weg, den ich kenne:
forke mal dieses Repository (rechts oben auf fork).
Dann clonest Du Deinen Fork, so dass Du den Code auf Deinem Rechner hast.
Führst die Änderungen durch, committest sie und pushst sie. Dann landen sie in Deinem Fork.
Der Rest ist ganz gut hier beschrieben:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by stephanstapel** [comment]
closed by https://github.com/stephanstapel/ZUGFeRD-csharp/commit/dc5e8ff947ca043ed5a9397e0d15cefd072dc5f2
