### ISSUE TITLE
ElectronicAddressSchemeIdentifiers is missing the code for Austrian VAT Number (9914)

### ISSUE THREAD

**Issue by cst-tobias-michel** [stephanstapel/ZUGFeRD-csharp#353]
Hi, 

the `ElectronicAddressSchemeIdenitfiers` Enum is missing a value for Austria.
In the [Peppol EAS](https://docs.peppol.eu/poacc/billing/3.0/codelist/eas/) it is listed as: 
9914 - Österreichische Umsatzsteuer-Identifikationsnummer

Is that intentional? If not would it be possible to add it soon?

**Comment by stephanstapel** [comment]
Hi @cst-tobias-michel ,
Maybe it was't defined in the specification when I implemented it.
Feel free to send a PR, looking forward!

**Comment by cst-tobias-michel** [comment]
@stephanstapel Thank you for your quick reply!
Closing this issue now as the code is merged in the main branch.
