### ISSUE TITLE
Add a possibility to create a new TradeLineItem with a specific LineId

### ISSUE THREAD

**Issue by quotschmacher** [stephanstapel/ZUGFeRD-csharp#356]
I am trying to write a AutoMapper configuration to use it with your data model. But since there is no constructor with a lineId or a possibility to set the lineId (as mentioned in #181 ) there is no possibility to create a map to s2industries.ZUGFeRD.TradeLineItem.
One possibility would be to move the checks from https://github.com/stephanstapel/ZUGFeRD-csharp/blob/c6e41300d0ca48c41b21501a88c2b19f1a8783c3/ZUGFeRD/InvoiceDescriptor.cs#L1172 to before creating the TradeLineItem and then pass it in a constructor.

I hope I could clarify my point...

**Comment by DaveHalma** [comment]
Hi Quotschmacher,
möglicherweise verstehe ich Dich falsch, aber hat das Stephan nicht schon in seiner Übersicht/Erklärung zum Code thematisiert? 
![Screenshot_s2](https://github.com/user-attachments/assets/df3c5722-6a60-4a35-9d30-36f1e409e5fa)
Gerne korrigieren, sofern falsch!

**Comment by quotschmacher** [comment]
Thematisiert wurde, wie man TradeLineItems hinzufügen kann.
Nehmen wir mal an, ich habe folgende Klassen:
``` csharp
public class Dokument
{
  public string Rechnungsnummer;
  public List<Position> Rechnungspositionen;
}

public class Position
{
  public sring Identifier;
}

public class InvoiceDescriptor
{
  public string InvoiceNo;
  public List<TradeLineItem> TradeLineItems;
}

public class TradeLineItem
{
  public AssociatedDocument AssociatedDocument;
}

public class AssociatedDocument
{
  public string LineID;
}
```

Was mache ich dann in AutoMapper? Ich erstelle quasi die Konfiguration für zwei Mappings. Das erste ist mal schemenhaft:

InvoiceDescriptor -> Dokument
- InvoiceNo-> Rechnungsnummer
- TradeLineItems -> Rechnungspositionen
- Reverse

TradeLineItem -> Position
- AssociatedDocument.LineId -> Identifier
- Reverse

Reverse sagt dafür, das man das Mapping dann gleich in beide Richtungen hat. Damit habe ich dann relativ einfach ein Mapping zwischen meiner Struktur und der ZUGFeRD-Library erzeugt, da ich Dokument auf InvoiceDescriptor (inklusive der Rechnungspositionen) und zurück erzeugt habe. Zusätzlich kann ich bei Bedarf auch einfach zwischen einer meiner Rechnungspositionen und einem TradeLineItem und / oder zurück mappen. Das geht dann in dem Fall aber nicht, da ich die LineId nicht setzen kann. Ich kann bei TradeLineItem -> Position auch sagen, nutze den Konstruktor, aber da gibt es auch keinen mit einer LineId. Es gibt keine Möglichkeit, einfach nur ein TradeLineItem mit einer LineId zu erzeugen, außer man fügt es direkt einer kompletten Rechnung hinzu.

**Comment by stephanstapel** [comment]
Ich hoffe, dass ich jetzt nicht an der Frage vorbei antworte: um das automatische Anlegen von Positionsnummern zu ermöglichen, braucht es die Abhängigkeit von Descriptor und Item in der Erstellung. Ich habe keine Idee, wie ich diese Abhängigkeit auflösen kann.

**Comment by quotschmacher** [comment]
Es geht mir nicht um das automatische Anlegen von Positionsnummern (ich weiß nicht inwiefern das im Hintergrund notwendig ist) - mir geht es nur darum, das man ein TradeLineItem mit einer bestimmten AssociatedDocument.LineId erzeugen kann. Dazu muss man ja eigentlich "nur" das nachträgliche Setzen der LineId ermöglichen oder eben einen entsprechenden Konstruktor bereitstellen. 
Das stellt in meinen Augen keinen Konflikt zum jetzigen System dar, da es nicht möglich ist, ein fertiges TradeLineItem zum InvoiceDescriptor hinzuzufügen, da der Setter der TradeLineItems ja eh auf internal gesetzt ist und es nur über die beiden AddTradeLineItems möglich ist. 

Ich stelle das auch gern per PR bereit, es geht mir jetzt gerade nur um das "warum ist das so??".

**Comment by stephanstapel** [comment]
kannst Du diesen Branch einmal ausprobieren:
https://github.com/stephanstapel/ZUGFeRD-csharp/tree/lineitem-lineid

**Comment by quotschmacher** [comment]
Sieht nach dem ersten kurzen Test ganz gut aus. Jetzt kann ich eine einfache Konfiguration für den AutoMapper mit

```
var configuration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<s2industries.ZUGFeRD.InvoiceDescriptor, Rechnungsdokument>()
        .ForMember(dest => dest.Rechnungspositionen, opt => opt.MapFrom(src => src.TradeLineItems))
        .ReverseMap();
    cfg.CreateMap<s2industries.ZUGFeRD.TradeLineItem, Rechnungsposition>()
        .ForMember(dest => dest.Position, opt => opt.MapFrom(src => src.AssociatedDocument.LineID)) // BT-126
        .ReverseMap()
            .ConstructUsing(src => new TradeLineItem(src.Position)); // BT-126
});
```

erstellen und dann einfach zwischen meinem Format und der ZUGFeRD-csharp Library mappen.

```
var mapper = new Mapper(configuration);

Rechnungsdokument dok = mapper.Map<Rechnungsdokument>(descriptor);

InvoiceDescriptor newDescriptor = mapper.Map<InvoiceDescriptor>(dok);
```

Und dann stehen in `newDescriptor` wieder die Rechnungspositionen mit der korrekten LineID.

Hab vielen dank - wenn das im Master ist schließe ich das Ticket.

**Comment by stephanstapel** [comment]
erledigt
