### ISSUE TITLE
ShipToTradeParty wird nicht geschrieben.

### ISSUE THREAD

**Issue by MSergLoos** [stephanstapel/ZUGFeRD-csharp#359]
Profile = Comfort
ZUGFeRDVersion.Version22

Dieses Element wird in das XML nicht geschrieben: 
 
```xml
<ram:ApplicableHeaderTradeDelivery>
			<ram:ShipToTradeParty>
				<ram:PostalTradeAddress>
					<ram:PostcodeCode>12345</ram:PostcodeCode>
					<ram:LineOne>Verwaltung Straße 40</ram:LineOne>
					<ram:LineTwo>Einheit: 5.OG rechts</ram:LineTwo>
					<ram:CityName>Musterstadt</ram:CityName>
					<ram:CountryID>DE</ram:CountryID>
				</ram:PostalTradeAddress>
			</ram:ShipToTradeParty>
		</ram:ApplicableHeaderTradeDelivery>
```

Zum Setzen der Werte benutze ich die Eigenschaft:
public Party ShipTo { get; set; }

Bespieldokument aus zugferd22de\EN16931: 
"EN16931_Betriebskostenabrechnung.pdf"

**Comment by quotschmacher** [comment]
Schau mal hier: https://github.com/stephanstapel/ZUGFeRD-csharp/blob/df32503306a6a19aaa4ba4ac7fd175b425e91ee9/ZUGFeRD/InvoiceDescriptor23CIIWriter.cs#L1265
Wird nur im Extended Profil geschrieben.

**Comment by MSergLoos** [comment]
![grafik](https://github.com/user-attachments/assets/e6c3090c-a675-498c-937c-a2b2463013e8)

**Comment by stephanstapel** [comment]
können wir dieses Thema schließen, @MSergLoos ?

**Comment by MSergLoos** [comment]
Ja, wir können das schließen
