### ISSUE TITLE
Issue beim Schreiben von PayeeTradeParty bei COMFORT

### ISSUE THREAD

**Issue by MSergLoos** [stephanstapel/ZUGFeRD-csharp#360]
Profile = Comfort
ZUGFeRDVersion.Version22

Dieser Code erzeugt folgendes XML:
```
invoice.Payee = new Party() {
  ID = new GlobalID(GlobalIDSchemeIdentifiers.Unknown, "Sample ID"),
  Name = "Sample Name",
};
```

```XML
<ram:PayeeTradeParty>
        <ram:ID>Sample ID</ram:ID>
        <ram:Name>Sample Name</ram:Name>
        <ram:PostalTradeAddress>
          <ram:CountryID>Unknown</ram:CountryID>
        </ram:PostalTradeAddress>
      </ram:PayeeTradeParty>
```

PostalTradeAddress ist nicht valide und sollte laut Spezifikation überhaupt nicht geschrieben werden.

**Comment by stephanstapel** [comment]
Kannst Du bitte einmal den aktuellen Code aus dem Master-Branch testen?

**Comment by MSergLoos** [comment]
Jetzt habe ich beim Ausführen:

Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:
    System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)
    System.Collections.Generic.Stack<T>.Pop()
    s2industries.ZUGFeRD.ProfileAwareXmlTextWriter.WriteEndElement() in ProfileAwareXmlTextWriter.cs
    s2industries.ZUGFeRD.InvoiceDescriptor23CIIWriter.Save(s2industries.ZUGFeRD.InvoiceDescriptor, System.IO.Stream, s2industries.ZUGFeRD.ZUGFeRDFormats) in InvoiceDescriptor23CIIWriter.cs
    s2industries.ZUGFeRD.InvoiceDescriptor23Writer.Save(s2industries.ZUGFeRD.InvoiceDescriptor, System.IO.Stream, s2industries.ZUGFeRD.ZUGFeRDFormats) in InvoiceDescriptor23Writer.cs
    s2industries.ZUGFeRD.InvoiceDescriptor.Save(System.IO.Stream, s2industries.ZUGFeRD.ZUGFeRDVersion, s2industries.ZUGFeRD.Profile, s2industries.ZUGFeRD.ZUGFeRDFormats) in InvoiceDescriptor.cs

**Comment by stephanstapel** [comment]
> Jetzt habe ich beim Ausführen:
> 
> Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst: System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource) System.Collections.Generic.Stack.Pop() s2industries.ZUGFeRD.ProfileAwareXmlTextWriter.WriteEndElement() in ProfileAwareXmlTextWriter.cs s2industries.ZUGFeRD.InvoiceDescriptor23CIIWriter.Save(s2industries.ZUGFeRD.InvoiceDescriptor, System.IO.Stream, s2industries.ZUGFeRD.ZUGFeRDFormats) in InvoiceDescriptor23CIIWriter.cs s2industries.ZUGFeRD.InvoiceDescriptor23Writer.Save(s2industries.ZUGFeRD.InvoiceDescriptor, System.IO.Stream, s2industries.ZUGFeRD.ZUGFeRDFormats) in InvoiceDescriptor23Writer.cs s2industries.ZUGFeRD.InvoiceDescriptor.Save(System.IO.Stream, s2industries.ZUGFeRD.ZUGFeRDVersion, s2industries.ZUGFeRD.Profile, s2industries.ZUGFeRD.ZUGFeRDFormats) in InvoiceDescriptor.cs

ja, habe ich auch gerade gemerkt. Brauche etwas, um das zu fixen.

**Comment by MSergLoos** [comment]
> ja, habe ich auch gerade gemerkt. Brauche etwas, um das zu fixen.

Lass dir ruhig Zeit .. 👍

**Comment by stephanstapel** [comment]
jetzt bitte testen. Freue mich auf Erweiterung der Testcases, das wäre sehr hilfreich. Siehe TestPartyExtensions().

**Comment by MSergLoos** [comment]
Hi Stephan, im Moment kann ich das nicht machen, aber ich schaue es mir später an und sehe, was ich tun kann.

**Comment by MSergLoos** [comment]
Nein, noch nicht. Diese Woche werde ich es nicht schaffen. Ich schreibe, wenn ich es gemacht habe.

**Comment by MSergLoos** [comment]
Hallo Stephan, jetzt möchte ich versuchen, den Testcase zu erweitern. Ich habe noch nie solche Änderungen in GitHub gemacht. Ich habe nachgeschaut, wie es gemacht wird, und wenn ich es richtig verstehe, sollte ich dein Projekt erst einmal „forken“, was eine Kopie des Projekts in meinem Account erstellt. Danach kann ich Änderungen vornehmen und sie „commiten“. Anschließend kann ich diese Änderungen als Vorschlag zur Übernahme in deinem Projekt einreichen. Ist das richtig so?

**Comment by stephanstapel** [comment]
Hallo @MSergLoos ,
ja, genauso funktioniert das. Auf der github-Oberfläche bekommst Du nach einem Commit in Deinem Fork auch direkt das Angebot, einen Pull Request zu erzeugen. D.h. wenn Du mit dem fertig bist, was Du machen möchtest, kannst Du das bequem auf der Oberfläche erledigen.

**Comment by MSergLoos** [comment]
Das können wir schließen, nehme ich an.
