### ISSUE TITLE
Add profiles for ZUGFeRD 2.1

### ISSUE THREAD

**Issue by stephanstapel** [stephanstapel/ZUGFeRD-csharp#37]
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/dc5e8ff947ca043ed5a9397e0d15cefd072dc5f2/ZUGFeRD/Profile.cs#L93

**Comment by cGiesen** [comment]
switch (profile)
                    {
                        case Profile.Minimum: return "urn:factur-x.eu:1p0:minimum";
                        case Profile.Basic: return "urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:basic";
                        case Profile.BasicWL: return "urn:factur-x.eu:1p0:basicwl";
                        case Profile.Comfort: return "urn:cen.eu:en16931:2017";
                        case Profile.Extended: return "urn:cen.eu:en16931:2017#conformant#urn:factur-x.eu:1p0:extended";
                        default: return "";
                    }
