### ISSUE TITLE
Add full Adress To BuyerTradeParty in XRechnung Profile

### ISSUE THREAD

**Issue by Nichsen** [stephanstapel/ZUGFeRD-csharp#374]
ZUGFeRDVersion : Version23
Profile: XRechnung

Kosit Validator (XRechnung 3.0.1) complains about missing buyer address (city, postcode...).
I think the problem is that it is only provided if it is a "BuyerTaxRepresentativeTradeParty" or the profil is "Extended".

**Comment by stephanstapel** [comment]
Hi @Nichsen ,
can you share the code, the file and tell if you are using the nuget version or the current github code?

**Comment by Nichsen** [comment]
Hi @stephanstapel im using the github master version.

![image](https://github.com/user-attachments/assets/d84a8035-d65b-4f23-bd9c-3f2f51c545fb)


While debuging i added additional XRechnung Profile:
InvocieDescriptor23CIIWriter.cs Line 1372:
`if ((this.Descriptor.Profile == Profile.Extended)|| (this.Descriptor.Profile == Profile.XRechnung) || partyType.In(PartyTypes.SellerTradeParty, PartyTypes.BuyerTaxRepresentativeTradeParty, PartyTypes.ShipToTradeParty, PartyTypes.ShipToTradeParty, PartyTypes.UltimateShipToTradeParty, PartyTypes.SalesAgentTradeParty)`)

With this implementaion the error in the validator is gone:

**Comment by stephanstapel** [comment]
are you talking about BuyerTaxRepresentativeTradeParty or BuyerTradeParty?

**Comment by Nichsen** [comment]
My "Buyer" is a "BuyerTradeParty". But for "BuyerTradeParty" the adress will not be written in the XML
