### ISSUE TITLE
XML in UTF-8 ohne BOM

### ISSUE THREAD

**Issue by MSergLoos** [stephanstapel/ZUGFeRD-csharp#390]
Können Sie bitte die Möglichkeit vorsehen, XML in UTF-8-Kodierung zu erstellen, aber ohne die UTF-8-BOM-Markierung? Darauf aufmerksam gemacht wurde ich durch einen Online-Validator, der mir gesagt hat, dass das XML ohne BOM sein sollte. Danach habe ich im Internet recherchiert und viele Empfehlungen gefunden, XML in UTF-8 ohne BOM zu schreiben. Die Bibliothek erstellt derzeit nur mit BOM, und ich habe keinen Weg gefunden, die Kodierung ohne BOM festzulegen (new UTF8Encoding(false)).

**Comment by stephanstapel** [comment]
afaik hat die XmlTextWriter-Klasse dafür keine Option vorgesehen. Ich empfehle daher, die Datei in einen Stream zu speichern und dann per StreamWriter mit UTF8Encoding(false) zu schreiben.

**Comment by MSergLoos** [comment]
alles klar!

**Comment by MSergLoos** [comment]
Alles klar. Das mache es jetzt. Aber eventuell sollte man dieses Issue als Wunsch für zukünftige Versionen betrachten

**Comment by MSergLoos** [comment]
Ich habe den Wunsch jetzt in "Ideas" übertrgagen

**Comment by stelogek** [comment]
Könntest Du kurz beschreiben, wie Du das gemacht hast?

**Comment by MSergLoos** [comment]
```
MemoryStream memoryStream = new MemoryStream();
invoice.Save(memoryStream,
    ZUGFeRDVersion.Version22, 
    profile 
    );

// remove BOM if exists
byte[] result = memoryStream.ToArray();
if (result.Length >= 3 && result[0] == 0xEF && result[1] == 0xBB && result[2] == 0xBF) {
    byte[] newResult = new byte[result.Length - 3];
    Array.Copy(result, 3, newResult, 0, newResult.Length);
    result = newResult;
}

return result;
```
