### ISSUE TITLE
Latest UBL-Writer is generating invalid document

### ISSUE THREAD

**Issue by quotschmacher** [stephanstapel/ZUGFeRD-csharp#399]
With the last fix for the UBL Customization ID a bug was inserted:

![image](https://github.com/user-attachments/assets/99e7953a-f045-410b-8dc6-f95d7d5a3177)

The generated CustomizationID is `<cbc:CustomizationID>cbc:CustomizationID", "urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0</cbc:CustomizationID>`

**Comment by stephanstapel** [comment]
grmpf, thanks
