### ISSUE TITLE
PaymentMeansTypeCodes.cs missing

### ISSUE THREAD

**Issue by KVS-CBL** [stephanstapel/ZUGFeRD-csharp#4]
Im Repo fehlt die Datei "PaymentMeansTypeCodes.cs".
Im Projekt ist diese vorhanden. Daher ist das Projekt aktuell nicht kompilierbar.

**Comment by stephanstapel** [comment]
oha, danke für den Hinweis. Habe ich Datei nun auch committed:

https://github.com/stephanstapel/ZUGFeRD-csharp/commit/8d27b4004a29c9c476aaf23122ee4a62a83d4164
