### ISSUE TITLE
Exception if namespaces dont have the default names 

### ISSUE THREAD

**Issue by MelanieVeigl** [stephanstapel/ZUGFeRD-csharp#401]
Hello Stephan,

i have invoices with random namespace names. This was no problem until the change in https://github.com/stephanstapel/ZUGFeRD-csharp/commit/bd15684b5eea2e0767244207bc6381ea2a590f02
Now I get an XPathException ("Namespace prefix 'udt' is not defined.") in "NodeAsDateTime()" .

Is there any chance to handle these random namespace names? 

I attached an example:
[cii22-namespace-test.txt](https://github.com/user-attachments/files/17398630/cii22-namespace-test.txt)

regards 
Melanie

**Comment by stephanstapel** [comment]
Hi Melanie,
thanks for the example. Yes, that is right.
Just wondering if is really worked before since the old code was far more rigid than the new code, ultimately expecting certain namespace prefixes

**Comment by IsThatUniqueEnough** [comment]
[Technical/XML: Regarding fixed namespace prefixes (rsm:,ram:...)](https://www.zugferd-community.net/de/infothek/technical_xml_regarding_fixed_namespace_prefixes_rsm_ram_)

**Comment by stephanstapel** [comment]
> [Technical/XML: Regarding fixed namespace prefixes (rsm:,ram:...)](https://www.zugferd-community.net/de/infothek/technical_xml_regarding_fixed_namespace_prefixes_rsm_ram_)

Interesting article, thanks!
