### ISSUE TITLE
Wrong output rounding in _formatDecimal in IINvoiceDescriptorWriter.cs

### ISSUE THREAD

**Issue by ChrisOertel** [stephanstapel/ZUGFeRD-csharp#407]
Hello,
from my point of view the rounding in the function _formatDecimal is not compatible to the FacturX Specs. Specs says that round happens to the next value (Chapter 7.1.8 Rundungsregeln bei Berechnungen):

_Für positive Zahlen: Aufrunden auf den nächsthöheren Wert. Beispiel: 13,455 auf zwei Nachkomma-stellen aufgerundet ergibt 13,46._

In the code is the default Rounding used, which ist ToEven and not AwayFromZero.

`return Math.Round(value.Value, numDecimals).ToString($"F{numDecimals}", CultureInfo.InvariantCulture);` 

From the  .Net Documentation (https://learn.microsoft.com/en-us/dotnet/api/system.math.round?view=net-8.0#system-math-round(system-decimal-system-int32)):
This method uses the default rounding convention of [MidpointRounding.ToEven](https://learn.microsoft.com/en-us/dotnet/api/system.midpointrounding?view=netframework-4.8#system-midpointrounding-toeven).

Should there be an AwayFromZero in the function?

Regards,
Chris

**Comment by stephanstapel** [comment]
Rounding is always an issue. Afaik, this should be correct?!

![grafik](https://github.com/user-attachments/assets/804e89fa-e127-45c4-8fb5-7e5d09fa0a05)

**Comment by ChrisOertel** [comment]
Morning,
I used the following test code and used the original line from _formatDecimal to get the result string:

```
        [TestMethod]
        public void Test_formatDecimal()
        {
            int numDecimals = 2;
            decimal? value = (decimal)(1145.0 * 9.3130); //10663,385

            //10663,38
            string resultWrong = Math.Round(value.Value, numDecimals).ToString($"F{numDecimals}", CultureInfo.InvariantCulture);
            //10663,39
            string result = Math.Round(value.Value, numDecimals, MidpointRounding.AwayFromZero).ToString($"F{numDecimals}", CultureInfo.InvariantCulture);
        }
```
Without the MidpointRounding.AwayFromZero i get  the wrong result:
![Github](https://github.com/user-attachments/assets/c693c48f-7ea2-463e-ba13-e1a2d2df98e8)

With MidpointRounding.AwayFromZero the calculation is fine according to the FacturX specs:
![Github2](https://github.com/user-attachments/assets/cf35ead9-3dc0-4cf8-8f71-999089400153)

We are using the nuget Package and still have a .NET 4.8 application, which should have no impact because the default for rounding has not changed in newer .NET versions)

Have a nice week,
Chris

**Comment by stephanstapel** [comment]
@ChrisOertel : I can reproduce that with your sample code, thanks.
What I still don't get:

```
decimal? x = 4.455m;
decimal y = Math.Round(x.Value, numDecimals);
```

reliably delivers 4.46. Why is this the case?
