### ISSUE TITLE
Profile cannot be read if there are upper cases in the ID string

### ISSUE THREAD

**Issue by Heinz164** [stephanstapel/ZUGFeRD-csharp#409]
I got a invoice with ID "urn:cen.eu:EN16931:2017#compliant#urn:zugferd.de:2p0:basic".
The profile cannot be read because the part "EN16931" contains upper cases.

This issue could be solved, if in Profile.ProfileExtension.FromString() the parameter "s" would be converted to lower case:

...
switch(s.ToLower())
...

**Comment by stephanstapel** [comment]
can you please verify the code change and close the ticket if it works?

**Comment by Heinz164** [comment]
Yes, your changes work.
