### ISSUE TITLE
File not closed

### ISSUE THREAD

**Issue by cGiesen** [stephanstapel/ZUGFeRD-csharp#41]
The file is still in use, when I like to use it again, I got an file is in use error

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/8d1a32e335912b8286dd3c1010a5f6a573196458/ZUGFeRD-Test/Application.cs#L55

**Comment by stephanstapel** [comment]
Please check if the error persists.

**Comment by cGiesen** [comment]
Fine now

**Comment by cGiesen** [comment]
Problem is fixed
