### ISSUE TITLE
Trade Allowance Charge on position level

### ISSUE THREAD

**Issue by srkptzld** [stephanstapel/ZUGFeRD-csharp#412]
Hello,

I am currently working on an solution to write ZUGFerD for our invoice-creation in office.
The last weeks I used this project to bring our data in correct form.

ATM the point is applying multiple allowances on one position.
I noticed that adding two tradeallowance-obj to the list will write :
```
<ram:SpecifiedTradeAllowanceCharge>
          <ram:ChargeIndicator>
            <udt:Indicator>false</udt:Indicator>
          </ram:ChargeIndicator>
          <ram:ActualAmount>3538.26</ram:ActualAmount>
          <ram:ChargeIndicator>
            <udt:Indicator>false</udt:Indicator>
          </ram:ChargeIndicator>
          <ram:ActualAmount>3538.00</ram:ActualAmount>
</ram:SpecifiedTradeAllowanceCharge>
```
instead of:
 ```
<ram:SpecifiedTradeAllowanceCharge>
          <ram:ChargeIndicator>
            <udt:Indicator>false</udt:Indicator>
          </ram:ChargeIndicator>
          <ram:ActualAmount>3538.00</ram:ActualAmount>
</ram:SpecifiedTradeAllowanceCharge>
<ram:SpecifiedTradeAllowanceCharge>
          <ram:ChargeIndicator>
            <udt:Indicator>false</udt:Indicator>
          </ram:ChargeIndicator>
          <ram:ActualAmount>3538.26</ram:ActualAmount>
 </ram:SpecifiedTradeAllowanceCharge>
```
I also noticed, that some fields, f.e. 'ReasonCode', are not implemented and that the percentages are not written to file.

I then clicked through the issues and saw that implementation of TradeAllowanceCharge on position-level was planned  in Feb. 2024. 

I was asking myself, if this is an priority in the actual state of the project or if somebody is already working on this.

**Comment by stephanstapel** [comment]
Hi @srkptzld ,
thanks for reaching out. If you like, send in a pull request. Please remember to add test cases and implement the feature for all versions where it is available.
Cheers,
Stephan
