### ISSUE TITLE
X-Rechnung 3.0 Extension not supported in Reader

### ISSUE THREAD

**Issue by MelanieVeigl** [stephanstapel/ZUGFeRD-csharp#416]
Hi Stephan,

Currently, no reader supports "X-Rechnung 3.0.2" that is compliant with extension. 

Here is an excerpt from the specification (https://xeinkauf.de/xrechnung/versionen-und-bundles/): 
![image](https://github.com/user-attachments/assets/08d9635f-3e22-4ccd-88b3-1fdfc411fdb1)

My suggestion is to add the uri to InvoiceDescriptor23CIIReader.IsReadableByThisReaderVersion()
 `"urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0"`

Regards

**Comment by stephanstapel** [comment]
quickly added
https://github.com/stephanstapel/ZUGFeRD-csharp/commit/7c5d425c9d39b0217ab866f77fa83f18e51e857a
