### ISSUE TITLE
ErrorState and message

### ISSUE THREAD

**Issue by cGiesen** [stephanstapel/ZUGFeRD-csharp#42]
Actual I got a result or not.
If not, there ist no info why!

I like to have a error flag perhaps IsError and in this case an ErrorMessage

Example:
We check the version of the XML but for some reason we can#t get the correct version.

actual the result is not filled or empty.
In this case we can set IsError to true and ErrorMessage to "not supported version"

**Comment by stephanstapel** [comment]
In fact, this is implemented by throwing exceptions. 
There is for example the UnsupportedException like used here:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/ff9df01a5174c4737e33903fd0d6e617d8f1962d/ZUGFeRD/InvoiceDescriptor1Reader.cs#L606

We can add more information to this exception if you like, e.g. text information with some details. However, I'd like to stay with this style of error messages.
