### ISSUE TITLE
ShipTo information not available on output XML

### ISSUE THREAD

**Issue by ricavir11** [stephanstapel/ZUGFeRD-csharp#421]
HI, 

I'm using v14.1 and I would like to have "ApplicableHeaderTradeDelivery" information on the XML output file.
Therefore, I'm setting ShipTo property like this :
![image](https://github.com/user-attachments/assets/1a1892c0-cd7f-4f85-8dde-1ebe678a5ebe)

Then saving in Extended profile :
![image](https://github.com/user-attachments/assets/15b58228-0eef-4ab7-80e2-a7a04309106b)

As a result, I don't have any shipment information on the XML output file.

Am I missing something ? 

PS : I also tested with latest v15 package but still same problem.

**Comment by stephanstapel** [comment]
Afaik, there is no ship to party in UBL format.
Have a look here:
https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/

If I'm wrong, I'm happy to discuss.

**Comment by ricavir11** [comment]
Humm see.
Would it be possible to map ShipTo with DeliveryLocation on UBL format :
https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-Delivery/

**Comment by ricavir11** [comment]
Wow so fast, tks @stephanstapel 
I had short review of your code and it seems good to me.
I will try to take some time to build and test it

**Comment by stephanstapel** [comment]
yep, had some spare time. Lucky you!
Could you contribute some test cases? I.e. writing and reading with delivery date, without shipto, without delivery date, with shipto, with both elements?
