### ISSUE TITLE
UBL-Writer Closing Tag for Delivery is missing

### ISSUE THREAD

**Issue by quotschmacher** [stephanstapel/ZUGFeRD-csharp#427]
There is a missing `Writer.WriteEndElement();` to the following line:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/f36c837b11569dbd2c7af59e4f43893e8b5584bb/ZUGFeRD/InvoiceDescriptor22UBLWriter.cs#L212C17-L212C61

**Comment by stephanstapel** [comment]
looks right, can you send in a PR? Just wondering why no test case breaks.

**Comment by quotschmacher** [comment]
I wrote an simple test method but it did finish with a success. Then I looked into the code...

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/f36c837b11569dbd2c7af59e4f43893e8b5584bb/ZUGFeRD/ProfileAwareXmlTextWriter.cs#L187C1-L190C10

Ther´function called there has the following description: `// Closes any open elements or attributes and puts the writer back in the Start state.`

And the created invoice looked like

``` xml
    </cac:InvoiceLine>
  </cac:Delivery>
</ubl:Invoice>
```

So there is nearly no way to test if all entries have a corresponding closing element, as it will be autogenerated.

**Comment by quotschmacher** [comment]
thanks!
