### ISSUE TITLE
I want to fix some issues for XRechnung-Export in UBL 2.4

### ISSUE THREAD

**Issue by Tr1ckMan** [stephanstapel/ZUGFeRD-csharp#436]
When I create an XRechnung with the current ZUGFeRD dll and validate it on https://erechnungsvalidator.service-bw.de/, several errors are displayed. This is due to the new UBL/XRechnung version. To fix the errors, I need to make changes that are not backward compatible. Should I do this in a new writer class?

I would clone the InvoiceDescriptor22UBLWriter class as InvoiceDescriptor24UBLWriter?
In this new class I could fix the problems I know about and create a PR. Or do you have a better idea?

**Comment by stephanstapel** [comment]
yes, feel free. I guess the reader version then also needs an update.

**Comment by Tr1ckMan** [comment]
hi @stephanstapel.
I have just read that the latest XRechnung (3.0.2) standard is also based on UBL 2.1. So it makes no sense to write the UBLWriter for 2.4. 
Why does the UBLWriter exist for version 2.2 if only 2.1 is actually supported?

How can we or I incorporate the current XRechnung standards into the UBLWriter? Is there a concept for this?
