### ISSUE TITLE
AccountingCustomerParty CompanyID

### ISSUE THREAD

**Issue by DaveHalma** [stephanstapel/ZUGFeRD-csharp#441]
Dear EInvoice enthusiasts, dear Stephan 
Foremost, thanks for the amazing project!
I came across an issue with the AccountingCustomerParty and thus with the current state of the InvoiceDescriptor22UBLReader. 
In my case, I need the cac:PartyLegalEntity in order to access the Customer CompanyID. I modified the code accordingly, and it works fine now. 
Did any of you came across this problem? And if so, how did you solve it?
Many thanks
Dave

The xml looks like this:
<cac:AccountingCustomerParty>
<cac:Party>
<cbc:EndpointID schemeID="9930">DE279247134</cbc:EndpointID>
<cac:PostalAddress>
...
</cac:PostalAddress>
<cac:PartyLegalEntity>
<cbc:RegistrationName>DB Service GmbH</cbc:RegistrationName>
<cbc:CompanyID>DE279247134</cbc:CompanyID> // my point of interest

**Comment by stephanstapel** [comment]
Can you share your code or send a pull request?
