### ISSUE TITLE
'ram'-Namespace problem(/rsm:ExchangedDocument/ram:IncludedNote) InvoiceDescriptor23CIIReader

### ISSUE THREAD

**Issue by DicomSiarheiVishneuski** [stephanstapel/ZUGFeRD-csharp#469]
I have one error with Message: "Namespace prefix 'ram' is not defined." in ExchangedDocument->IncludedNote(/rsm:ExchangedDocument/ram:IncludedNote) area by read.

**Comment by DicomSiarheiVishneuski** [comment]
[xrechnung-Test.xml.txt](https://github.com/user-attachments/files/17980445/xrechnung-Test.xml.txt)
xrechnung-info-file

**Comment by stephanstapel** [comment]
thanks.
The prefixes ram and rsm should be used from your supplier:

https://www.zugferd-community.net/de/infothek/technical_xml_regarding_fixed_namespace_prefixes_rsm_ram_

**Comment by DicomSiarheiVishneuski** [comment]
link not work:
![image](https://github.com/user-attachments/assets/bad33039-ce30-41a8-9b3d-37b6cd08c44c)

**Comment by DicomSiarheiVishneuski** [comment]
yes, if namespaces "rsm, ram" are mandatory, and in your code they are visible among the names, why are they not in the list of namespace-prefixes?

**Comment by DicomSiarheiVishneuski** [comment]
I received this invoice and cannot download it using the library. What should I do? can you me halp, please

**Comment by DicomSiarheiVishneuski** [comment]
i will tolk, that a function 'XmlNamespaceManager nsmgr = _GenerateNamespaceManagerFromNode(doc.DocumentElement);' is false , or the  loop foreach (XmlNode node in doc.SelectNodes("//rsm:ExchangedDocument/ram:IncludedNote", nsmgr)) in class "InvoiceDescriptor23CIIReader".
