### ISSUE TITLE
Make all properties of the InvoiceDescriptor public

### ISSUE THREAD

**Issue by drocx** [stephanstapel/ZUGFeRD-csharp#474]
@stephanstapel I just saw your commit https://github.com/stephanstapel/ZUGFeRD-csharp/commit/866fdc7344b7d62af8172d4383b6b0098dbaca06 when I wanted to make some changes to the InvoiceDescriptor.
Will this just be a demo PDF or e.g. a graphical representation of an XRechnung?

My employer has asked me to integrate something like this into our software.

Therefore, I had mapped the InvoiceDescriptor class into a report and displayed everything graphically there.
I noticed that some properties are still set to private, such as the PaymentTerms.

Can the remaining private properties perhaps all be set to public, or is there something against it?

<img width="215" alt="image" src="https://github.com/user-attachments/assets/5faaa999-1aea-43f1-b520-162f40108756">

**Comment by stephanstapel** [comment]
Hi @drocx ,
my intention is not to make all properties public. In contrary, for all substructures and lists, I am intending to make at least the setter private and rather implement functions to fill the substructure or add elements to the lists.
