### ISSUE TITLE
Property 'Tax.AllowanceChargeBasisAmount' is always 0 when loaded from a stream

### ISSUE THREAD

**Issue by amroel** [stephanstapel/ZUGFeRD-csharp#486]
Hi,
please take a look at the following test case:
https://github.com/amroel/ZUGFeRD-csharp/blob/reading_applicable_taxes/ZUGFeRD.Test/TestTaxes.cs

The test is failing on the last line `Assert.AreEqual(-5m, actualTax.AllowanceChargeBasisAmount);`

To be clear: The property is very well saved on line 36 ( `expected.Save(ms);`), it's just not set when loaded back on line 39 (`InvoiceDescriptor actual = InvoiceDescriptor.Load(ms);`)

Please let me know if I'm doing something wrong or if I eventually can/should provide a PR.

Kind Regards
Amro

**Comment by stephanstapel** [comment]
Hi @amroel ,
when passing no additional parameters, you are storing the file as ZUGFeRD version 1 and profile Basic. And you are right, there seems to be a bug in https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/InvoiceDescriptor1Reader.cs. I would be more than happy if you would fix it and send a PR. I guess you can find the corresponding code in the reader classes for the more modern versions.
