### ISSUE TITLE
Invalid xml according to online validator

### ISSUE THREAD

**Issue by pkurz** [stephanstapel/ZUGFeRD-csharp#49]
Hi Stephan,
thanks for this library, i am trying to get it to work.
But it seems i can't generate a xml schema that satisfies the online validator: [Vaildator](https://www.zugferd-community.net)

I always get an error:
`schema validation fails:org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 15; cvc-complex-type.2.4.a: Invalid content was found starting with element '{"urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":Name}'. One of '{"urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":IssueDateTime}' is expected.`

Even though "IssueDateTime" is in my xml schema.. Maybe it has to be in another order?

**Comment by stephanstapel** [comment]
which version of ZUGFeRD are you using. Can you provide a sample file?

**Comment by pkurz** [comment]
Thanks for the fast response 👍 
Sure i attach a example file, which is using ZUGFeRD 2.1. (For me 2.0 didnt make a difference in the validator)
[ZUGFeRD-invoice.zip](https://github.com/stephanstapel/ZUGFeRD-csharp/files/4835669/ZUGFeRD-invoice.zip)

**Comment by cGiesen** [comment]
I will test in the evenig. 
Tests with some official sites are still open! Thanks for the example.
By the way. Import example and export during testing is nearly the same ;)

**Comment by cGiesen** [comment]
I start testing with this validator and I'm confused.
1. He didn't like TestIndicator, but the docu give me that property
2. I got an error because of ExchangedDocument / Name, Have a look to BT-1 it's allowed

From my point of view, the testing is not ok. The docu give other information

I do some other test here:
https://ecosio.com/de/peppol-und-xml-dokumente-online-validieren/

Here I got one error because of the shema(?)

I try the file creted during testing.

Any ideas?

**Comment by cGiesen** [comment]
Hello,

I got a positiv result now. But there is more work left than expacted.

cu

**Comment by pkurz** [comment]
That sounds good and bad 😞 Is it possible (once the pull request gone through) to create valid basic profile.

**Comment by cGiesen** [comment]
Basic should be fine now. 
But we need realy more tests
Perhaps you can help?

**Comment by pkurz** [comment]
I do not have that much time, but i can try :)
Where do you need help?

**Comment by stephanstapel** [comment]
I will merge the code tonight. It'd be great if you could use your real world examples (probably with different profiles) and validate that against one of the validators. If you then find non-non-sense errors from the validators, it'd be great to share them (as separate issues please).

**Comment by pkurz** [comment]
Sure, sounds great. Will do it in the next few days

**Comment by stephanstapel** [comment]
I found some time to merge and test already. 
Loaded official examples, saved them again and compared both files.
Looks quite promising imho. Some things vary but that shouldn't matter too much for everyday use cases. I'm closing this issue now.
