### ISSUE TITLE
AddSpecifiedTradeAllowanceCharge does not add reason to XML

### ISSUE THREAD

**Issue by ChrisOertel** [stephanstapel/ZUGFeRD-csharp#491]
Hello, 
as I can not reopen Issue #445 I write an new one...

The reason for SpecifiedTradeAllowanceChargein Profile Comfort is not writen to the XML file.
According to the documentation for Factur-X 1.0. 7 reason is also availible in the Comfort profile and not only in Extended or XRechnung.

**Comment by stephanstapel** [comment]
can you please send a PR?

**Comment by ChrisOertel** [comment]
Added #494

**Comment by stephanstapel** [comment]
merged
