### ISSUE TITLE
CustomizationID Not Changing with Profile Selection

### ISSUE THREAD

**Issue by HerrMagiic** [stephanstapel/ZUGFeRD-csharp#492]
#### Description
It appears that the `<cbc:CustomizationID>` does not change when selecting different profiles. In my tests with the Comfort and Basic profiles and selected format `ZUGFeRDFormats.UBL` , the `<cbc:CustomizationID>` is always set to:

```
urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0
```

Is this behavior correct, or should there be a way to distinguish between profiles? For example, should it be something like:

```
urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:basic
```

It would be great if someone can give me clarification on this.

Thank you

**Comment by stephanstapel** [comment]
yes, you are right. That makes no sense.
UBL is only applicable for XRechnung.
I will make sure that an exception is thrown!
