### ISSUE TITLE
Where is the cac:AccountingCustomerParty>cac:Party>cac:PartyIdentification>cbc:ID>? 

### ISSUE THREAD

**Issue by djbox3** [stephanstapel/ZUGFeRD-csharp#496]
Help question, 
I'm trying to generate the following:  
invoiceDescriptor.Save("ubl.xml", ZUGFeRDVersion.Version23, Profile.XRechnung, ZUGFeRDFormats.UBL);

In the "xRechnung with LineId.xml" sample, shows the following example:

**cac:AccountingCustomerParty>cac:Party>cac:PartyIdentification>cbc:ID>**

    <cac:AccountingCustomerParty>
        <cac:Party>
            <cbc:EndpointID schemeID="EM">buyer@info.de</cbc:EndpointID>
            **<cac:PartyIdentification>
                <cbc:ID>[Buyer identifier]</cbc:ID>
            </cac:PartyIdentification>**

I didn't see any way to add cac:PartyIdentification>cbc:ID. Is there a reason why we don't have a way to implement it?

I was only able to generate the following:
  <cac:AccountingCustomerParty>
    <cac:Party>
      <cbc:EndpointID schemeID="EM">buyer@info.de</cbc:EndpointID>
      **<cac:PartyName>
        <cbc:Name>[Buyer identifier]</cbc:Name>
      </cac:PartyName>**

**Comment by stephanstapel** [comment]
Hi @djbox3 ,
can you please check the latest code and test if this implements the desired behavior?
