### ISSUE TITLE
DateTimeInvalidLocalFormat Exception in PDF Saving

### ISSUE THREAD

**Issue by langeengineering** [stephanstapel/ZUGFeRD-csharp#499]
Hi,

ich bekomme den Fehler:

"Eine UTC-DateTime wird in Text konvertiert, dessen Format nur für die lokale Zeitangabe gültig ist. Dies kann auftreten, wenn Sie DateTime.ToString mithilfe des "z"-Formatbezeichners aufrufen, wodurch ein lokaler Zeitzonenoffset in der Ausgabe eingefügt wird. Verwenden Sie in diesem Fall entweder den "Z"-Formatbezeichner, der eine UTC-Zeit angibt, oder die "o"-Formatzeichenfolge (dies ist die empfohlene Vorgehensweise, wenn eine DateTime im Text erhalten bleiben soll). Die Ursache kann auch sein, dass Sie eine DateTime übergeben, die von XmlConvert oder DataSet serialisiert werden soll. Wenn Sie XmlConvert.ToString verwenden, übergeben Sie XmlDateTimeSerializationMode.RoundtripKind, damit richtig serialisiert wird. Wenn Sie DataSet verwenden, legen Sie DateTimeMode für das DataColumn-Objekt auf DataSetDateTime.Utc fest. "

wenn ich via:

`await InvoicePdfProcessor.SaveToPdfAsync(targetPath, ZUGFeRDVersion.Version23, Profile.Comfort, ZUGFeRDFormats.CII, sourcePath, desc);`

eine ZUGFeRD PDF generieren möchte.

**Comment by stephanstapel** [comment]
an welcher Stelle wird dieser Fehler denn geworfen? Es wäre toll, wenn Du einmal durch den Code durchsteppen könntest

**Comment by langeengineering** [comment]
Das Ganze passiert in Zeile **120** in der **"ZUGFeRD-csharp/ZUGFeRD.PDF/InvoiceDescriptorPdfSaver.cs"**

` xmlParamsDict.Elements.Add("/ModDate", new PdfString("D:" + DateTime.UtcNow.ToString("yyyyMMddHHmmsszzz")));`

**Comment by stephanstapel** [comment]
Kannst Du den aktuellen Code einmal ausprobieren?

**Comment by stephanstapel** [comment]
@langeengineering : Du kannst den Code entweder mit git clonen oder Du auf Download zip:

![grafik](https://github.com/user-attachments/assets/f6ab6a46-9c5d-432a-b940-205be58d3965)

**Comment by langeengineering** [comment]
Ah und dann erstelle ich einen Test in meinem geclonten Projekt/Code?

**Comment by langeengineering** [comment]
Sorry für die verspätete Rückmeldung.
Ich habe einen eigenen Test erstellt der nun unter meinem Test Code von vorher sauber durchläuft.
Die Änderungen können so übernommen werden.

**Comment by Blacktempel** [comment]
@stephanstapel crasht leider immer noch in `InvoiceDescriptorPdfSaver`.
Bitte zusätzlich auch in Zeile 167 + 168 abändern, das wurde vergessen. Habe das lokal bei mir bereits gemacht.

Aktuell:
`.Replace("{{CreationDate}}", dateTimeNow.ToString("yyyy-MM-ddThh:mm:sszzz"))`
`.Replace("{{ModificationDate}}", dateTimeNow.ToString("yyyy-MM-ddThh:mm:sszzz"))`

Soll:
`.Replace("{{CreationDate}}", _FormatPdfDateTime(dateTimeNow))`
`.Replace("{{ModificationDate}}", _FormatPdfDateTime(dateTimeNow))`

Danke :)

**Comment by stephanstapel** [comment]
@Blacktempel : soweit ich mich in die Standards eingelesen habe, wird ein Zeitstempel innerhalb der PDF-Datei (/ModDate) anders kodiert als in den XMP-Daten.

PDF-Datei:

![grafik](https://github.com/user-attachments/assets/31faea07-8652-4a24-ac9f-7a7d264c1771)

XMP-Daten:

![grafik](https://github.com/user-attachments/assets/2bd0ebce-7066-48ae-b0b2-056d3aab9db3)

**Comment by stephanstapel** [comment]
@langeengineering , @Blacktempel : könnt Ihr den eben aktualisierten Code bitte einmal ausprobieren?
Und mir sagen, ob Ihr .net Core oder .net Framework 4.x verwendet.

**Comment by langeengineering** [comment]
@stephanstapel 

Dieser Code funktioniert nach wie vor bei mir auf .Net Framework 4.8

**Comment by Blacktempel** [comment]
Funktioniert, danke, bin noch auf .NET Framework 4.x

**Comment by PalmKiT** [comment]
Hallo, ich hatte zuerst das selbe Problem. Ich habe mir dann die DLL's mit dem aktuellen Code (heute ca. vor 2 Stunden) selbst gebaut und getestet. Der DateTime Fehler war weg, jedoch kriege ich jetzt eine MissingMethodException beim aufrufen von InvoicePdfProcessor.SaveToPdfAsync().
![grafik](https://github.com/user-attachments/assets/8821f705-9d7c-4039-a5a6-1ca60a8820ff)
PdfSharp ist installiert per NuGet und auch rechts zu sehen unter den Verweisen.
![grafik](https://github.com/user-attachments/assets/b3a8d339-52d1-49df-b5f0-735e2ada2851)

**Comment by langeengineering** [comment]
Ich habe nun in meinem Code das selbe Verhalten wie @PalmKiT

**Comment by stephanstapel** [comment]
@PalmKiT : mit dem Standard PDFSharp funktioniert es leider nicht. Ich veröffentliche in den nächsten Tagen eine neue Version.

**Comment by PalmKiT** [comment]
Gibt es einen Workaround oder eine andere PDFSharp Version, die ich vorerst nutzen kann?

**Comment by PalmKiT** [comment]
@stephanstapel Mit PDFSharp Extended (über NuGet) klappt das speichern auch nicht. Genau der selbe Fehler wie an vorher erwähnten Stelle. Ich warte dann auf eine neue Version, vielen dank soweit :)

**Comment by PalmKiT** [comment]
@stephanstapel Mit der neuen Version hat das nun alles geklappt, vielen dank. PDF ist valide laut portinvoice. Leider fehlt nun die Signierung mit PDF/A. Wie genau schaffe ich es diese zu signieren? Über PDFSharp?

**Comment by stephanstapel** [comment]
@PalmKiT : vielleicht mal so rum: ich habe bislang noch keine signierten PDF-Rechnungen gesehen.
Ansonsten, ja. Die Version 6.2 soll das können:
https://docs.pdfsharp.net/PDFsharp/Topics/PDF-Features/Signatures.html
allerdings nutze ich für ZUGFeRD.PDF nicht PDFSharp selbst sondern einen Community Fork, da PDFSharp selbst im Moment eigene XMP-Metadaten verhindert.
