### ISSUE TITLE
Validierung

### ISSUE THREAD

**Issue by KVS-CBL** [stephanstapel/ZUGFeRD-csharp#5]
Hallo,
wurden die generierten Daten validiert?
Habe meine generierten Dateien mal auf dieser Seite getestet: https://www.din-zugferd-validation.org
Ergebnis: Sehr viele Fehler im Bereich von (fehlenden) Namespaces und auch fehlende Elemente.
[ValidationResult.txt](https://github.com/stephanstapel/ZUGFeRD-csharp/files/356760/ValidationResult.txt)

Die strukur enspricht an vielen Stellen auch nicht den Beispiel dateien von Zugferd und als sich auch nicht mit deren xsd validieren.

Hat dies auch schon jemand anderes beobachten können, bzw. hat eine Lösung parat?
Ansonsten bemühe ich mich um einen Hotfix...

**Comment by stephanstapel** [comment]
Hallo,
ja, die Generierung habe ich validiert. Mit der letzten Version aus nuget funktioniert alles recht gut, die Daten sehen dann auch anders aus als die in ValidationResult.txt :)

Es gibt übrigens leider mehrere Validierer, die unterschiedliche Ergebnisse liefern (siehe auch https://www.checker.ferdmc.com/).

Der DIN-Checker wirft leider auch mit der neuen Version einige Fehler, die gemäß Spezifikation eigentlich korrekt wären, das können wir uns gerne gemeinsam hier ansehen.

Ansonsten stell' gerne den Quellcode zur Verfügung, mit der die xml-Datei generiert wurde, dann schaue ich mir das an!

**Comment by KVS-CBL** [comment]
Hi Stephan,
Die NuGet Ressource zu aktualisieren war der richtige Hinweis. Ist mir jetzt fast ein wenig peinlich... :)
Ich danke dir.
