### ISSUE TITLE
Add value to the public enum ReferenceTypeCodes

### ISSUE THREAD

**Issue by christianschmid200272** [stephanstapel/ZUGFeRD-csharp#501]
Pleas expand the public enum ReferenceTypeCodes about the value 'ON' (Order document identifier, buyer assigned | [1022] Identifier assigned by the buyer to an order. |).

**Comment by stephanstapel** [comment]
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/bbb0b499ba7ff14d524d471c90f55b713b90b3cb/ZUGFeRD/ReferenceTypeCodes.cs#L203
?
