### ISSUE TITLE
Problem with quantities and decimal places

### ISSUE THREAD

**Issue by AlgoLinz** [stephanstapel/ZUGFeRD-csharp#503]
Hi,

I am using the NuGet package ZugFerd-csharp version 16.0.3.

My client deals with wood, and therefore the quantities must be specified with three decimal places. When I create an invoice with a single item:

    Price / m³ = 520 EUR
    Quantity = 15,619
    Tax = 19%
    Netto amount = 8121,88 EUR
    tax amount = 1543,16 EUR
    Brutto amount = 9665,94 EUR

then my XML file looks like this:

      <ram:SpecifiedLineTradeAgreement>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>8122.40</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>

In the element ChargeAmount, the total net amount is present (it should be the net price per unit, which is 520). Consequently, the remaining calculations, such as:

        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>126871.89</ram:LineTotalAmount>
        </ram:Speci

fiedTradeSettlementLineMonetarySummation>

is wrong.

However, if the quantity is specified without decimal places (e.g., 15 or 50 or ...), then the XML section looks correct. In the element ChargeAmount, the net price per unit is specified.

Could it be that the library in version 16.0.3 has a bug in this area?

Thank you

**Comment by stephanstapel** [comment]
I can't verify this.
I copied _formatDecimal() from here:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/d7e0c9cd378b0db102d533337d0f15d281d80b52/ZUGFeRD/IInvoiceDescriptorWriter.cs#L48

and created a test method.  The method is successful:

```
[TestMethod]
public void DecimalRoundTest()
{
    string s = "";
    decimal? value = 8121.88m;
    int numDecimals = 2;


    if (value == null)
    {
        s = String.Empty;
    }

    s = Math.Round(value.Value, numDecimals, MidpointRounding.AwayFromZero).ToString($"F{numDecimals}", CultureInfo.InvariantCulture);
    Assert.AreEqual(s, "8131.88");
}
```

Can you debug InvoiceDescriptor23CIIWriter and set a breakpoint here:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/d7e0c9cd378b0db102d533337d0f15d281d80b52/ZUGFeRD/InvoiceDescriptor23CIIWriter.cs#L363

**Comment by AlgoLinz** [comment]
Danke @stephanstapel,

habe den Fehler gefunden. In der Methode desc.AddTradeLineItem habe ich statt Netto- und Bruttopreis des einzelnen Stückes den Netto- und Bruttopreis der Position übergeben.

Dadurch entstand der Fehler.

**Comment by stephanstapel** [comment]
@AlgoLinz : puh, ich wäre sonst auch echt ratlos gewesen.
