### ISSUE TITLE
4461  Payment means code incomplete?

### ISSUE THREAD

**Issue by hyreka** [stephanstapel/ZUGFeRD-csharp#510]
Hello,

is the PaymentMeansTypeCodes list incompletely implemented or are there reasons why not all codes defined at [https://unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred4461.htm](url) appear?

I am missing something like PayPal:

+ 68 Online payment service
              Payment will be made or has been made by an online
              payment service.

Seems to fit.

I'm not that deep into the topic yet, I hope the question is not senseless.
Can the list be extended?

**Comment by stephanstapel** [comment]
Please send a PR to add this code. There are intentionally not all values in the component (for all codes) since the vast amount of possibilities will make the component almost useless - you can't find anything then.

**Comment by hyreka** [comment]
Thanks for your fast response and great work!

I have not used github so far.

I will try to create a PR.

Thanks
