### ISSUE TITLE
System.ArgumentException in ZUGFeRD.PDF.Test

### ISSUE THREAD

**Issue by langeengineering** [stephanstapel/ZUGFeRD-csharp#513]
Wenn ich den Test BasicSaveExampleFile() im  ZUGFeRD.PDF.Test ausführe bekomme ich folgenden Fehler:

> BasicSaveExampleFile
>    Quelle: SaveTests.cs Zeile 28
>    Dauer: 147 ms
> 
>   Nachricht: 
> Die Testmethode "s2industries.ZUGFeRD.PDF.Test.SaveTests.BasicSaveExampleFile" hat eine Ausnahme ausgelöst: 
> System.ArgumentException: A PDF name must start with a slash (/).
> 
>   Stapelüberwachung: 
> PdfName.ctor(String value)
> InvoiceDescriptorPdfSaver._CreateFacturXStream(Stream pdfStream, Stream xmlStream, ZUGFeRDVersion version, Profile profile, String documentTitle, String documentDescription, String invoiceFilename) Zeile 147
> InvoiceDescriptorPdfSaver.SaveAsync(Stream targetStream, ZUGFeRDVersion version, Profile profile, ZUGFeRDFormats format, Stream pdfSourceStream, InvoiceDescriptor descriptor) Zeile 56
> InvoiceDescriptorPdfSaver.SaveAsync(String targetPath, ZUGFeRDVersion version, Profile profile, ZUGFeRDFormats format, String pdfSourcePath, InvoiceDescriptor descriptor) Zeile 75
> InvoicePdfProcessor.SaveToPdfAsync(String targetPdfPath, ZUGFeRDVersion version, Profile profile, ZUGFeRDFormats format, String pdfSourcePath, InvoiceDescriptor descriptor) Zeile 59
> SaveTests.BasicSaveExampleFile() Zeile 37

**Comment by stephanstapel** [comment]
Âktualisiere bitte einmal das nuget-Paket

**Comment by langeengineering** [comment]
@stephanstapel welches Nuget Paket meinst du? ich verwende den geclonten Code direkt aus deinem Repository.

**Comment by stephanstapel** [comment]
@langeengineering : dann müsstest Du einmal den Code aktualisieren, habe gerade ein Update gepushed

**Comment by langeengineering** [comment]
Passt jetzt danke!
