### ISSUE TITLE
Fehler beim Erstellen einer PDF mit InvoicePdfProcessor.SaveToPdfAsync

### ISSUE THREAD

**Issue by conceptcase** [stephanstapel/ZUGFeRD-csharp#518]
Folgende Fehler erhalte ich beim Erstellen einer ZUGFeRD PDF Datei:

=== Zustandsinformationen vor Bindung ===
LOG: DisplayName = PdfSharp, Version=1.1.1.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb
 (Fully-specified)
LOG: Appbase = file:///C:/2_Projekte/2_3_Projekte/VisualStudioOnline/FDDIS2024/RuntimeObjekte/Debug/
LOG: Ursprünglicher PrivatePath = NULL
Aufruf von Assembly : s2industries.ZUGFeRD.PDF, Version=16.1.1.0, Culture=neutral, PublicKeyToken=18b03107da61b096.
===
LOG: Diese Bindung startet im default-Load-Kontext.
LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\2_Projekte\2_3_Projekte\VisualStudioOnline\FDDIS2024\RuntimeObjekte\Debug\FDDIS_Start.exe.Config
LOG: Die Hostkonfigurationsdatei wird verwendet: 
LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config wird verwendet.
LOG: Verweis nach der Richtlinie: PdfSharp, Version=1.1.1.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb
LOG: Download von neuem URL file:///C:/2_Projekte/2_3_Projekte/VisualStudioOnline/FDDIS2024/RuntimeObjekte/Debug/PdfSharp.DLL.
WRN: Der Vergleich des Assemblynamens führte zum Konflikt: Nebenversion.
ERR: Das Setup der Assembly konnte nicht abgeschlossen werden (hr = 0x80131040). Die Suche wurde beendet.

Die Datei oder Assembly "PdfSharp, Version=1.1.1.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)

Stacktrace:
   at s2industries.ZUGFeRD.PDF.InvoiceDescriptorPdfSaver._CreateFacturXStream(Stream pdfStream, Stream xmlStream, ZUGFeRDVersion version, Profile profile, String documentTitle, String documentDescription, String invoiceFilename)
   at s2industries.ZUGFeRD.PDF.InvoiceDescriptorPdfSaver.<SaveAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at s2industries.ZUGFeRD.PDF.InvoiceDescriptorPdfSaver.<SaveAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at s2industries.ZUGFeRD.PDF.InvoicePdfProcessor.<SaveToPdfAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at FDDIS.CtlReporting.<CreateEDIAsync>d__33.MoveNext() in C:\2_Projekte\2_3_Projekte\VisualStudioOnline\FDDIS2024\CtlAndOtherClasses\CtlReporting.cs:line 2426

Was ist zu tun (bin leider nicht ganz so tief in der Materie) ;-) ?

**Comment by stephanstapel** [comment]
Verwendest Du .net Framework 4.0? Ist PDFSharp für diese Version verfügbar? Kannst Du bitte einmal nachschauen?

**Comment by conceptcase** [comment]
Aktuell verwenden wir .NET 4.7.2
PDFSharp und PDFSharp-Extended sind installiert ...
Wir haben auch schon mit den beiden aktuellen Previews getestet ...

**Comment by stephanstapel** [comment]
wahrscheinlich wird es nicht funktionieren, wenn beide installiert sind.
Gib' hier gerne auch einen Daumen hoch, damit empira die notwendige Funktion umsetzt, so dass wir hier das normale Paket verwenden können: https://github.com/empira/PDFsharp/pull/44

**Comment by stephanstapel** [comment]
ja, für die ZUGFeRD-Bibliothek ist ausschließlich pdfsharp-extended notwendig

**Comment by conceptcase** [comment]
Ergebnis bleibt das Gleiche ...
Bin am Verzweifeln ;-) X-Rechnungen passen und sind 100% valide;
Bekomme nur keine ZUGFeRD-PDF-Datei; es wird zwar "augenscheinlich" was eingebettet, aber die Fehler bleiben identisch und die PDF-Datei lässt sich als ZUGFeRD nicht öffnen ...

**Comment by stephanstapel** [comment]
Kannst Du einmal das Projekt herunterladen und die Unit Tests von ZUGFeRD.PDF.Test ausführen?

**Comment by conceptcase** [comment]
Hallo Herr Stapel,
erstmal ganz herzlichen Dank für das Engagement und die Hilfestellungen.
Wir haben die Unit Tests durchgeführt und konnten nichts Auffälliges erkennen, da sich bei uns nur ein Konsolenfenster geöffnet hat. Daraus konnten wir keine neuen Erkenntnisse erlangen.

Aktuell gibt es die Problemstellung, dass Ihr Projekt die PDFSharp 1.1.1 erwartet, aber aus irgendeinem Grund diese als Konflikt/Fehler erkannt wird.
**+++Message+++**
Die Datei oder Assembly "PdfSharp, Version=1.1.1.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)

Beim Kompilieren erscheint eine Warnung mit einem Konflikt zu einer PDFSharp 1.2.0:
**+++WARNUNG+++**
Es wurden Konflikte zwischen verschiedenen Versionen von "PdfSharp" gefunden, die nicht aufgelöst werden konnten.
Konflikt zwischen PdfSharp, Version=1.1.1.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb und PdfSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb.

BEIDE wohlgemerkt mit dem identischen Token !
**Kann es evtl. sein, dass in einer DLL ein falscher Token oder eine falsche Version eingetragen ist ?**

Wir haben jetzt in unserer Verzweiflung ;-) mal alle Nuget's rausgenommen und "sauber" wieder eingebunden.
Dann kommt zuerst ein anderer Fehler, gefolgt von dem obigen:
**+++Message+++**
Die Datei oder Assembly "Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)

Die Assembly "PdfSharp" ist bei uns als 1.1.1 eingebunden.
Die Assembly "Microsoft.Extensions.Logging.Abstractions" ist bei uns automatisch mit Version 9.0.0 eingebunden.

Was können/müssen wir tun, damit wir ZUGFeRD PDF-Dateien generieren können ?
MfG
Horst Gaffron

**Comment by stephanstapel** [comment]
es tut mir sehr leid, aber der Umgang mit Dependencies im klassischen .net Framework hat mir auch immer Kopfschmerzen bereitet. Ich erinnere mich gut daran, wie lange es gedauert hat, bis man alles zurechtgezupft hatte, bis es diese Fehlermeldungen nicht mehr gab. Eine Lösung dafür übersteigt den Scope dieser Komponenten.
DIe Nutzung von .net core ist keine Option?

**Comment by conceptcase** [comment]
Das ist schlecht, denn so wie es scheint kommt die Problematik ja aus einer Ihrer DLL's heraus.
Ich bin da so langsam hilflos, da ich bereits alles versucht habe, was ich dazu gefunden hab.
Vielleicht könnten wir ja mal einen Fernzugriff machen; selbstverständlich gegen Bezahlung und ein Honorar für Sie ... ;-)

**Comment by stephanstapel** [comment]
wenn ich es richtig verstehe, entsteht das Dilemma durch pdfsharp-extended. Die Komponente ist leider notwendig, siehe Kommentar oben. Ist die Isolation in eine eigene Applikation eine Option, so dass die Dependencies sich nicht mit denen der restlichen Applikation mischen?

**Comment by conceptcase** [comment]
Das kann ich leider nicht abschließend oder mit Sicherheit bestimmen, ob das Dilemma tatsächlich durch "PDFSharp-extended" produziert wird. Dazu stecke ich vermutlich nicht tief genug in diesem Thema. ;-)
Aber es scheint so zu sein, dass eine DLL aus den Projekten ZUGFeRD.PDF oder PDFSharp einen falschen Token oder eine falsche Version adressiert. Darauf habe ich halt keinerlei Einfluss oder auch tiefere Einsicht.

Komplett auf .NET Core umzustellen ist so eine Sache, da es sich um ein relativ umfangreiches Projekt handelt und es vermutlich Monate dauert, dies umzustellen. Aber eigentlich brauchen wir das ja auch gar nicht, weil wir ausschließlich Windows als Plattform nutzen.

**Comment by conceptcase** [comment]
Es sollte doch auch so möglich sein, ZUGFeRD PDF's zu erstellen.
Die X-Rechnungen funktionieren ja auch absolut reibungslos und fehlerfrei, so dass diese zu 100% als valide erkannt werden.

**Comment by stephanstapel** [comment]
PDF A/3 ist leider alles andere als trivial. Meines Wissens ist dies die einzige .net Open Source Komponente, die PDF A/3 erzeugen kann. Kommerzielle Alternativen gibt es zuhauf, bei Bedarf kann ich dazu gerne einige Tipps geben.

**Comment by conceptcase** [comment]
Ich bin für jeden Tipp oder Lösung dankbar ... ;-)
Solange es nicht Unsummen kostet.
Aber ich bin ja von dem gesamten Paket richtig begeistert und es funktioniert ja auch alles reibungslos und fehlerfrei.
Deshalb bin ich ja so verzweifelt, weil das eben nicht funzt und vor allem nur an einer Kleinigkeit hängt, so wie ich das momentan einordne.

Vielleicht können wir uns das ja doch mal gemeinsam anschauen :-)

**Comment by conceptcase** [comment]
Hallo Stefan Stapel,
herzlichen Dank für Deine Bemühungen und Hilfestellungen.
Wir haben es jetzt "hinbekommen" ... :-)
Es läuft ... HURRA ... alle ZUGFeRD PDF-Dateien werden korrekt erzeugt und ausgegeben.

Vielen Dank nochmals für dieses tolle Lösung, die ("wenn sie läuft ;-)") richtig suuuper und perfekt ist.

Schöne Feiertag und einen guten Rutsch ins neue Jahr, sowie viel Erfolg weiterhin.
MfG
Horst Gaffron

**Comment by langeengineering** [comment]
@conceptcase darf Ich fragen wie es bei euch nun final geklappt hat? Wir verwenden auch.Net Framework 4.8.

**Comment by conceptcase** [comment]
Der Schlüssel war eigentlich der Hinweis von Stefan Stapel zum "**Zurechtzupfen**" und der "**Umgang**" mit Dependencies im .NET Framework.
Ich habe mal alle "**_app.config_**" (_in unserem Projekt 58 Stück_) Dateien durchsucht und sämtliche "**_packages.config_**" (_bei uns 4 Stück_) in der Entwicklungsumgebung nachgesehen.

Dabei habe ich festgestellt, dass die "**PdfSharp.System**" überall doppelt eingetragen war (_jeweils einmal als Version 1.1.1.0 und 1.2.0.0_), aber beide Male mit dem identischen **Token f94615aa0424f9eb**. Die Einträge für die 1.2.0.0 habe ich alle komplett gelöscht!

      <dependentAssembly>
        <assemblyIdentity name="PdfSharp.System" publicKeyToken="f94615aa0424f9eb" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.0.0" newVersion="1.2.0.0" />
      </dependentAssembly>

      <dependentAssembly>
        <assemblyIdentity name="PdfSharp.System" publicKeyToken="f94615aa0424f9eb" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.1.0" newVersion="1.1.1.0" />
      </dependentAssembly>

Darüber hinaus fand sich die Assembly "**Microsoft.Extensions.Logging.Abstractions**" mit unterschiedlichen Versionen (6.0.0.0 und 9.0.0.0), obwohl diese nur als Version 9.0.0.0 installiert ist. Komischerweise meldete PdfSharp aber hier einen Konflikt, weil die Version 6.0.0.0 erwartet wurde. Ich habe dann die 6 von 62 Einträgen von 9.0.0.0 auf 6.0.0.0 korrigiert (_obwohl die 9.0.0.0 installiert ist_).

      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>

Projekt gespeichert, Entwicklungsumgebung neu gestartet, vollständig kompiliert und schon war alles gut.
Jede **ZUGFeRD PDF** (_Basic, Comfort, EN16931, Extended_) wurde jetzt korrekt erstellt und von den Viewern Quba, Ultramarin und anderen Online-Viewern erkannt. 
Die Tests waren valide und die eingebettete XML fehlerfrei ...

Herzlichen Dank nochmals an @stephanstapel und @günterwirth, die mit ihren Hilfestellungen den richtigen Denkanstoß ausgelöst haben.
Manchmal ist es einfach so, dass man darüber sprechen oder in diesem Fall schreiben muss, um die Windungen im Hirn anzuregen und den Lösungsansatz zu finden ... ;-) ;-)

**Comment by conceptcase** [comment]
https://github.com/stephanstapel/ZUGFeRD-csharp/issues/518#issuecomment-2558455444

 

 

Mit freundlichen Grüßen

Horst Gaffron

 

P 

Bitte berücksichtigen Sie den Schutz unserer Umwelt, bevor Sie diese E-Mail ausdrucken.

Please consider the environment before printing this email.

 

 

 

Von: langeengineering ***@***.***> 
Gesendet: Sonntag, 22. Dezember 2024 06:32
An: stephanstapel/ZUGFeRD-csharp ***@***.***>
Cc: conceptcase ***@***.***>; Mention ***@***.***>
Betreff: Re: [stephanstapel/ZUGFeRD-csharp] Fehler beim Erstellen einer PDF mit InvoicePdfProcessor.SaveToPdfAsync (Issue #518)

 

@conceptcase <https://github.com/conceptcase>  darf Ich fragen wie es bei euch nun final geklappt hat? Wir verwenden auch.Net Framework 4.8.

**Comment by langeengineering** [comment]
@conceptcase vielen Dank für die detaillierte Beschreibung. Ich werde demnächst selbst ins Troubleshooting gehen und berichten!

**Comment by CodesInChaos** [comment]
> Meines Wissens ist dies die einzige .net Open Source Komponente, die PDF A/3 erzeugen kann.

Man kann mit etwas Mühe iTextSharp4 (LGPL) davon überzeugen konformes PDF A/3 auszuspucken und Zugferd einzubetten. Aber die Bibliothek wird seit fast 20 Jahren nicht mehr gewartet, ist also eher nicht zu empfehlen.
