### ISSUE TITLE
ZUGFeRD 2.1.1 - Profile XRECHNUNG

### ISSUE THREAD

**Issue by pkurz** [stephanstapel/ZUGFeRD-csharp#53]
On July 1st the 2.1.1 version of ZUGFeRD released, it added the profile XRECHNUNG.
The difference in the example is minimal to the comfort (en16391/) profile.
I've gone ahead and compared the two profiles: [diffchecker.com](https://www.diffchecker.com/G6AVg4r9)
Specification: [download link](https://www.awv-net.de/updates/zugferd211/zugferd211de.zip)

**Comment by stephanstapel** [comment]
Thanks for the diff.
I think now it is time to redesign the profile allocation/ writing of the zugferd invoice in different versions.

Imho the only feasible option is to throw an exception when an invoice is written with an unsupported profile for the desired zugferd version.

I.e.:
```csharp
InvoiceDescriptor descriptor = InvoiceDescriptor.CreateInvoice(......);
descriptor.Profile =Profile.XRechnung;

try
{
  descriptor.Save("zugferd-v1.xml", ZUGFeRDVersion.Version1); // save as version 1.x
}
catch (ZUGFeRDException ex)
{
  // exception will be thrown since profile is not supported
}


try
{
  descriptor.Save("zugferd-v1.xml", ZUGFeRDVersion.Version21); // save as version 2.1.x
}
catch (ZUGFeRDException ex)
{
  // exception will NOT be thrown
}
```

**Comment by pkurz** [comment]
Yes that sounds about right, same for basic wl which was introduced in 2.0 IIRC.

**Comment by stephanstapel** [comment]
Yes, you are right:

```csharp
InvoiceDescriptor descriptor = InvoiceDescriptor.CreateInvoice(......);
descriptor.Profile =Profile.XRechnung;

try
{
  descriptor.Save("zugferd-v1.xml", ZUGFeRDVersion.Version1); // save as version 1.x
}
catch (ZUGFeRDException ex)
{
  // exception will be thrown since profile is not supported
}


InvoiceDescriptor descriptor = InvoiceDescriptor.CreateInvoice(......);
descriptor.Profile =Profile.BasicWL;

try
{
  descriptor.Save("zugferd-v1.xml", ZUGFeRDVersion.Version2); // save as version 2.0
}
catch (ZUGFeRDException ex)
{
  // exception will be thrown since profile is not supported
}



try
{
  descriptor.Save("zugferd-v1.xml", ZUGFeRDVersion.Version21); // save as version 2.1.x
}
catch (ZUGFeRDException ex)
{
  // exception will NOT be thrown
}
```

**Comment by pkurz** [comment]
Just read the ReadMe that was attached to the documentation of 2.1.1 and there is written:
`Version 2.0. vom 21.3.2019: Weitere Schemata zugefügt:
     "Schema\BASIC und MINIMUM\zugferd2p0_basicwl_minimum_codedb.xml"
     "Schema\EN16931\zugferd2p0_en16931_codedb.xml"
     "Schema\EXTENDED\zugferd2p0_extended_codedb.xml"`
So in 2.0 Basic/Minimum/en16931(comfort) and extended were added and all of those must throw an exception in v1

**Comment by stephanstapel** [comment]
If you have some minutes, could you create a matrix of supported profiles and versions? It'd be great to add this to the readme.md on the front page!

**Comment by pkurz** [comment]
Sure!
| Profile         	| Version1 	| Version2 	| Version21 	|
|-----------------	|----------	|----------	|-----------	|
| MINIMUM         	|          	| X        	| X         	|
| BASIC WL        	|          	| X        	| X         	|
| BASIC           	| X        	| X        	| X         	|
| COMFORT/EN16391 	| X        	| X        	| X         	|
| XRECHNUNG       	|          	|          	| X         	|
| EXTENDED        	| X        	| X        	| X         	|

Thats what i gathered, it seems in 1.0 there was basic, comfort and extended

**Comment by stephanstapel** [comment]
another option would be to make the Profile property read only and set it when writing the actual invoice:

```csharp
InvoiceDescriptor descriptor = InvoiceDescriptor.CreateInvoice(......);
// descriptor.Profile =Profile.XRechnung; // not possible because it would be read only

try
{
  descriptor.Save("zugferd-v1.xml", ZUGFeRDVersion.Version1, Profile.Comfort); // save as version 1.x
}
catch (ZUGFeRDException ex)
{
  // no exception
}
```

Any thoughts on both alternatives?
