### ISSUE TITLE
*ReferencedDocument IssuerAssignedID ist im InvoiceDescriptor21Reader noch ID

### ISSUE THREAD

**Issue by naschine** [stephanstapel/ZUGFeRD-csharp#62]
Siehe z.B.: https://github.com/stephanstapel/ZUGFeRD-csharp/blob/eb10475393b735c0cd5587bda1213206e0e23c61/ZUGFeRD/InvoiceDescriptor21Reader.cs#L112

ID wurder zu IssuerAssignedID in ZUGFeRD 2.1 bei den folgenden XML Knoten:

 - BuyerOrderReferencedDocument
 - DeliveryNoteReferencedDocument
 - AdditionalReferencedDocument
 - ContractReferencedDocument

EDIT: ebenso im Writer

**Comment by stephanstapel** [comment]
Kannst Du Dir den neuen Code-Stand ansehen:

https://github.com/stephanstapel/ZUGFeRD-csharp/commit/d6d864df19eee71fef7e5204c5b4bccd96b690c1

ich habe auch die Darstellung der DateTimeStrings an die aktuelle Dokumentation angepasst.

**Comment by naschine** [comment]
Sorry for writing German in the first issue.

Thanks for the quick fix! And you're right, ZUGFeRD 2.0 was already IssuerAssignedID as well.

Found a rather nice listing with differences on https://www.mustangproject.org/zugferd/?lang=de

**Comment by naschine** [comment]
Seems the code changes didn't make it into 4.0.0 and the master branch?

**Comment by stephanstapel** [comment]
I'm currently away from my dev machine but checked the code, it looks like this:

![grafik](https://user-images.githubusercontent.com/2912080/96844324-a8174000-144f-11eb-9543-31141c47ce1d.png)

can you please re-check if you are using the most up to date version (or try the github version)?
Otherwise I'll check later today.

**Comment by naschine** [comment]
# 4.0.0 InvoiceDescriptor21Writer:
- DeliveryNoteReferencedDocument
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/c08da62ba0e68d00c04fd216acd33481266afbce/ZUGFeRD/InvoiceDescriptor21Writer.cs#L323
- AdditionalReferencedDocument
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/c08da62ba0e68d00c04fd216acd33481266afbce/ZUGFeRD/InvoiceDescriptor21Writer.cs#L466


# 4.0.0 InvoiceDescriptor21Reader:
- BuyerOrderReferencedDocument (Fallback? It's correctly adressed in line 308 and following)
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/c08da62ba0e68d00c04fd216acd33481266afbce/ZUGFeRD/InvoiceDescriptor21Reader.cs#L373
- DeliveryNoteReferencedDocument
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/c08da62ba0e68d00c04fd216acd33481266afbce/ZUGFeRD/InvoiceDescriptor21Reader.cs#L112
- ContractReferencedDocument (Correct, but code doubled)
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/c08da62ba0e68d00c04fd216acd33481266afbce/ZUGFeRD/InvoiceDescriptor21Reader.cs#L396
and
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/c08da62ba0e68d00c04fd216acd33481266afbce/ZUGFeRD/InvoiceDescriptor21Reader.cs#L417

These are all the occurences I found, quickly skimming through the writer and the reader without taking scopes too much into account. Please have a look for yourself, thanks!

**Comment by stephanstapel** [comment]
For the reader you are right (fixed in latest commit, thanks). The curent code for the writer however is different and correct in terms of handling IssuerAssignedId. Are you sure that you are reviewing the master branch?

**Comment by naschine** [comment]
I used the master branch tagged 4.0.0 files. So it's entirely possible, that in later commits it was already fixed for the writer.

**Comment by stephanstapel** [comment]
Thanks. It's fixed now everywhere.
