### ISSUE TITLE
Intellisense Kommentare für NuGet package

### ISSUE THREAD

**Issue by dsn27** [stephanstapel/ZUGFeRD-csharp#64]
Hi.

Vielen Dank für die tolle Arbeit die du hier geleistet hast.

Ich hab die neuste Version vom NuGet package in Visual Studio heruntergeladen.
Kommentare aus dem Quelltext werden jedoch in Intellisense nicht angezeigt.
Diese sind aber super praktisch um die Bedeutung eines Enums zu verstehen z.B. TaxRegistrationSchemeID.VA

Es scheint das die XML Dokumentation nicht mit ausgegeben wird.
[https://stackoverflow.com/questions/43305578/show-comments-in-nuget-package](https://stackoverflow.com/questions/43305578/show-comments-in-nuget-package)

Wäre toll wenn du diese noch hinzufügen könntest.

Danke!

Schöne Grüße
Michel

**Comment by stephanstapel** [comment]
sehr gerne. Vielen Dank für das Feedback.
Ich finde es immer großartig, wenn direkt der Lösungsvorschlag mit gepostet wird. Das macht es mir einfacher 👍 

Kannst Du Dir das aktualisierte nuget Package einmal ansehen?

**Comment by dsn27** [comment]
Dank dir für die schnelle Reaktion.

Läuft!
