### ISSUE TITLE
XRechnung 

### ISSUE THREAD

**Issue by AndreasWaning** [stephanstapel/ZUGFeRD-csharp#65]
Hallo zusammen,

ich habe mir den Source Code inkl. Test Project runtergeladen.
Wenn ich die Rechnung mit:
            string path = "output.xml";
            InvoiceDescriptor desc = _createInvoice();
            desc.Save(path, ZUGFeRDVersion.Version21, Profile.XRechnung);
speicher, bekomme ich mit jedem Validator Fehlermeldung !

Was mache ich da falsch ?
Man kann doch XRechnung erstellen, oder ?

Oder muss ich warten bis V2.1.1 kommt ?

**Comment by stephanstapel** [comment]
Ja, XRechnung kann man erzeugen. Bekannt ist, dass die Validatoren fehlerbehaftet sind. Welchen verwenden Sie?

**Comment by AndreasWaning** [comment]
z. B. den:
https://www.epoconsulting.com/erechnung/xrechnung-validator

Offizieller Kosit Validator !!!  Da sind 2 Bsp XRechnungen , die keine Fehlermelden !

**Comment by stephanstapel** [comment]
Es gibt keinen Grund für 4 Ausrufungszeichen in einem Open Source-Projekt.

Ich habe einige der vom Validator gemeldeten Fehler korrigiert. Es gibt nun einige Summenthemen, die noch moniert werden, ihre wäre ich für Unterstützung dankbar:

![image](https://user-images.githubusercontent.com/2912080/91071921-0b941580-e639-11ea-9260-8bd951591d9f.png)

Diese Meldung:

![image](https://user-images.githubusercontent.com/2912080/91071861-fa4b0900-e638-11ea-81ab-28c77781ebb0.png)

scheint ein Validator-Fehler zu sein.

**Comment by AndreasWaning** [comment]
Hallo Stephan,  danke für die Antwort und sorry für die Rufzeichen. Da hab ich mir nix bei gedacht.

Gruß Andreas

**Comment by stephanstapel** [comment]
ersetzt durch #68, #69, #70
