### ISSUE TITLE
Hardcoded path to documentation XML file

### ISSUE THREAD

**Issue by SandraEickel** [stephanstapel/ZUGFeRD-csharp#66]
ZUGFeRD/ZUGFeRD.csproj references DocumentationFile E:\develop\ZUGFeRD\s2industries.ZUGFeRD.xml.
I don't have a drive E:.
Issue can be fixed by unsing GenerateDocumentationFile instead and setting this to true (and moving this to the main PropertyGroup without conditions.
I've fixed this in my fork.

**Comment by stephanstapel** [comment]
sounds good. As you just mentioned in one of your earlier messages, this is a bug in Visual Studio. Feel free to issue a pull request.

**Comment by stephanstapel** [comment]
fixed by https://github.com/stephanstapel/ZUGFeRD-csharp/pull/67
