### ISSUE TITLE
XRechnung: Consider modifying handling of SellerTradeParty

### ISSUE THREAD

**Issue by stephanstapel** [stephanstapel/ZUGFeRD-csharp#68]
![image](https://user-images.githubusercontent.com/2912080/91086814-b9aaba00-e64f-11ea-88de-4af226582481.png)

```xml
<ram:SellerTradeParty>
        <ram:GlobalID schemeID="0088">4000001123452</ram:GlobalID>
        <ram:Name>Lieferant GmbH</ram:Name>
        <ram:DefinedTradeContact />
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>80333</ram:PostcodeCode>
          <ram:LineOne>Lieferantenstraße 20</ram:LineOne>
          <ram:CityName>München</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">201/113/40209</ram:ID>
        </ram:SpecifiedTaxRegistration>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">DE123456789</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:SellerTradeParty>
```

**Comment by AndreasWaning** [comment]
Hallo Stephan,
so sieht das aus, in der XRechnung.xml, wo der Validator nicht meckert:

<ram:SellerTradeParty>
  <ram:GlobalID schemeID="0088">4000001123452</ram:GlobalID>
  <ram:Name>Lieferant GmbH</ram:Name>
  <ram:DefinedTradeContact>
    <ram:PersonName>Max Mustermann</ram:PersonName>
    <ram:DepartmentName>Muster-Einkauf</ram:DepartmentName>
    <ram:TelephoneUniversalCommunication>
      <ram:CompleteNumber>+49891234567</ram:CompleteNumber>
    </ram:TelephoneUniversalCommunication>_
    <ram:EmailURIUniversalCommunication>
      <ram:URIID>Max@Mustermann.de</ram:URIID>
    </ram:EmailURIUniversalCommunication>**
  </ram:DefinedTradeContact>
  <ram:PostalTradeAddress>
    <ram:PostcodeCode>80333</ram:PostcodeCode>
    <ram:LineOne>Lieferantenstraße 20</ram:LineOne>
    <ram:CityName>München</ram:CityName>
    <ram:CountryID>DE</ram:CountryID>
  </ram:PostalTradeAddress>
  <ram:SpecifiedTaxRegistration>
    <ram:ID schemeID="FC">201/113/40209</ram:ID>
  </ram:SpecifiedTaxRegistration>
  <ram:SpecifiedTaxRegistration>
    <ram:ID schemeID="VA">DE123456789</ram:ID>
  </ram:SpecifiedTaxRegistration>
</ram:SellerTradeParty>

**Comment by stephanstapel** [comment]
danke. Es ist schon klar, welche Felder gefüllt sein müssen. Das Problem ist, dass die Bibliothek das Füllen dieser Felder nicht erzwingt:

Werden die Felder mit Hilfe von SetSellerContact() gefüllt, klappt die Validierung. 
Werden die Felder nicht per SetSellerContact() gefüllt, klappt die Validierung nicht.

D.h. der Erfolg ist dem Benutzer überlassen, der bekommt aber keinen Hinweis darauf, dass das Ergebnis womöglich nicht korrekt ist.
