### ISSUE TITLE
Forgot to remove ', false' in Line 180 of InvoiceDescriptor21Writer.cs?

### ISSUE THREAD

**Issue by SandraEickel** [stephanstapel/ZUGFeRD-csharp#71]
In a lot of places ', false' was removed from lines like
Writer.WriteValue(_formatDate(tradeLineItem.BuyerOrderReferencedDocument.IssueDateTime.Value, false));
but not from line 180 of ZUGFeRD/InvoiceDescriptor21Writer.cs

The generated file ZUGFeRD/s2industries.ZUGFeRD.xml (in my tests, this file did not appear directly in ZUGFeRD) contains information about badly formatted XML in the following lines
53 
1379 

Between lines 1421 and 1422 the information, in which profiles this is availabe, is missing. 

Line 1469 contains additional '///'.

Line 1539 misses a 'd'.

Line 1575 shoud read 'Quadratmeter'.

Lines 2094, 2124 and 2129 lack a non-empty summary.

**Comment by stephanstapel** [comment]
I'll dive into the code and check which representation of datetime should be displayed.

Could you split the second issue into a dedicated issue (and before check if the problem is still present in the current code)?

**Comment by SandraEickel** [comment]
Above happened while reviewing the diffs before merging your then fresh code into my fork ...

I'll create a new issue for the XML documentation ... or perhaps I'll fix some of them ...
