### ISSUE TITLE
Error BR-21 and BR25 See Comment AW, Name and LineID should have a value !

### ISSUE THREAD

**Issue by AndreasWaning** [stephanstapel/ZUGFeRD-csharp#72]
![image](https://user-images.githubusercontent.com/11454642/91202895-bb818580-e702-11ea-9d2e-97167c51e3c9.png)

       public void addTradeLineCommentItem(string comment)
        {
            TradeLineItem item = new TradeLineItem()
            {
                //AW
                Name="ComentItem",

                AssociatedDocument = new ZUGFeRD.AssociatedDocument(),
                
                GrossUnitPrice = 0m,
                NetUnitPrice= 0m,
                BilledQuantity = 0m
            };

            item.AssociatedDocument.Notes.Add(new Note(
                content: comment,
                subjectCode: SubjectCodes.Unknown,
                contentCode: ContentCodes.Unknown
            ));

            //AW
            item.AssociatedDocument.LineID=0;

            this.TradeLineItems.Add(item);
        } // !addTradeLineCommentItem()

**Comment by stephanstapel** [comment]
Duplikat von #69
