### ISSUE TITLE
InvoiceType codes missing, wrong, code duplication in writers

### ISSUE THREAD

**Issue by SandraEickel** [stephanstapel/ZUGFeRD-csharp#73]
See "ZUGFeRD-2.1.1 - Spezifikation_TA.pdf", Page 24.

Currently, we have 380, 381, 383, 389 and 1380 which should be 384 (1380 should be kept for compatibilty, but only accepted for reading purposes).
Of the recommended codes 261, 386 and 326 are missing.
For MINIMUM and BASIC WL profiles, 751 is required (in Germany).
The given UNTDID 1001 subset contains many more coders which should be supported.

_translateInvoiceType and _encodeInvoiceType should be handled like other enumerations instead of being copied to each InvoiceDescriptor_Writer.

Parts of those other EnumExtentions are ugly enough.

Instead of creating an EnumToString function, which in turn doesn't do anything else than ToString with g format which itself is just the default for a plain ToString, one should just use ToString directly.

Some Enums do not set Unkown = 0, which is a bad thing.
The CountryCodes should have their numeric value attached.
SubjectCodes should also be updated accoring to the documentation for 2.1.1.

**Comment by stephanstapel** [comment]
I think this is closed by #77 ?
