### ISSUE TITLE
Rule BR-S-02 and BR-CO-26 throw an error even though BT-31 is present

### ISSUE THREAD

**Issue by pkurz** [stephanstapel/ZUGFeRD-csharp#75]
![grafik](https://user-images.githubusercontent.com/54670146/91733452-d2fcba80-eba9-11ea-926f-e51b450d4605.png)

So i'm receiving these errors, even though i have the field BT-31 present, do i need the other fields?

```xml
  <ram:SellerTradeParty>
        <ram:Name>Company Name</ram:Name>
        <ram:DefinedTradeContact>
          <ram:PersonName>Person</ram:PersonName>
          <ram:TelephoneUniversalCommunication>
            <ram:CompleteNumber>01234567890</ram:CompleteNumber>
          </ram:TelephoneUniversalCommunication>
          <ram:EmailURIUniversalCommunication>
            <ram:URIID>email@email.com</ram:URIID>
          </ram:EmailURIUniversalCommunication>
        </ram:DefinedTradeContact>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>00000</ram:PostcodeCode>
          <ram:LineOne>Street 12</ram:LineOne>
          <ram:CityName>Any City</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">TaxRegistration1</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:SellerTradeParty>
```

**Comment by stephanstapel** [comment]
Honestly, these business rules are a nightmare. The standard itself is complicated enough. But evaluating different fields to match certain scenarios is just horror.

Concerning BR-S-02, maybe should try and add BT-32:

`
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:SellerTra
deParty/ram:SpecifiedTaxRegistration/ram:ID, 
@schemeID="FC"
`

Concerning BR-CO-26:

BT-29 is defined as:

`
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:SellerTra
deParty/ram:GlobalID/@schemeID
`

BT-30:

`
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:SellerTra
deParty/ram:SpecifiedLegalOrganization/ram:ID
`


Let's start step by step. Could you add BT-32 to your document and then we continue?

**Comment by pkurz** [comment]
Okay, adding BT-32 fixed the first one.
If i research for BT-29 i found this article (in german) [bund.de](https://xrechnung.bund.de/prod/er_files/nutzungsbedingungen_de.jsp), if you search for bt-29 it is written that is only needed if it is known. And isn't needed when not known.
And also in the documentation is written that BT-30 is not needed, and if left out it should be known to both parties.

**Comment by stephanstapel** [comment]
I can only add to this. Matching all these business rules imho is impossible.
So shall we leave things as they are or should I implement e.g. the 'SpecifiedLegalOrganization' (nobody else after asked for that :) )

**Comment by pkurz** [comment]
Not sure about that tbh. It seems like nobody else ran into this issue, but it seems that it is required by any way. Or i am doing something wrong maybe?

**Comment by stephanstapel** [comment]
Yes, you are certainly also right. But as the link to bund.de said, you can only state things that you have. I guess representing the SellerParty's GlobalID should be possible using the current codebase. Could you try to use it and see if the error is gone?

**Comment by pkurz** [comment]
I can try, but in the current context i do not have that information.

**Comment by pkurz** [comment]
I just looked into the XRechnung example from the documentation, and they used the company name as the GlobalID, maybe thats enough?

**Comment by pkurz** [comment]
Okay i found the problem for this. It is completely not understandable how it something like this can happen in a standard like this. 
[issue in kosit validator](https://github.com/itplr-kosit/validator-configuration-xrechnung/issues/5).

**Comment by stephanstapel** [comment]
you are kidding. Just like https://github.com/stephanstapel/ZUGFeRD-csharp/issues/56. So shall we close this?

**Comment by pkurz** [comment]
Yeah, and the validator from [epoconsulting.com](https://www.epoconsulting.com/erechnung/xrechnung-validator) should not be used anymore!
