### ISSUE TITLE
Code example is deprecated and creates an invalid CII format

### ISSUE THREAD

**Issue by aschliewert** [stephanstapel/ZUGFeRD-csharp#78]
Hi. 
Is it possible to get an working code example which creates a valid XRechnung in the CII format? Maybe the code example in the ReadMe File could be updated? Whatever I do, the validator throws many errors.

Thanks in advance.

**Comment by stephanstapel** [comment]
Sounds reasonable. If I set up a new example, could you check it with all validators (for 1.x, 2.1 and XRechnung)?

**Comment by aschliewert** [comment]
I am using online validators for XRechnung CII format for version 2.1. But I can try.

**Comment by aschliewert** [comment]
One of the validators I am using is https://www.epoconsulting.com/erechnung/xrechnung-validator (KoSIT Validator).

**Comment by stephanstapel** [comment]
Yes, that's the most famous one.
Did you see this though: https://github.com/stephanstapel/ZUGFeRD-csharp/issues/75 ?

**Comment by pkurz** [comment]
@aschliewert i wouldn't recommend this one. You can set up the official kosit validator yourself. Just search for the github repo and follow the steps. There is a XRechnung configuration in the readme, follow the instructions of the configuration and you should be up and running and you should be able to verify your documents.

**Comment by stephanstapel** [comment]
I have updated the example in the test application (https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD-Test/Application.cs).
It now matches 99.9% with https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/documentation/zuferd211/Beispiele/XRECHNUNG/zugferd_2p1_XRECHNUNG_Einfach.pdf.

**Comment by stephanstapel** [comment]
I guess this is finished? Can we close this issue?

**Comment by aschliewert** [comment]
Hi. Thank you for all the answeres and your quick help. Yes this issue can be closed.
