### ISSUE TITLE
node info for totals is not equal to specyfication

### ISSUE THREAD

**Issue by K2-Software** [stephanstapel/ZUGFeRD-csharp#79]
in zugferd 1.0 reader we try to read node 
"ram:SpecifiedTradeSettlementHeaderMonetarySummation"
but in specyfication of zugferd is 
"ram:SpecifiedTradeSettlementMonetarySummation"

in zugferd 2.0 writer we have node:
"ram:SpecifiedTradeSettlementMonetarySummation"
but in specyfication is
"ram:SpecifiedTradeSettlementHeaderMonetarySummation"

#76 Solved in pull request

**Comment by stephanstapel** [comment]
solved

**Comment by K2-Software** [comment]
> solved. Thanks!

no problem. When You will create a new NuGet?

**Comment by stephanstapel** [comment]
I'm just waiting for an updated pull request for:
https://github.com/stephanstapel/ZUGFeRD-csharp/pull/77
Then I'd throw a new package in, most likeley it'll be a new major version since there are some changes that break old code.

**Comment by stephanstapel** [comment]
I published 4.0.0 beta (prelease) on nuget. It should appear there in a couple of minutes.

**Comment by K2-Software** [comment]
we have tested it on our side, all invoices now get valid info from the node.

**Comment by euphilein** [comment]
@stephanstapel what are the open issues/requirements which prevent the stable release of the nuget? Can we help to test/complete some pending work?

**Comment by stephanstapel** [comment]
@euphilein : no there is nothing that prevents us from releasing. I was just working on other projects.
