### ISSUE TITLE
Zeilenbetrag beim Import fehlt?

### ISSUE THREAD

**Issue by KVS-CBL** [stephanstapel/ZUGFeRD-csharp#8]
Hallo,

sehe ich es richtig, dass es beim Import einer ZUGFeRD-Datei  nicht möglich ist auf den Zeilenbetrag zuzugreifen?
Gemeint ist das Element mit dem XPath `/rsm:CrossIndustryDocument/rsm:SpecifiedSupplyChainTradeTransaction/ram:IncludedSupplyChainTradeLineItem/ram:SpecifiedSupplyChainTradeSettlement/ram:SpecifiedTradeSettlementMonetarySummation/ram:LineTotalAmount`

Gerade bei Rechnung im Basic-Profile wäre dies wichtig, da hier (zumindest im FeRD Beispiel
[ZUGFeRD_1p0_BASIC_Einfach.pdf](https://github.com/stephanstapel/ZUGFeRD-csharp/files/524958/ZUGFeRD_1p0_BASIC_Einfach.pdf)) außer Menge und Zeilenbetrag nichts enhalten ist.

**Comment by stephanstapel** [comment]
Hallo,
kannst Du mir ein vollständiges Beispiel schicken? Gerne auch per Mail (vorname.nachname@web.de), falls vertraulich. Dann baue ich das fix ein!
Danke!
Stephan

**Comment by stephanstapel** [comment]
fixed with commit https://github.com/stephanstapel/ZUGFeRD-csharp/commit/24b9637b3c1742cb2b28ea3659c05440c5896f01.
