### ISSUE TITLE
Is the library support Extract/Insert into PDF?

### ISSUE THREAD

**Issue by jdevillard** [stephanstapel/ZUGFeRD-csharp#82]
Hello, 

I'm currently looking at Factur-X format.
I would like to take a look at this library, is this library support the read/write of invoice from/to PDF file? 

Thanks.

**Comment by stephanstapel** [comment]
This library only supports reading and writing the xml files you need.

Concerning generating pdf/a along with attachments, I can recommend PDF Tools (https://www.pdf-tools.com/pdf20/en/products/pdf-converter-validation/pdf-to-pdfa-converter/).

Concerning reading attachments from pdf, itextsharp is a good choice:
https://stackoverflow.com/questions/6305505/how-do-i-extract-attachments-from-a-pdf-file
