### ISSUE TITLE
Upgrading to 4.0.0 breaks ZUGFeRD on vb.net

### ISSUE THREAD

**Issue by styletronix** [stephanstapel/ZUGFeRD-csharp#83]
I just upgraded to 4.0.0 but ZUGFeRD is no longer usable in vb.net because there are functions like "**a**ddTradeLineCommentItem" and "**A**ddTradeLineCommentItem". 

while **a**ddTradeLineCommentItem is marked as obsolete, I can't use **A**ddTradeLineCommentItem because Visual Basic is case insensitive.

Should I use a completely different function for addTradeLineCommentItem or what Is the supposed way to use this functon?

**Comment by stephanstapel** [comment]
Hi,
Oh. I wasn't aware of such issues, since I'm working c# only. I'm sorry. Could you stay with 3.2.x for so long?

**Comment by styletronix** [comment]
Sure. Thanks.

**Comment by TomcatBB** [comment]
me again :-), i trapped into the same problem, because we are still using VB.NET in our project

**Comment by stephanstapel** [comment]
I'll definitely ship version 5.0 soon (during October 2020) with the API cleaned up so that this problem will vanish. Just waiting for the pull request for #92.

**Comment by stephanstapel** [comment]
Version 5.0.0 is out. Everything should be fine now.
