### ISSUE TITLE
DeliveryNoteReferencedDocument has wrong elements

### ISSUE THREAD

**Issue by alexruett** [stephanstapel/ZUGFeRD-csharp#84]
I'm using version 4.0.0.
The element "DeliveryNoteReferencedDocument" writes theses Elements:
IssueDateTime
ID

According to the documentation 2.1.1 of 01.07.2020 it should be:
IssuerAssignedID
FormattedIssueDateTime (with sub elements DateTimeString and format)

Maybe you can verify this?
Thanks alot.

**Comment by stephanstapel** [comment]
Fixed my last commit
