### ISSUE TITLE
currencyID is not allowed in GrossPriceProductTradePrice and others

### ISSUE THREAD

**Issue by alexruett** [stephanstapel/ZUGFeRD-csharp#86]
In spezifikation 2.1.1 the attribute **currencyID** is only allowed in these elements:
TaxBasisTotalAmount
TaxTotalAmount
GrandTotalAmount

And not in:
BasisAmount
ActualAmount
LineTotalAmount
GrossPriceProductTradePrice 
[...]

**Comment by stephanstapel** [comment]
not sure.
E.g. BasisAmount is defined with data type udt:AmountType:

![image](https://user-images.githubusercontent.com/2912080/93384126-eaec6380-f864-11ea-9a80-2f30345f410a.png)

and udt:AmountType is defined as:

![image](https://user-images.githubusercontent.com/2912080/93384333-fc357000-f864-11ea-8806-f7552cd702ac.png)

**Comment by alexruett** [comment]
In FACTUR-X_EXTENDED.sch it says:

`  <pattern>
    <rule context="/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:LineTotalAmount[@currencyID]">
      <report test="true()">
	Attribute @currencyID' marked as not used in the given context.</report>
    </rule>
  </pattern>
`

**Comment by stephanstapel** [comment]
alright, looking for your pull request.

**Comment by alexruett** [comment]
I tried to push a branch at to create a pull request, but I got error 403 in the github console. I dont't know, what's wrong here.

**Comment by stephanstapel** [comment]
That's strange. Maybe you are logged in with wrong credentials in github (or none at all)?
Feel free to send the diff if it's not working.

**Comment by alexruett** [comment]
[removedcurrencyid.zip](https://github.com/stephanstapel/ZUGFeRD-csharp/files/5237568/removedcurrencyid.zip)
Maybe it's Visual studio or just me. 
Anyway, please finde my changes in the attached file. Two new files and the changed InvoiceDescriptor21Writer.cs.

**Comment by stephanstapel** [comment]
Ok, thanks. However my goal is not to remove the literal element and attribute names so I'll revert that change.

**Comment by alexruett** [comment]
It's your repository, so that's totally up to you. IMHO it's not correct according to the specifications, so maybe I have to decide, whether to create my own fork or look somewhere else.
Anyhow, thanks for considering it and for your work in general.

**Comment by stephanstapel** [comment]
You might have got me wrong. I'll include the change around removing currencyId but not go fo the symbolic representation of the element and attribute names.

**Comment by alexruett** [comment]
Oh, ok. I really misunderstood that. Leaving the literals is not my style (obviously), but doesn't effect the main aspect of this issue. So, thanks.
(Though I would like to hear the argument against the symbolic representation for the sake of discussion).
