### ISSUE TITLE
XRechnung lässt sich nicht validieren

### ISSUE THREAD

**Issue by hypers1** [stephanstapel/ZUGFeRD-csharp#87]
Ich bekomme beim Validieren der XRechnung (auch wenn ich die Datei mit dem Demoprogramm erstelle) immer folgende Meldung:

XML Schema | schemas/ubl21/maindoc/UBL-Invoice-2.1.xsd
Error message: [SAX] cvc-elt.1.a: Cannot find the declaration of element 'rsm:CrossIndustryInvoice'.
Technical details: cvc-elt.1.a: Cannot find the declaration of element 'rsm:CrossIndustryInvoice'.

Ich nutze folgenden Validator: 
https://ecosio.com/de/peppol-und-xml-dokumente-online-validieren/

Ist der Validator fehlerhaft oder passt die Umsetzung für XRechnung noch nicht?

[xrechnung.zip](https://github.com/stephanstapel/ZUGFeRD-csharp/files/5237433/xrechnung.zip)

**Comment by stephanstapel** [comment]
Nimm mal CII:

![grafik](https://user-images.githubusercontent.com/2912080/93450933-d47ef000-f8d6-11ea-8b03-ec92fc278663.png)
