### ISSUE TITLE
XmlDocument.Load(stream); not Closing File Stream

### ISSUE THREAD

**Issue by ROBdk97** [stephanstapel/ZUGFeRD-csharp#88]
In every InvoiceDescriptorReader Version the doc.Load(stram) does not close the file stream which is a known issue with the XmlDocument from .net. Maybe you should do it this way:

```csharp
XmlDocument doc = new XmlDocument();
using (XmlReader xmlReader = XmlReader.Create(stream)){
    doc.Load(xmlReader);
    xmlReader.Close();
}
```

instead of
```csharp
XmlDocument doc = new XmlDocument();
doc.Load(stream);
```

**Comment by stephanstapel** [comment]
The library relies on the stream being open when invoked so it also doesn't close the stream.

**Comment by ROBdk97** [comment]
Well but after you loaded the file why would you need the file to be still open?

**Comment by stephanstapel** [comment]
That is right. But it's not the library's stream, it is just used in there. The stream is created and opened outside, filled in the library and the rest is up to the user.

You raised a good point though: I added documentation to the Load and Save methods to make everyone aware of this fact.

**Comment by ROBdk97** [comment]
Even if you close the stream yourself, the libary still has the stream opened. Thats why I report the issue
