### ISSUE TITLE
SpecifiedTradeAllowanceCharge -> ChargeIndicator -> Indicator is always true

### ISSUE THREAD

**Issue by aschliewert** [stephanstapel/ZUGFeRD-csharp#89]
If I try to add TradeAllowenceCharge with the AddTradeAllowanceCharge() function, it always translates the indicator to true even if I put false into the function.

**Comment by stephanstapel** [comment]
Hi, which ZUGFeRD version are you generating?

**Comment by aschliewert** [comment]
Hi, I am using ZUGFeRD version 2.1 and with profile XRechnung. The version of the library I am using is 4.0.0.

**Comment by stephanstapel** [comment]
I tried to verify the bug using the _createInvoice() function in the test application.
I added

`desc.AddTradeAllowanceCharge(false, 10.0m, CurrencyCodes.EUR, 9.0m, "Reason x", TaxTypes.VAT, TaxCategoryCodes.A, 19.0m);`

which generated:

![image](https://user-images.githubusercontent.com/2912080/94071560-65345f00-fdf4-11ea-87e3-aaa3b12b1585.png)

Then I modified the code:

`desc.AddTradeAllowanceCharge(true, 10.0m, CurrencyCodes.EUR, 9.0m, "Reason x", TaxTypes.VAT, TaxCategoryCodes.A, 19.0m);`

which generated:

![image](https://user-images.githubusercontent.com/2912080/94071594-7c734c80-fdf4-11ea-8225-192e1251cb81.png)

so everything seems to be alright. Am I missing anything here?

**Comment by stephanstapel** [comment]
I did the same on item level:

`item.AddTradeAllowanceCharge(false, CurrencyCodes.EUR, 11.0m, 2.0m, "reason y");`

which results in:

![image](https://user-images.githubusercontent.com/2912080/94072469-02dc5e00-fdf6-11ea-9968-52e315e412de.png)

and

`item.AddTradeAllowanceCharge(true, CurrencyCodes.EUR, 11.0m, 2.0m, "reason y");`

resulting in:

![image](https://user-images.githubusercontent.com/2912080/94072502-15ef2e00-fdf6-11ea-8c6c-2767eef04a4e.png)

**Comment by aschliewert** [comment]
Oh this is my fault. I didn't know that the function inverts the value and had only used invoices with discounts so far. Thank you for the quick response and the effort. So I close the issue.

**Comment by aschliewert** [comment]
That sounds really good. Thank you.
