### ISSUE TITLE
Leeres TradeLineItem wenn AssociatedDocumentLineDocument vorhanden

### ISSUE THREAD

**Issue by KVS-CBL** [stephanstapel/ZUGFeRD-csharp#9]
Hallo,
die Methode _parseTradeLineItem im InvoiceDescriptorReader wird abegbrochen wenn AssociatedDocumentLineDocument/IncludedNote/Content gefüllt ist (InvoiceDescriptorReader.cs Zeile ca. 166).
In der Beispieldatei [ZUGFeRD_1p0_COMFORT_Rabatte.pdf](https://github.com/stephanstapel/ZUGFeRD-csharp/files/550883/ZUGFeRD_1p0_COMFORT_Rabatte.pdf) wird hierdurch aber eine relevante Zeile (Pfand) übersprungen bzw. nur die Bemerkung erfasst aber nicht Menge, Einheit, Preis...

**Comment by stephanstapel** [comment]
Hallo,

da war wohl ein richtiger Implementierungsfehler. Ich hatte bis dato angenommen, dass solche Zeilen reine Kommentarzeilen sind.
Das habe ich nun korrigiert. Bevor ich die Datei über nuget bereitstelle, kannst Du bitte einmal diese Version ausprobieren:

[s2industries.ZUGFeRD.dll.zip](https://github.com/stephanstapel/ZUGFeRD-csharp/files/551518/s2industries.ZUGFeRD.dll.zip)

?
Statt des Feldes 'Comment' einer Zeile gibt es nun das Objekt AssociatedDocument.
Insbesondere den Umgang mit den Zeilennummern musste ich nun ändern.
Die Erzeugung des COMFORT_Rabatte-Files klappte schonmal ohne Fehler

**Comment by KVS-CBL** [comment]
Hallo Stephan,

sieht gut aus. Alle Felder werden wie erwartet übergeben.

Danke für die wiedermal schnelle Hilfe.

**Comment by stephanstapel** [comment]
Hallo,

Prima! Kannst Du Dir die Erzeugung ebenfalls ansehen?

Viele Gruesse,

Stephan

**Comment by KVS-CBL** [comment]
Bei der Validierung einer neu generierten Datei bekomme ich einen Fehler wlchen ich bei meinen letzten Test noch nicht hatte.

> Der Nettopreis "3.3333" entspricht nicht dem Bruttopreis abzüglich des Rabatts und zuzüglich des Zuschlags "4.6667".

Dies liegt aber eher an meiner Implementierung als an der DLL.
