### ISSUE TITLE
AdditionalReferencedDocument

### ISSUE THREAD

**Issue by aschliewert** [stephanstapel/ZUGFeRD-csharp#92]
Hello. Could you please explain how I create the following structure? 

<<ram:AdditionalReferencedDocument>>
            <<ram:IssuerAssignedID>>XRechnung-v2.0.0-Syntax-Binding-Extension.pdf</ram:IssuerAssignedID>
            <<ram:Name>>TestName</ram:Name>
            <ram:AttachmentBinaryObject filename="XRechnung-v2.0.0-Syntax-Binding-Extension.pdf"
                                        mimeCode="application/pdf">JVBERi0xLjQKJaqrrK0KMSAwIG9iago8PAovVGl... 
            </ram:AttachmentBinaryObject>
</ram:AdditionalReferencedDocument>

(I'm not sure if this is valid, I've seen it by generating a XRechnung file in CII format on https://xrechnungsgenerator.schuetze.ag)

As far as I've seen, is that not yet possible or have I overlooked it? If this is not yet possible, is it planned to implement it? 

Thank you in advance

**Comment by stephanstapel** [comment]
Hi.
That's not yet possible. If you want, I can guide you to the place where you could implement this and support you.

**Comment by aschliewert** [comment]
Ok I've added new properties to the AdditionalReferencedDocument class, added a function "SetAdditionalReferencedDocument" to InvoiceDecsriptor class and expanded the InvoiceDescriptor1Writer, InvoiceDescriptor20Writer and InvoiceDescriptor21Writer classes which works fine for me. Also I changed the AdditionalReferencedDocument property to an array, because it is possible to add multiple documents.

**Comment by stephanstapel** [comment]
Sounds good. Could you issue a pull request so I can review the changes?
